#pragma comment(linker, "/export:AADTBAcquireToken=\"C:\\Windows\\SysWOW64\\aadtb.AADTBAcquireToken\"")
#pragma comment(linker, "/export:AADTBAcquireTokenEx=\"C:\\Windows\\SysWOW64\\aadtb.AADTBAcquireTokenEx\"")
#pragma comment(linker, "/export:AADTBFreeString=\"C:\\Windows\\SysWOW64\\aadtb.AADTBFreeString\"")
#pragma comment(linker, "/export:AADTBFreeStruct=\"C:\\Windows\\SysWOW64\\aadtb.AADTBFreeStruct\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\aadtb.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\aadtb.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\aadtb.DllGetClassObject\"")
