#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\accessibilitycpl.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\accessibilitycpl.DllGetClassObject\"")
#pragma comment(linker, "/export:DllInstall=\"C:\\Windows\\SysWOW64\\accessibilitycpl.DllInstall\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\accessibilitycpl.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\accessibilitycpl.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\accessibilitycpl.DllUnregisterServer\"")
