#pragma comment(linker, "/export:APIExportForDetours=\"C:\\Windows\\SysWOW64\\AppVEntSubsystems32.dll\"")
#pragma comment(linker, "/export:CurrentThreadIsVirtualized=\"C:\\Windows\\SysWOW64\\AppVEntSubsystems32.dll\"")
#pragma comment(linker, "/export:RequestUnhookedFunctionList=\"C:\\Windows\\SysWOW64\\AppVEntSubsystems32.dll\"")
#pragma comment(linker, "/export:VirtualizeCurrentProcess=\"C:\\Windows\\SysWOW64\\AppVEntSubsystems32.dll\"")
#pragma comment(linker, "/export:VirtualizeCurrentThread=\"C:\\Windows\\SysWOW64\\AppVEntSubsystems32.dll\"")
#pragma comment(linker, "/export:_IsProcessHooked@0=\"C:\\Windows\\SysWOW64\\AppVEntSubsystems32.dll\"")
