#pragma comment(linker, "/export:AppCleanup=\"C:\\Windows\\SysWOW64\\avicap32.dll\"")
#pragma comment(linker, "/export:capCreateCaptureWindowA=\"C:\\Windows\\SysWOW64\\avicap32.dll\"")
#pragma comment(linker, "/export:capCreateCaptureWindowW=\"C:\\Windows\\SysWOW64\\avicap32.dll\"")
#pragma comment(linker, "/export:capGetDriverDescriptionA=\"C:\\Windows\\SysWOW64\\avicap32.dll\"")
#pragma comment(linker, "/export:capGetDriverDescriptionW=\"C:\\Windows\\SysWOW64\\avicap32.dll\"")
#pragma comment(linker, "/export:videoThunk32=\"C:\\Windows\\SysWOW64\\avicap32.dll\"")
