#pragma comment(linker, "/export:AzGenerateAudit=\"C:\\Windows\\SysWOW64\\AzSqlExt.AzGenerateAudit\"")
#pragma comment(linker, "/export:__GetXpVersion=\"C:\\Windows\\SysWOW64\\AzSqlExt.__GetXpVersion\"")
#pragma comment(linker, "/export:xp_AzManAddRole=\"C:\\Windows\\SysWOW64\\AzSqlExt.xp_AzManAddRole\"")
#pragma comment(linker, "/export:xp_AzManAddUserToRole=\"C:\\Windows\\SysWOW64\\AzSqlExt.xp_AzManAddUserToRole\"")
#pragma comment(linker, "/export:xp_AzManDeleteRole=\"C:\\Windows\\SysWOW64\\AzSqlExt.xp_AzManDeleteRole\"")
#pragma comment(linker, "/export:xp_AzManRemoveUserFromRole=\"C:\\Windows\\SysWOW64\\AzSqlExt.xp_AzManRemoveUserFromRole\"")
