#print comment(linker, "/export:BamCreateSettingsClientLib=\"C:\\Windows\\SysWOW64\\BamSettingsClient.dll\"")
#print comment(linker, "/export:BamDestroySettingsClientLib=\"C:\\Windows\\SysWOW64\\BamSettingsClient.dll\"")
#print comment(linker, "/export:BamFreeQueriedApplications=\"C:\\Windows\\SysWOW64\\BamSettingsClient.dll\"")
#print comment(linker, "/export:BamQueryKnownApplications=\"C:\\Windows\\SysWOW64\\BamSettingsClient.dll\"")
#print comment(linker, "/export:BamSetUserManagementState=\"C:\\Windows\\SysWOW64\\BamSettingsClient.dll\"")
