#pragma comment(linker, "/export:BthCollectFingerprintInfo=\"C:\\Windows\\SysWOW64\\BthTelemetry.BthCollectFingerprintInfo\"")
#pragma comment(linker, "/export:BthProcessEventDataDword=\"C:\\Windows\\SysWOW64\\BthTelemetry.BthProcessEventDataDword\"")
#pragma comment(linker, "/export:BthProcessEventOccurrence=\"C:\\Windows\\SysWOW64\\BthTelemetry.BthProcessEventOccurrence\"")
#pragma comment(linker, "/export:BthProcessEventOccurrenceBthaddr=\"C:\\Windows\\SysWOW64\\BthTelemetry.BthProcessEventOccurrenceBthaddr\"")
#pragma comment(linker, "/export:BthProcessEventOccurrenceResult=\"C:\\Windows\\SysWOW64\\BthTelemetry.BthProcessEventOccurrenceResult\"")
#pragma comment(linker, "/export:BthProcessEventOccurrenceResultBthaddr=\"C:\\Windows\\SysWOW64\\BthTelemetry.BthProcessEventOccurrenceResultBthaddr\"")
#pragma comment(linker, "/export:BthProcessRpalEventOccurrence=\"C:\\Windows\\SysWOW64\\BthTelemetry.BthProcessRpalEventOccurrence\"")
