#pragma comment(linker, "/export:CLSID_CfgComp=\"C:\\Windows\\SysWOW64\\cfgbkend.CLSID_CfgComp\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\cfgbkend.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\cfgbkend.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\cfgbkend.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\cfgbkend.DllUnregisterServer\"")
#pragma comment(linker, "/export:IID_ICfgComp=\"C:\\Windows\\SysWOW64\\cfgbkend.IID_ICfgComp\"")
#pragma comment(linker, "/export:IID_ISettingsComp=\"C:\\Windows\\SysWOW64\\cfgbkend.IID_ISettingsComp\"")
#pragma comment(linker, "/export:IID_ISettingsComp2=\"C:\\Windows\\SysWOW64\\cfgbkend.IID_ISettingsComp2\"")
