#pragma comment(linker, "/export:JsThunk_AllocateData=\"C:\\Windows\\SysWOW64\\Chakrathunk.dll\"")
#pragma comment(linker, "/export:JsThunk_Cleanup=\"C:\\Windows\\SysWOW64\\Chakrathunk.dll\"")
#pragma comment(linker, "/export:JsThunk_CleanupDefer=\"C:\\Windows\\SysWOW64\\Chakrathunk.dll\"")
#pragma comment(linker, "/export:JsThunk_CleanupFinish=\"C:\\Windows\\SysWOW64\\Chakrathunk.dll\"")
#pragma comment(linker, "/export:JsThunk_DataToCode=\"C:\\Windows\\SysWOW64\\Chakrathunk.dll\"")
#pragma comment(linker, "/export:JsThunk_GetSize=\"C:\\Windows\\SysWOW64\\Chakrathunk.dll\"")
#pragma comment(linker, "/export:JsThunk_InitData=\"C:\\Windows\\SysWOW64\\Chakrathunk.dll\"")
#pragma comment(linker, "/export:JsThunk_Is=\"C:\\Windows\\SysWOW64\\Chakrathunk.dll\"")
