#pragma comment(linker, "/export:CvCloseDataSource=\"C:\\Windows\\SysWOW64\\chartv.CvCloseDataSource\"")
#pragma comment(linker, "/export:CvCreateDataSource=\"C:\\Windows\\SysWOW64\\chartv.CvCreateDataSource\"")
#pragma comment(linker, "/export:CvGetData=\"C:\\Windows\\SysWOW64\\chartv.CvGetData\"")
#pragma comment(linker, "/export:CvGetDataSourceName=\"C:\\Windows\\SysWOW64\\chartv.CvGetDataSourceName\"")
#pragma comment(linker, "/export:CvInitialize=\"C:\\Windows\\SysWOW64\\chartv.CvInitialize\"")
#pragma comment(linker, "/export:CvSetData=\"C:\\Windows\\SysWOW64\\chartv.CvSetData\"")
#pragma comment(linker, "/export:CvSetDataSourceName=\"C:\\Windows\\SysWOW64\\chartv.CvSetDataSourceName\"")
#pragma comment(linker, "/export:CvUninitialize=\"C:\\Windows\\SysWOW64\\chartv.CvUninitialize\"")
