#pragma comment(linker, "/export:CvCloseDataSource=\"C:\\Windows\\SysWOW64\\chartv.dll\"")
#pragma comment(linker, "/export:CvCreateDataSource=\"C:\\Windows\\SysWOW64\\chartv.dll\"")
#pragma comment(linker, "/export:CvGetData=\"C:\\Windows\\SysWOW64\\chartv.dll\"")
#pragma comment(linker, "/export:CvGetDataSourceName=\"C:\\Windows\\SysWOW64\\chartv.dll\"")
#pragma comment(linker, "/export:CvInitialize=\"C:\\Windows\\SysWOW64\\chartv.dll\"")
#pragma comment(linker, "/export:CvSetData=\"C:\\Windows\\SysWOW64\\chartv.dll\"")
#pragma comment(linker, "/export:CvSetDataSourceName=\"C:\\Windows\\SysWOW64\\chartv.dll\"")
#pragma comment(linker, "/export:CvUninitialize=\"C:\\Windows\\SysWOW64\\chartv.dll\"")
