#pragma comment(linker, "/export:ClbAddData=\"C:\\Windows\\SysWOW64\\clb.dll\"")
#pragma comment(linker, "/export:ClbSetColumnWidths=\"C:\\Windows\\SysWOW64\\clb.dll\"")
#pragma comment(linker, "/export:ClbStyleW=\"C:\\Windows\\SysWOW64\\clb.dll\"")
#pragma comment(linker, "/export:ClbWndProc=\"C:\\Windows\\SysWOW64\\clb.dll\"")
#pragma comment(linker, "/export:CustomControlInfoW=\"C:\\Windows\\SysWOW64\\clb.dll\"")
