#print comment(linker, "/export:CMConfig=\"C:\\Windows\\SysWOW64\\cmcfg32.dll\"")
#print comment(linker, "/export:CMConfigEx=\"C:\\Windows\\SysWOW64\\cmcfg32.dll\"")
#print comment(linker, "/export:CmstpExtensionProc=\"C:\\Windows\\SysWOW64\\cmcfg32.dll\"")
#print comment(linker, "/export:CmstpExtensionProc2=\"C:\\Windows\\SysWOW64\\cmcfg32.dll\"")
#print comment(linker, "/export:_CMConfig@8=\"C:\\Windows\\SysWOW64\\cmcfg32.dll\"")
