#pragma comment(linker, "/export:AwaitContactPickerResults=\"C:\\Windows\\SysWOW64\\ContactActivation.AwaitContactPickerResults\"")
#pragma comment(linker, "/export:ContactToVCardString=\"C:\\Windows\\SysWOW64\\ContactActivation.ContactToVCardString\"")
#pragma comment(linker, "/export:DeserializeContactFromString=\"C:\\Windows\\SysWOW64\\ContactActivation.DeserializeContactFromString\"")
#pragma comment(linker, "/export:SerializeContactToString=\"C:\\Windows\\SysWOW64\\ContactActivation.SerializeContactToString\"")
#pragma comment(linker, "/export:SerializeContactToVCard=\"C:\\Windows\\SysWOW64\\ContactActivation.SerializeContactToVCard\"")
#pragma comment(linker, "/export:ShowContactPickerAsync=\"C:\\Windows\\SysWOW64\\ContactActivation.ShowContactPickerAsync\"")
#pragma comment(linker, "/export:VCardStringToContact=\"C:\\Windows\\SysWOW64\\ContactActivation.VCardStringToContact\"")
