#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\CPFilters.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\CPFilters.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\CPFilters.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\CPFilters.DllUnregisterServer\"")
#pragma comment(linker, "/export:UpdatePlayready=\"C:\\Windows\\SysWOW64\\CPFilters.UpdatePlayready\"")
