#pragma comment(linker, "/export:CryptUIWizBuildCTL=\"C:\\Windows\\SysWOW64\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:CryptUIWizDigitalSign=\"C:\\Windows\\SysWOW64\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:CryptUIWizExport=\"C:\\Windows\\SysWOW64\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:CryptUIWizFreeDigitalSignContext=\"C:\\Windows\\SysWOW64\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:CryptUIWizImport=\"C:\\Windows\\SysWOW64\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:CryptUIWizImportInternal=\"C:\\Windows\\SysWOW64\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:GetFunctionTable=\"C:\\Windows\\SysWOW64\\cryptuiwizard.dll\"")
