#pragma comment(linker, "/export:CryptsvcDllCtrl=\"C:\\Windows\\SysWOW64\\crypttpmeksvc.dll\"")
#pragma comment(linker, "/export:EKCliAuthorityKeyGetInfo=\"C:\\Windows\\SysWOW64\\crypttpmeksvc.dll\"")
#pragma comment(linker, "/export:EKCliTpmEndorsementKeyDecryptSCEPChallenge=\"C:\\Windows\\SysWOW64\\crypttpmeksvc.dll\"")
#pragma comment(linker, "/export:EKCliTpmEndorsementKeyGetInfo=\"C:\\Windows\\SysWOW64\\crypttpmeksvc.dll\"")
#pragma comment(linker, "/export:EKCliTpmGetManufacturerInfo=\"C:\\Windows\\SysWOW64\\crypttpmeksvc.dll\"")
#pragma comment(linker, "/export:FreeCMCResponse=\"C:\\Windows\\SysWOW64\\crypttpmeksvc.dll\"")
#pragma comment(linker, "/export:IsCmcResponseForAttestation=\"C:\\Windows\\SysWOW64\\crypttpmeksvc.dll\"")
#pragma comment(linker, "/export:ParseCMCResponse=\"C:\\Windows\\SysWOW64\\crypttpmeksvc.dll\"")
