#pragma comment(linker, "/export:CscNetApiGetInterface=\"C:\\Windows\\SysWOW64\\cscapi.dll\"")
#pragma comment(linker, "/export:CscSearchApiGetInterface=\"C:\\Windows\\SysWOW64\\cscapi.dll\"")
#pragma comment(linker, "/export:OfflineFilesEnable=\"C:\\Windows\\SysWOW64\\cscapi.dll\"")
#pragma comment(linker, "/export:OfflineFilesGetShareCachingMode=\"C:\\Windows\\SysWOW64\\cscapi.dll\"")
#pragma comment(linker, "/export:OfflineFilesQueryStatus=\"C:\\Windows\\SysWOW64\\cscapi.dll\"")
#pragma comment(linker, "/export:OfflineFilesQueryStatusEx=\"C:\\Windows\\SysWOW64\\cscapi.dll\"")
#pragma comment(linker, "/export:OfflineFilesStart=\"C:\\Windows\\SysWOW64\\cscapi.dll\"")
