#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\cscobj.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\cscobj.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\cscobj.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\cscobj.dll\"")
#print comment(linker, "/export:ProcessGroupPolicy=\"C:\\Windows\\SysWOW64\\cscobj.dll\"")
#print comment(linker, "/export:ProcessPolicy=\"C:\\Windows\\SysWOW64\\cscobj.dll\"")
