#pragma comment(linker, "/export:D3D11RefGetLastCreation=\"C:\\Windows\\SysWOW64\\d3d10warp.dll\"")
#pragma comment(linker, "/export:D3DLayerGetInterface=\"C:\\Windows\\SysWOW64\\d3d10warp.dll\"")
#pragma comment(linker, "/export:OpenAdapter=\"C:\\Windows\\SysWOW64\\d3d10warp.dll\"")
#pragma comment(linker, "/export:OpenAdapter10_2=\"C:\\Windows\\SysWOW64\\d3d10warp.dll\"")
#pragma comment(linker, "/export:OpenAdapter12=\"C:\\Windows\\SysWOW64\\d3d10warp.dll\"")
#pragma comment(linker, "/export:OpenDisplayAdapter1=\"C:\\Windows\\SysWOW64\\d3d10warp.dll\"")
#pragma comment(linker, "/export:QueryDListForApplication1=\"C:\\Windows\\SysWOW64\\d3d10warp.dll\"")
#pragma comment(linker, "/export:VSD3DDebugConnectionBuffer=\"C:\\Windows\\SysWOW64\\d3d10warp.dll\"")
