#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\DavSyncProvider.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\DavSyncProvider.dll\"")
#pragma comment(linker, "/export:ForceCalDavCollectionsListRefreshDuringNextSync=\"C:\\Windows\\SysWOW64\\DavSyncProvider.dll\"")
#pragma comment(linker, "/export:HandleWebDavMeetingResponseForAppointment=\"C:\\Windows\\SysWOW64\\DavSyncProvider.dll\"")
#pragma comment(linker, "/export:HandleWebDavMeetingResponseForMeetingNotification=\"C:\\Windows\\SysWOW64\\DavSyncProvider.dll\"")
#pragma comment(linker, "/export:UpdateCalDavTrackingSchema=\"C:\\Windows\\SysWOW64\\DavSyncProvider.dll\"")
#pragma comment(linker, "/export:UpdateGMailContactSyncPartner=\"C:\\Windows\\SysWOW64\\DavSyncProvider.dll\"")
