#print comment(linker, "/export:DirectInput8Create=\"C:\\Windows\\SysWOW64\\dinput8.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\dinput8.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\dinput8.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\dinput8.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\dinput8.dll\"")
#print comment(linker, "/export:GetdfDIJoystick=\"C:\\Windows\\SysWOW64\\dinput8.dll\"")
