#pragma comment(linker, "/export:PushRouter_Close=\"C:\\Windows\\SysWOW64\\dmpushproxy.dll\"")
#pragma comment(linker, "/export:PushRouter_FreeGetMessageEventName=\"C:\\Windows\\SysWOW64\\dmpushproxy.dll\"")
#pragma comment(linker, "/export:PushRouter_FreeMessage=\"C:\\Windows\\SysWOW64\\dmpushproxy.dll\"")
#pragma comment(linker, "/export:PushRouter_FreeMessageEx=\"C:\\Windows\\SysWOW64\\dmpushproxy.dll\"")
#pragma comment(linker, "/export:PushRouter_GetMessage=\"C:\\Windows\\SysWOW64\\dmpushproxy.dll\"")
#pragma comment(linker, "/export:PushRouter_GetMessageEx=\"C:\\Windows\\SysWOW64\\dmpushproxy.dll\"")
#pragma comment(linker, "/export:PushRouter_Open=\"C:\\Windows\\SysWOW64\\dmpushproxy.dll\"")
#pragma comment(linker, "/export:PushRouter_SubmitPush=\"C:\\Windows\\SysWOW64\\dmpushproxy.dll\"")
