#pragma comment(linker, "/export:DeserializeLANPolicy=\"C:\\Windows\\SysWOW64\\dot3gpclnt.dll\"")
#pragma comment(linker, "/export:GenerateLANPolicy=\"C:\\Windows\\SysWOW64\\dot3gpclnt.dll\"")
#pragma comment(linker, "/export:LANGPADeInit=\"C:\\Windows\\SysWOW64\\dot3gpclnt.dll\"")
#pragma comment(linker, "/export:LANGPAInit=\"C:\\Windows\\SysWOW64\\dot3gpclnt.dll\"")
#pragma comment(linker, "/export:ProcessLANPolicyEx=\"C:\\Windows\\SysWOW64\\dot3gpclnt.dll\"")
