#pragma comment(linker, "/export:DrvSetupInstallDriver=\"C:\\Windows\\SysWOW64\\drvsetup.dll\"")
#pragma comment(linker, "/export:DrvSetupInstallWuDriver=\"C:\\Windows\\SysWOW64\\drvsetup.dll\"")
#pragma comment(linker, "/export:DrvSetupUninstallDriver=\"C:\\Windows\\SysWOW64\\drvsetup.dll\"")
#pragma comment(linker, "/export:DrvSetupUninstallWuDrivers=\"C:\\Windows\\SysWOW64\\drvsetup.dll\"")
#pragma comment(linker, "/export:pDrvSetupUninstallDriver=\"C:\\Windows\\SysWOW64\\drvsetup.dll\"")
