#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\eapputil.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\eapputil.dll\"")
#pragma comment(linker, "/export:EapConvertHostToWireFormat16=\"C:\\Windows\\SysWOW64\\eapputil.dll\"")
#pragma comment(linker, "/export:EapConvertHostToWireFormat24=\"C:\\Windows\\SysWOW64\\eapputil.dll\"")
#pragma comment(linker, "/export:EapConvertHostToWireFormat32=\"C:\\Windows\\SysWOW64\\eapputil.dll\"")
#pragma comment(linker, "/export:EapConvertWireToHostFormat16=\"C:\\Windows\\SysWOW64\\eapputil.dll\"")
#pragma comment(linker, "/export:EapConvertWireToHostFormat24=\"C:\\Windows\\SysWOW64\\eapputil.dll\"")
#pragma comment(linker, "/export:EapConvertWireToHostFormat32=\"C:\\Windows\\SysWOW64\\eapputil.dll\"")
