#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\eapputil.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\eapputil.DllGetActivationFactory\"")
#pragma comment(linker, "/export:EapConvertHostToWireFormat16=\"C:\\Windows\\SysWOW64\\eapputil.EapConvertHostToWireFormat16\"")
#pragma comment(linker, "/export:EapConvertHostToWireFormat24=\"C:\\Windows\\SysWOW64\\eapputil.EapConvertHostToWireFormat24\"")
#pragma comment(linker, "/export:EapConvertHostToWireFormat32=\"C:\\Windows\\SysWOW64\\eapputil.EapConvertHostToWireFormat32\"")
#pragma comment(linker, "/export:EapConvertWireToHostFormat16=\"C:\\Windows\\SysWOW64\\eapputil.EapConvertWireToHostFormat16\"")
#pragma comment(linker, "/export:EapConvertWireToHostFormat24=\"C:\\Windows\\SysWOW64\\eapputil.EapConvertWireToHostFormat24\"")
#pragma comment(linker, "/export:EapConvertWireToHostFormat32=\"C:\\Windows\\SysWOW64\\eapputil.EapConvertWireToHostFormat32\"")
