#pragma comment(linker, "/export:MappingDoAction=\"C:\\Windows\\SysWOW64\\ELSCore.dll\"")
#pragma comment(linker, "/export:MappingFreePropertyBag=\"C:\\Windows\\SysWOW64\\ELSCore.dll\"")
#pragma comment(linker, "/export:MappingFreeServices=\"C:\\Windows\\SysWOW64\\ELSCore.dll\"")
#pragma comment(linker, "/export:MappingGetServices=\"C:\\Windows\\SysWOW64\\ELSCore.dll\"")
#pragma comment(linker, "/export:MappingRecognizeText=\"C:\\Windows\\SysWOW64\\ELSCore.dll\"")
