#pragma comment(linker, "/export:MappingDoAction=\"C:\\Windows\\SysWOW64\\ELSCore.MappingDoAction\"")
#pragma comment(linker, "/export:MappingFreePropertyBag=\"C:\\Windows\\SysWOW64\\ELSCore.MappingFreePropertyBag\"")
#pragma comment(linker, "/export:MappingFreeServices=\"C:\\Windows\\SysWOW64\\ELSCore.MappingFreeServices\"")
#pragma comment(linker, "/export:MappingGetServices=\"C:\\Windows\\SysWOW64\\ELSCore.MappingGetServices\"")
#pragma comment(linker, "/export:MappingRecognizeText=\"C:\\Windows\\SysWOW64\\ELSCore.MappingRecognizeText\"")
