#pragma comment(linker, "/export:DoAction=\"C:\\Windows\\SysWOW64\\elshyph.dll\"")
#pragma comment(linker, "/export:FreePropertyBag=\"C:\\Windows\\SysWOW64\\elshyph.dll\"")
#pragma comment(linker, "/export:FreeService=\"C:\\Windows\\SysWOW64\\elshyph.dll\"")
#pragma comment(linker, "/export:InitService=\"C:\\Windows\\SysWOW64\\elshyph.dll\"")
#pragma comment(linker, "/export:RecognizeText=\"C:\\Windows\\SysWOW64\\elshyph.dll\"")
