#pragma comment(linker, "/export:ActivatePackage=\"C:\\Windows\\SysWOW64\\embeddedmodesvcapi.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\embeddedmodesvcapi.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\embeddedmodesvcapi.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\embeddedmodesvcapi.dll\"")
#pragma comment(linker, "/export:IsEmbeddedModeAllowed=\"C:\\Windows\\SysWOW64\\embeddedmodesvcapi.dll\"")
