#pragma comment(linker, "/export:CreateForegroundTaskManager=\"C:\\Windows\\SysWOW64\\ExecModelClient.CreateForegroundTaskManager\"")
#pragma comment(linker, "/export:CreateModernVoipPolicy=\"C:\\Windows\\SysWOW64\\ExecModelClient.CreateModernVoipPolicy\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\ExecModelClient.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\ExecModelClient.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\ExecModelClient.DllGetClassObject\"")
#pragma comment(linker, "/export:TestHook_CancelShutdown=\"C:\\Windows\\SysWOW64\\ExecModelClient.TestHook_CancelShutdown\"")
