#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\FirewallControlPanel.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\FirewallControlPanel.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\FirewallControlPanel.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\FirewallControlPanel.dll\"")
#pragma comment(linker, "/export:ShowNotificationDialogW=\"C:\\Windows\\SysWOW64\\FirewallControlPanel.dll\"")
#pragma comment(linker, "/export:ShowWarningDialogW=\"C:\\Windows\\SysWOW64\\FirewallControlPanel.dll\"")
