#pragma comment(linker, "/export:GetExpandedResourceExclusiveCpuCount=\"C:\\Windows\\SysWOW64\\gamemode.dll\"")
#pragma comment(linker, "/export:HasExpandedResources=\"C:\\Windows\\SysWOW64\\gamemode.dll\"")
#pragma comment(linker, "/export:MsixvcAddGameToGCS=\"C:\\Windows\\SysWOW64\\gamemode.dll\"")
#pragma comment(linker, "/export:MsixvcAddPackageAsync=\"C:\\Windows\\SysWOW64\\gamemode.dll\"")
#pragma comment(linker, "/export:MsixvcRemediateMutablePackagesForVolumeAsync=\"C:\\Windows\\SysWOW64\\gamemode.dll\"")
#pragma comment(linker, "/export:MsixvcUpdatePolicyString=\"C:\\Windows\\SysWOW64\\gamemode.dll\"")
#pragma comment(linker, "/export:MsixvcUpdatePolicyUInt64=\"C:\\Windows\\SysWOW64\\gamemode.dll\"")
#pragma comment(linker, "/export:ReleaseExclusiveCpuSets=\"C:\\Windows\\SysWOW64\\gamemode.dll\"")
