#print comment(linker, "/export:?GPHHookWindowPointerDown@CGamePanelExternalHook@@SGIXZ=\"C:\\Windows\\SysWOW64\\GamePanelExternalHook.dll\"")
#print comment(linker, "/export:?GetInstance@CGamePanelExternalHook@@SGAAV1@XZ=\"C:\\Windows\\SysWOW64\\GamePanelExternalHook.dll\"")
#print comment(linker, "/export:?Hook@CGamePanelExternalHook@@QAEXPAUHWND__@@@Z=\"C:\\Windows\\SysWOW64\\GamePanelExternalHook.dll\"")
#print comment(linker, "/export:?SetIntercept@CGamePanelExternalHook@@QAEX_NPAUHWND__@@@Z=\"C:\\Windows\\SysWOW64\\GamePanelExternalHook.dll\"")
#print comment(linker, "/export:?Unhook@CGamePanelExternalHook@@QAEXXZ=\"C:\\Windows\\SysWOW64\\GamePanelExternalHook.dll\"")
