#pragma comment(linker, "/export:?GPHHookWindowPointerDown@CGamePanelExternalHook@@SGIXZ=\"C:\\Windows\\SysWOW64\\GamePanelExternalHook.?GPHHookWindowPointerDown@CGamePanelExternalHook@@SGIXZ\"")
#pragma comment(linker, "/export:?GetInstance@CGamePanelExternalHook@@SGAAV1@XZ=\"C:\\Windows\\SysWOW64\\GamePanelExternalHook.?GetInstance@CGamePanelExternalHook@@SGAAV1@XZ\"")
#pragma comment(linker, "/export:?Hook@CGamePanelExternalHook@@QAEXPAUHWND__@@@Z=\"C:\\Windows\\SysWOW64\\GamePanelExternalHook.?Hook@CGamePanelExternalHook@@QAEXPAUHWND__@@@Z\"")
#pragma comment(linker, "/export:?SetIntercept@CGamePanelExternalHook@@QAEX_NPAUHWND__@@@Z=\"C:\\Windows\\SysWOW64\\GamePanelExternalHook.?SetIntercept@CGamePanelExternalHook@@QAEX_NPAUHWND__@@@Z\"")
#pragma comment(linker, "/export:?Unhook@CGamePanelExternalHook@@QAEXXZ=\"C:\\Windows\\SysWOW64\\GamePanelExternalHook.?Unhook@CGamePanelExternalHook@@QAEXXZ\"")
