#pragma comment(linker, "/export:GMSAAdd=\"C:\\Windows\\SysWOW64\\gmsaclient.dll\"")
#pragma comment(linker, "/export:GMSACheckIfExistsInAD=\"C:\\Windows\\SysWOW64\\gmsaclient.dll\"")
#pragma comment(linker, "/export:GMSACleanup=\"C:\\Windows\\SysWOW64\\gmsaclient.dll\"")
#pragma comment(linker, "/export:GMSADelete=\"C:\\Windows\\SysWOW64\\gmsaclient.dll\"")
#pragma comment(linker, "/export:GMSAGetPassword=\"C:\\Windows\\SysWOW64\\gmsaclient.dll\"")
#pragma comment(linker, "/export:GMSAInit=\"C:\\Windows\\SysWOW64\\gmsaclient.dll\"")
#pragma comment(linker, "/export:GMSARefreshPasswords=\"C:\\Windows\\SysWOW64\\gmsaclient.dll\"")
