#print comment(linker, "/export:CreateHrtfApo=\"C:\\Windows\\SysWOW64\\HrtfApo.dll\"")
#print comment(linker, "/export:CreateHrtfApoWithDatasetType=\"C:\\Windows\\SysWOW64\\HrtfApo.dll\"")
#print comment(linker, "/export:CreateHrtfEngineFactory=\"C:\\Windows\\SysWOW64\\HrtfApo.dll\"")
#print comment(linker, "/export:GetHrtfEngineMinFrameCount=\"C:\\Windows\\SysWOW64\\HrtfApo.dll\"")
#print comment(linker, "/export:IsHrtfApoAvailable=\"C:\\Windows\\SysWOW64\\HrtfApo.dll\"")
