#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\htui.DllMain\"")
#pragma comment(linker, "/export:HTUI_ColorAdjustment=\"C:\\Windows\\SysWOW64\\htui.HTUI_ColorAdjustment\"")
#pragma comment(linker, "/export:HTUI_ColorAdjustmentA=\"C:\\Windows\\SysWOW64\\htui.HTUI_ColorAdjustmentA\"")
#pragma comment(linker, "/export:HTUI_ColorAdjustmentW=\"C:\\Windows\\SysWOW64\\htui.HTUI_ColorAdjustmentW\"")
#pragma comment(linker, "/export:HTUI_DeviceColorAdjustment=\"C:\\Windows\\SysWOW64\\htui.HTUI_DeviceColorAdjustment\"")
#pragma comment(linker, "/export:HTUI_DeviceColorAdjustmentA=\"C:\\Windows\\SysWOW64\\htui.HTUI_DeviceColorAdjustmentA\"")
#pragma comment(linker, "/export:HTUI_DeviceColorAdjustmentW=\"C:\\Windows\\SysWOW64\\htui.HTUI_DeviceColorAdjustmentW\"")
