#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\IasMigPlugin.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\IasMigPlugin.dll\"")
#print comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\IasMigPlugin.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\IasMigPlugin.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\IasMigPlugin.dll\"")
#print comment(linker, "/export:IasUpgradeComplianceCheck=\"C:\\Windows\\SysWOW64\\IasMigPlugin.dll\"")
