#pragma comment(linker, "/export:CheckSnapshotPresence=\"C:\\Windows\\SysWOW64\\ifsutilx.CheckSnapshotPresence\"")
#pragma comment(linker, "/export:CreateVolumeSnapshot=\"C:\\Windows\\SysWOW64\\ifsutilx.CreateVolumeSnapshot\"")
#pragma comment(linker, "/export:GetSnapshotErrorMessage=\"C:\\Windows\\SysWOW64\\ifsutilx.GetSnapshotErrorMessage\"")
#pragma comment(linker, "/export:InitializeCOM=\"C:\\Windows\\SysWOW64\\ifsutilx.InitializeCOM\"")
#pragma comment(linker, "/export:ReleaseVolumeSnapshot=\"C:\\Windows\\SysWOW64\\ifsutilx.ReleaseVolumeSnapshot\"")
#pragma comment(linker, "/export:UninitializeCOM=\"C:\\Windows\\SysWOW64\\ifsutilx.UninitializeCOM\"")
