#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\InstallServiceTasks.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\InstallServiceTasks.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\InstallServiceTasks.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\InstallServiceTasks.DllUnregisterServer\"")
#pragma comment(linker, "/export:ForceAppInUseRestart=\"C:\\Windows\\SysWOW64\\InstallServiceTasks.ForceAppInUseRestart\"")
