#pragma comment(linker, "/export:FmtIdToPropStgName=\"C:\\Windows\\SysWOW64\\iprop.dll\"")
#pragma comment(linker, "/export:FreePropVariantArray=\"C:\\Windows\\SysWOW64\\iprop.dll\"")
#pragma comment(linker, "/export:PropStgNameToFmtId=\"C:\\Windows\\SysWOW64\\iprop.dll\"")
#pragma comment(linker, "/export:PropVariantClear=\"C:\\Windows\\SysWOW64\\iprop.dll\"")
#pragma comment(linker, "/export:PropVariantCopy=\"C:\\Windows\\SysWOW64\\iprop.dll\"")
#pragma comment(linker, "/export:StgCreatePropSetStg=\"C:\\Windows\\SysWOW64\\iprop.dll\"")
#pragma comment(linker, "/export:StgCreatePropStg=\"C:\\Windows\\SysWOW64\\iprop.dll\"")
#pragma comment(linker, "/export:StgOpenPropStg=\"C:\\Windows\\SysWOW64\\iprop.dll\"")
