#pragma comment(linker, "/export:CleanUpIpPriority=\"C:\\Windows\\SysWOW64\\iprtprio.dll\"")
#pragma comment(linker, "/export:ComputeRouteMetric=\"C:\\Windows\\SysWOW64\\iprtprio.dll\"")
#pragma comment(linker, "/export:ComputeRouteMetricEx=\"C:\\Windows\\SysWOW64\\iprtprio.dll\"")
#pragma comment(linker, "/export:GetPriorityInfo=\"C:\\Windows\\SysWOW64\\iprtprio.dll\"")
#pragma comment(linker, "/export:SetPriorityInfo=\"C:\\Windows\\SysWOW64\\iprtprio.dll\"")
