#pragma comment(linker, "/export:AllocInstanceData=\"C:\\Windows\\SysWOW64\\ir41_qcx.AllocInstanceData\"")
#pragma comment(linker, "/export:Compress=\"C:\\Windows\\SysWOW64\\ir41_qcx.Compress\"")
#pragma comment(linker, "/export:CompressBegin=\"C:\\Windows\\SysWOW64\\ir41_qcx.CompressBegin\"")
#pragma comment(linker, "/export:CompressEnd=\"C:\\Windows\\SysWOW64\\ir41_qcx.CompressEnd\"")
#pragma comment(linker, "/export:CompressFramesInfo=\"C:\\Windows\\SysWOW64\\ir41_qcx.CompressFramesInfo\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\ir41_qcx.DllMain\"")
#pragma comment(linker, "/export:FreeInstanceData=\"C:\\Windows\\SysWOW64\\ir41_qcx.FreeInstanceData\"")
#pragma comment(linker, "/export:SetScalability=\"C:\\Windows\\SysWOW64\\ir41_qcx.SetScalability\"")
