#pragma comment(linker, "/export:AllocInstanceData=\"C:\\Windows\\SysWOW64\\ir41_qc.AllocInstanceData\"")
#pragma comment(linker, "/export:Compress=\"C:\\Windows\\SysWOW64\\ir41_qc.Compress\"")
#pragma comment(linker, "/export:CompressBegin=\"C:\\Windows\\SysWOW64\\ir41_qc.CompressBegin\"")
#pragma comment(linker, "/export:CompressEnd=\"C:\\Windows\\SysWOW64\\ir41_qc.CompressEnd\"")
#pragma comment(linker, "/export:CompressFramesInfo=\"C:\\Windows\\SysWOW64\\ir41_qc.CompressFramesInfo\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\ir41_qc.DllMain\"")
#pragma comment(linker, "/export:FreeInstanceData=\"C:\\Windows\\SysWOW64\\ir41_qc.FreeInstanceData\"")
#pragma comment(linker, "/export:SetScalability=\"C:\\Windows\\SysWOW64\\ir41_qc.SetScalability\"")
