#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\itss.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\itss.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\itss.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\itss.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\itss.DllUnregisterServer\"")
