#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\jscript9diag.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\jscript9diag.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\jscript9diag.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\jscript9diag.dll\"")
#pragma comment(linker, "/export:FreeDumpStreams=\"C:\\Windows\\SysWOW64\\jscript9diag.dll\"")
#pragma comment(linker, "/export:GetDumpStreams=\"C:\\Windows\\SysWOW64\\jscript9diag.dll\"")
