#pragma comment(linker, "/export:InternetDeInitializeAutoProxyDll=\"C:\\Windows\\SysWOW64\\jsproxy.dll\"")
#pragma comment(linker, "/export:InternetDeInitializeAutoProxyDllEx=\"C:\\Windows\\SysWOW64\\jsproxy.dll\"")
#pragma comment(linker, "/export:InternetGetProxyInfo=\"C:\\Windows\\SysWOW64\\jsproxy.dll\"")
#pragma comment(linker, "/export:InternetGetProxyInfoEx=\"C:\\Windows\\SysWOW64\\jsproxy.dll\"")
#pragma comment(linker, "/export:InternetInitializeAutoProxyDll=\"C:\\Windows\\SysWOW64\\jsproxy.dll\"")
#pragma comment(linker, "/export:InternetInitializeAutoProxyDllEx=\"C:\\Windows\\SysWOW64\\jsproxy.dll\"")
