#pragma comment(linker, "/export:KbdLayerDescriptor=\"C:\\Windows\\SysWOW64\\KBDJPN.KbdLayerDescriptor\"")
#pragma comment(linker, "/export:KbdLayerMultiDescriptor=\"C:\\Windows\\SysWOW64\\KBDJPN.KbdLayerMultiDescriptor\"")
#pragma comment(linker, "/export:KbdLayerRealDllFile=\"C:\\Windows\\SysWOW64\\KBDJPN.KbdLayerRealDllFile\"")
#pragma comment(linker, "/export:KbdLayerRealDllFileNT4=\"C:\\Windows\\SysWOW64\\KBDJPN.KbdLayerRealDllFileNT4\"")
#pragma comment(linker, "/export:KbdNlsLayerDescriptor=\"C:\\Windows\\SysWOW64\\KBDJPN.KbdNlsLayerDescriptor\"")
