#pragma comment(linker, "/export:KbdLayerDescriptor=\"C:\\Windows\\SysWOW64\\KBDKOR.DLL\"")
#pragma comment(linker, "/export:KbdLayerMultiDescriptor=\"C:\\Windows\\SysWOW64\\KBDKOR.DLL\"")
#pragma comment(linker, "/export:KbdLayerRealDllFile=\"C:\\Windows\\SysWOW64\\KBDKOR.DLL\"")
#pragma comment(linker, "/export:KbdLayerRealDllFileNT4=\"C:\\Windows\\SysWOW64\\KBDKOR.DLL\"")
#pragma comment(linker, "/export:KbdNlsLayerDescriptor=\"C:\\Windows\\SysWOW64\\KBDKOR.DLL\"")
