#pragma comment(linker, "/export:KsCreateAllocator=\"C:\\Windows\\SysWOW64\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreateAllocator2=\"C:\\Windows\\SysWOW64\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreateClock=\"C:\\Windows\\SysWOW64\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreateClock2=\"C:\\Windows\\SysWOW64\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreatePin=\"C:\\Windows\\SysWOW64\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreatePin2=\"C:\\Windows\\SysWOW64\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreateTopologyNode=\"C:\\Windows\\SysWOW64\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreateTopologyNode2=\"C:\\Windows\\SysWOW64\\ksuser.dll\"")
