#pragma comment(linker, "/export:?classCCachedDataPathProperty@CCachedDataPathProperty@@2UCRuntimeClass@@B=\"C:\\Windows\\SysWOW64\\mfc42.?classCCachedDataPathProperty@CCachedDataPathProperty@@2UCRuntimeClass@@B\"")
#pragma comment(linker, "/export:?classCDataPathProperty@CDataPathProperty@@2UCRuntimeClass@@B=\"C:\\Windows\\SysWOW64\\mfc42.?classCDataPathProperty@CDataPathProperty@@2UCRuntimeClass@@B\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\mfc42.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\mfc42.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\mfc42.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\mfc42.DllUnregisterServer\"")
