#pragma comment(linker, "/export:?classCCachedDataPathProperty@CCachedDataPathProperty@@2UCRuntimeClass@@B=\"C:\\Windows\\SysWOW64\\mfc42u.dll\"")
#pragma comment(linker, "/export:?classCDataPathProperty@CDataPathProperty@@2UCRuntimeClass@@B=\"C:\\Windows\\SysWOW64\\mfc42u.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\mfc42u.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\mfc42u.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\mfc42u.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\mfc42u.dll\"")
