#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\MFPlay.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\MFPlay.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\MFPlay.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\MFPlay.DllUnregisterServer\"")
#pragma comment(linker, "/export:MFPCreateMediaPlayer=\"C:\\Windows\\SysWOW64\\MFPlay.MFPCreateMediaPlayer\"")
#pragma comment(linker, "/export:MFPCreateMediaPlayerEx=\"C:\\Windows\\SysWOW64\\MFPlay.MFPCreateMediaPlayerEx\"")
