#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\mfreadwrite.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\mfreadwrite.dll\"")
#pragma comment(linker, "/export:MFCreateSinkWriterFromMediaSink=\"C:\\Windows\\SysWOW64\\mfreadwrite.dll\"")
#pragma comment(linker, "/export:MFCreateSinkWriterFromURL=\"C:\\Windows\\SysWOW64\\mfreadwrite.dll\"")
#pragma comment(linker, "/export:MFCreateSourceReaderFromByteStream=\"C:\\Windows\\SysWOW64\\mfreadwrite.dll\"")
#pragma comment(linker, "/export:MFCreateSourceReaderFromMediaSource=\"C:\\Windows\\SysWOW64\\mfreadwrite.dll\"")
#pragma comment(linker, "/export:MFCreateSourceReaderFromURL=\"C:\\Windows\\SysWOW64\\mfreadwrite.dll\"")
