#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\MiracastReceiverExt.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\MiracastReceiverExt.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\MiracastReceiverExt.DllMain\"")
#pragma comment(linker, "/export:GetPlatformSpecificLockScreenAppLauncher=\"C:\\Windows\\SysWOW64\\MiracastReceiverExt.GetPlatformSpecificLockScreenAppLauncher\"")
#pragma comment(linker, "/export:IsLockScreenActive=\"C:\\Windows\\SysWOW64\\MiracastReceiverExt.IsLockScreenActive\"")
