#print comment(linker, "/export:CreateExecutivePlatform=\"C:\\Windows\\SysWOW64\\mmcndmgr.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\mmcndmgr.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\mmcndmgr.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\mmcndmgr.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\mmcndmgr.dll\"")
