#pragma comment(linker, "/export:ActivateAudioInterfaceAsync=\"C:\\Windows\\SysWOW64\\MMDevAPI.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\MMDevAPI.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\MMDevAPI.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\MMDevAPI.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\MMDevAPI.dll\"")
