#pragma comment(linker, "/export:CreateInstance=\"C:\\Windows\\SysWOW64\\MP4SDECD.CreateInstance\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\MP4SDECD.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\MP4SDECD.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\MP4SDECD.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\MP4SDECD.DllUnregisterServer\"")
