#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.dll\"")
#pragma comment(linker, "/export:DoMsCtfMonitor=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.dll\"")
#pragma comment(linker, "/export:InitLocalMsCtfMonitor=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.dll\"")
#pragma comment(linker, "/export:UninitLocalMsCtfMonitor=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.dll\"")
