#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\msdtcuiu.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\msdtcuiu.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\msdtcuiu.DllUnregisterServer\"")
#pragma comment(linker, "/export:DtcPerfClose=\"C:\\Windows\\SysWOW64\\msdtcuiu.DtcPerfClose\"")
#pragma comment(linker, "/export:DtcPerfCollect=\"C:\\Windows\\SysWOW64\\msdtcuiu.DtcPerfCollect\"")
#pragma comment(linker, "/export:DtcPerfOpen=\"C:\\Windows\\SysWOW64\\msdtcuiu.DtcPerfOpen\"")
#pragma comment(linker, "/export:PerfDllRegisterServer=\"C:\\Windows\\SysWOW64\\msdtcuiu.PerfDllRegisterServer\"")
