#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\msdtcuiu.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\msdtcuiu.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\msdtcuiu.dll\"")
#pragma comment(linker, "/export:DtcPerfClose=\"C:\\Windows\\SysWOW64\\msdtcuiu.dll\"")
#pragma comment(linker, "/export:DtcPerfCollect=\"C:\\Windows\\SysWOW64\\msdtcuiu.dll\"")
#pragma comment(linker, "/export:DtcPerfOpen=\"C:\\Windows\\SysWOW64\\msdtcuiu.dll\"")
#pragma comment(linker, "/export:PerfDllRegisterServer=\"C:\\Windows\\SysWOW64\\msdtcuiu.dll\"")
