#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\msimtf.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\msimtf.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\msimtf.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\msimtf.DllUnregisterServer\"")
#pragma comment(linker, "/export:MsimtfIsGuidMapEnable=\"C:\\Windows\\SysWOW64\\msimtf.MsimtfIsGuidMapEnable\"")
#pragma comment(linker, "/export:MsimtfIsWindowFiltered=\"C:\\Windows\\SysWOW64\\msimtf.MsimtfIsWindowFiltered\"")
