#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\msisip.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\msisip.dll\"")
#pragma comment(linker, "/export:MsiSIPCreateIndirectData=\"C:\\Windows\\SysWOW64\\msisip.dll\"")
#pragma comment(linker, "/export:MsiSIPGetSignedDataMsg=\"C:\\Windows\\SysWOW64\\msisip.dll\"")
#pragma comment(linker, "/export:MsiSIPIsMyTypeOfFile=\"C:\\Windows\\SysWOW64\\msisip.dll\"")
#pragma comment(linker, "/export:MsiSIPPutSignedDataMsg=\"C:\\Windows\\SysWOW64\\msisip.dll\"")
#pragma comment(linker, "/export:MsiSIPRemoveSignedDataMsg=\"C:\\Windows\\SysWOW64\\msisip.dll\"")
#pragma comment(linker, "/export:MsiSIPVerifyIndirectData=\"C:\\Windows\\SysWOW64\\msisip.dll\"")
