#pragma comment(linker, "/export:Close=\"C:\\Windows\\SysWOW64\\msscntrs.dll\"")
#pragma comment(linker, "/export:Collect=\"C:\\Windows\\SysWOW64\\msscntrs.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\msscntrs.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\msscntrs.dll\"")
#pragma comment(linker, "/export:Open=\"C:\\Windows\\SysWOW64\\msscntrs.dll\"")
