#pragma comment(linker, "/export:ClosePopupTipbar=\"C:\\Windows\\SysWOW64\\msutb.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\msutb.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\msutb.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\msutb.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\msutb.dll\"")
#pragma comment(linker, "/export:GetChildTipbar=\"C:\\Windows\\SysWOW64\\msutb.dll\"")
#pragma comment(linker, "/export:GetPopupTipbar=\"C:\\Windows\\SysWOW64\\msutb.dll\"")
#pragma comment(linker, "/export:SetRegisterLangBand=\"C:\\Windows\\SysWOW64\\msutb.dll\"")
