#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\ndproxystub.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\ndproxystub.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\ndproxystub.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\ndproxystub.dll\"")
#print comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\SysWOW64\\ndproxystub.dll\"")
