#pragma comment(linker, "/export:HelperTraceEvent=\"C:\\Windows\\SysWOW64\\netdiagfx.dll\"")
#pragma comment(linker, "/export:HelperTraceInitialize=\"C:\\Windows\\SysWOW64\\netdiagfx.dll\"")
#pragma comment(linker, "/export:HelperTraceUninitialize=\"C:\\Windows\\SysWOW64\\netdiagfx.dll\"")
#pragma comment(linker, "/export:WdiDiagnosticModuleMain=\"C:\\Windows\\SysWOW64\\netdiagfx.dll\"")
#pragma comment(linker, "/export:WdiGetDiagnosticModuleInterfaceVersion=\"C:\\Windows\\SysWOW64\\netdiagfx.dll\"")
#pragma comment(linker, "/export:WdiHandleInstance=\"C:\\Windows\\SysWOW64\\netdiagfx.dll\"")
