#pragma comment(linker, "/export:NetDriverInstallClose=\"C:\\Windows\\SysWOW64\\NetDriverInstall.dll\"")
#pragma comment(linker, "/export:NetDriverInstallCommit=\"C:\\Windows\\SysWOW64\\NetDriverInstall.dll\"")
#pragma comment(linker, "/export:NetDriverInstallInitialize=\"C:\\Windows\\SysWOW64\\NetDriverInstall.dll\"")
#pragma comment(linker, "/export:NetDriverInstallProcessAdditions=\"C:\\Windows\\SysWOW64\\NetDriverInstall.dll\"")
#pragma comment(linker, "/export:NetDriverInstallProcessRemovals=\"C:\\Windows\\SysWOW64\\NetDriverInstall.dll\"")
#pragma comment(linker, "/export:NetDriverInstallSync=\"C:\\Windows\\SysWOW64\\NetDriverInstall.dll\"")
