#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\NetSetupShim.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\NetSetupShim.dll\"")
#pragma comment(linker, "/export:NetSetupCreateBindingMap=\"C:\\Windows\\SysWOW64\\NetSetupShim.dll\"")
#pragma comment(linker, "/export:NetSetupExportDatabase=\"C:\\Windows\\SysWOW64\\NetSetupShim.dll\"")
#pragma comment(linker, "/export:NetSetupResetBindings=\"C:\\Windows\\SysWOW64\\NetSetupShim.dll\"")
#pragma comment(linker, "/export:NetSetupShimExecuteInfSection=\"C:\\Windows\\SysWOW64\\NetSetupShim.dll\"")
