#pragma comment(linker, "/export:NgcLocalAddCredential=\"C:\\Windows\\SysWOW64\\ngclocal.dll\"")
#pragma comment(linker, "/export:NgcLocalAddCredentialSilent=\"C:\\Windows\\SysWOW64\\ngclocal.dll\"")
#pragma comment(linker, "/export:NgcLocalChangeCredential=\"C:\\Windows\\SysWOW64\\ngclocal.dll\"")
#pragma comment(linker, "/export:NgcLocalFindCredential=\"C:\\Windows\\SysWOW64\\ngclocal.dll\"")
#pragma comment(linker, "/export:NgcLocalRemoveCredential=\"C:\\Windows\\SysWOW64\\ngclocal.dll\"")
