#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\NmaDirect.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\NmaDirect.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\NmaDirect.dll\"")
#pragma comment(linker, "/export:NmaDirect_OverrideUserLocation=\"C:\\Windows\\SysWOW64\\NmaDirect.dll\"")
#pragma comment(linker, "/export:NmaDirect_StartGuidanceWithSimulatedRoute=\"C:\\Windows\\SysWOW64\\NmaDirect.dll\"")
