#pragma comment(linker, "/export:IdnToAscii=\"C:\\Windows\\SysWOW64\\normaliz.dll\"")
#pragma comment(linker, "/export:IdnToNameprepUnicode=\"C:\\Windows\\SysWOW64\\normaliz.dll\"")
#pragma comment(linker, "/export:IdnToUnicode=\"C:\\Windows\\SysWOW64\\normaliz.dll\"")
#pragma comment(linker, "/export:IsNormalizedString=\"C:\\Windows\\SysWOW64\\normaliz.dll\"")
#pragma comment(linker, "/export:NormalizeString=\"C:\\Windows\\SysWOW64\\normaliz.dll\"")
