#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\npmproxy.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\npmproxy.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\npmproxy.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\npmproxy.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\SysWOW64\\npmproxy.GetProxyDllInfo\"")
