#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\NPSM.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\NPSM.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\NPSM.dll\"")
#pragma comment(linker, "/export:RegisterNowPlayingSessionManagerFactory=\"C:\\Windows\\SysWOW64\\NPSM.dll\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\SysWOW64\\NPSM.dll\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\SysWOW64\\NPSM.dll\"")
#pragma comment(linker, "/export:UnregisterNowPlayingSessionManagerFactory=\"C:\\Windows\\SysWOW64\\NPSM.dll\"")
