#pragma comment(linker, "/export:IdpConfigAddPolicy=\"C:\\Windows\\SysWOW64\\nshwfp.IdpConfigAddPolicy\"")
#pragma comment(linker, "/export:IdpConfigAllocateAndGetPolicy=\"C:\\Windows\\SysWOW64\\nshwfp.IdpConfigAllocateAndGetPolicy\"")
#pragma comment(linker, "/export:IdpConfigFreePolicy=\"C:\\Windows\\SysWOW64\\nshwfp.IdpConfigFreePolicy\"")
#pragma comment(linker, "/export:IdpConfigInitDefaultPolicy=\"C:\\Windows\\SysWOW64\\nshwfp.IdpConfigInitDefaultPolicy\"")
#pragma comment(linker, "/export:IdpConfigRemovePolicy=\"C:\\Windows\\SysWOW64\\nshwfp.IdpConfigRemovePolicy\"")
#pragma comment(linker, "/export:InitHelperDll=\"C:\\Windows\\SysWOW64\\nshwfp.InitHelperDll\"")
#pragma comment(linker, "/export:WfpCaptureExportedW=\"C:\\Windows\\SysWOW64\\nshwfp.WfpCaptureExportedW\"")
#pragma comment(linker, "/export:WfpCaptureStop=\"C:\\Windows\\SysWOW64\\nshwfp.WfpCaptureStop\"")
