#pragma comment(linker, "/export:IdpConfigAddPolicy=\"C:\\Windows\\SysWOW64\\nshwfp.dll\"")
#pragma comment(linker, "/export:IdpConfigAllocateAndGetPolicy=\"C:\\Windows\\SysWOW64\\nshwfp.dll\"")
#pragma comment(linker, "/export:IdpConfigFreePolicy=\"C:\\Windows\\SysWOW64\\nshwfp.dll\"")
#pragma comment(linker, "/export:IdpConfigInitDefaultPolicy=\"C:\\Windows\\SysWOW64\\nshwfp.dll\"")
#pragma comment(linker, "/export:IdpConfigRemovePolicy=\"C:\\Windows\\SysWOW64\\nshwfp.dll\"")
#pragma comment(linker, "/export:InitHelperDll=\"C:\\Windows\\SysWOW64\\nshwfp.dll\"")
#pragma comment(linker, "/export:WfpCaptureExportedW=\"C:\\Windows\\SysWOW64\\nshwfp.dll\"")
#pragma comment(linker, "/export:WfpCaptureStop=\"C:\\Windows\\SysWOW64\\nshwfp.dll\"")
