#pragma comment(linker, "/export:FreeInterfaceContextTable=\"C:\\Windows\\SysWOW64\\OnDemandConnRouteHelper.FreeInterfaceContextTable\"")
#pragma comment(linker, "/export:GetInterfaceContextTableForHostName=\"C:\\Windows\\SysWOW64\\OnDemandConnRouteHelper.GetInterfaceContextTableForHostName\"")
#pragma comment(linker, "/export:OnDemandAddRouteRequest=\"C:\\Windows\\SysWOW64\\OnDemandConnRouteHelper.OnDemandAddRouteRequest\"")
#pragma comment(linker, "/export:OnDemandGetRoutingHint=\"C:\\Windows\\SysWOW64\\OnDemandConnRouteHelper.OnDemandGetRoutingHint\"")
#pragma comment(linker, "/export:OnDemandRegisterNotification=\"C:\\Windows\\SysWOW64\\OnDemandConnRouteHelper.OnDemandRegisterNotification\"")
#pragma comment(linker, "/export:OnDemandRemoveMatchingRoute=\"C:\\Windows\\SysWOW64\\OnDemandConnRouteHelper.OnDemandRemoveMatchingRoute\"")
#pragma comment(linker, "/export:OnDemandRemoveRouteRequest=\"C:\\Windows\\SysWOW64\\OnDemandConnRouteHelper.OnDemandRemoveRouteRequest\"")
#pragma comment(linker, "/export:OnDemandUnRegisterNotification=\"C:\\Windows\\SysWOW64\\OnDemandConnRouteHelper.OnDemandUnRegisterNotification\"")
