#pragma comment(linker, "/export:ExecuteUninstall=\"C:\\Windows\\SysWOW64\\osuninst.dll\"")
#pragma comment(linker, "/export:GetUninstallImageSize=\"C:\\Windows\\SysWOW64\\osuninst.dll\"")
#pragma comment(linker, "/export:IsUninstallImageValid=\"C:\\Windows\\SysWOW64\\osuninst.dll\"")
#pragma comment(linker, "/export:ProvideUiAlerts=\"C:\\Windows\\SysWOW64\\osuninst.dll\"")
#pragma comment(linker, "/export:RemoveUninstallImage=\"C:\\Windows\\SysWOW64\\osuninst.dll\"")
