#pragma comment(linker, "/export:PcaGetFileInfoFromPath=\"C:\\Windows\\SysWOW64\\pcacli.dll\"")
#pragma comment(linker, "/export:PcaIsPcaDisabled=\"C:\\Windows\\SysWOW64\\pcacli.dll\"")
#pragma comment(linker, "/export:PcaLinkChildProcessToParent=\"C:\\Windows\\SysWOW64\\pcacli.dll\"")
#pragma comment(linker, "/export:PcaMonitorProcess=\"C:\\Windows\\SysWOW64\\pcacli.dll\"")
#pragma comment(linker, "/export:PcaMonitorProcess2=\"C:\\Windows\\SysWOW64\\pcacli.dll\"")
#pragma comment(linker, "/export:PcaNotifyMsiInstall=\"C:\\Windows\\SysWOW64\\pcacli.dll\"")
#pragma comment(linker, "/export:PcaNotifyStatusIcon=\"C:\\Windows\\SysWOW64\\pcacli.dll\"")
#pragma comment(linker, "/export:PcaSendToService=\"C:\\Windows\\SysWOW64\\pcacli.dll\"")
