#pragma comment(linker, "/export:CloseLagPerfData=\"C:\\Windows\\SysWOW64\\perfts.CloseLagPerfData\"")
#pragma comment(linker, "/export:CloseTSObject=\"C:\\Windows\\SysWOW64\\perfts.CloseTSObject\"")
#pragma comment(linker, "/export:CollectLagPerfData=\"C:\\Windows\\SysWOW64\\perfts.CollectLagPerfData\"")
#pragma comment(linker, "/export:CollectTSObjectData=\"C:\\Windows\\SysWOW64\\perfts.CollectTSObjectData\"")
#pragma comment(linker, "/export:OpenLagPerfData=\"C:\\Windows\\SysWOW64\\perfts.OpenLagPerfData\"")
#pragma comment(linker, "/export:OpenTSObject=\"C:\\Windows\\SysWOW64\\perfts.OpenTSObject\"")
