#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\photowiz.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\photowiz.DllGetClassObject\"")
#pragma comment(linker, "/export:DllInstall=\"C:\\Windows\\SysWOW64\\photowiz.DllInstall\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\photowiz.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\photowiz.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\photowiz.DllUnregisterServer\"")
#pragma comment(linker, "/export:UsePPWForPrintTo=\"C:\\Windows\\SysWOW64\\photowiz.UsePPWForPrintTo\"")
