#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\PortableDeviceClassExtension.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\PortableDeviceClassExtension.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\PortableDeviceClassExtension.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\PortableDeviceClassExtension.dll\"")
#print comment(linker, "/export:Microsoft_WDF_UMDF_Version=\"C:\\Windows\\SysWOW64\\PortableDeviceClassExtension.dll\"")
