#pragma comment(linker, "/export:AsyncUILoaderEntryW=\"C:\\Windows\\SysWOW64\\prnntfy.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\prnntfy.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\prnntfy.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\prnntfy.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\prnntfy.dll\"")
#pragma comment(linker, "/export:PrintNotifyTray_Exit=\"C:\\Windows\\SysWOW64\\prnntfy.dll\"")
#pragma comment(linker, "/export:PrintNotifyTray_Init=\"C:\\Windows\\SysWOW64\\prnntfy.dll\"")
