#pragma comment(linker, "/export:??0MIFree@@QAE@PAX@Z=\"C:\\Windows\\SysWOW64\\prvdmofcomp.dll\"")
#pragma comment(linker, "/export:??1MIFree@@QAE@XZ=\"C:\\Windows\\SysWOW64\\prvdmofcomp.dll\"")
#pragma comment(linker, "/export:??4MIServer@@QAEAAV0@$$QAV0@@Z=\"C:\\Windows\\SysWOW64\\prvdmofcomp.dll\"")
#pragma comment(linker, "/export:??4MIServer@@QAEAAV0@ABV0@@Z=\"C:\\Windows\\SysWOW64\\prvdmofcomp.dll\"")
#pragma comment(linker, "/export:CompileSchemaToWMI=\"C:\\Windows\\SysWOW64\\prvdmofcomp.dll\"")
#pragma comment(linker, "/export:CreateRegisterParameter=\"C:\\Windows\\SysWOW64\\prvdmofcomp.dll\"")
#pragma comment(linker, "/export:GetProviderSchema=\"C:\\Windows\\SysWOW64\\prvdmofcomp.dll\"")
#pragma comment(linker, "/export:GetProviderSchemaFile=\"C:\\Windows\\SysWOW64\\prvdmofcomp.dll\"")
