#pragma comment(linker, "/export:RdrSysprepSpecialize=\"C:\\Windows\\SysWOW64\\radardt.dll\"")
#pragma comment(linker, "/export:RdrSysprepSpecializeOffline=\"C:\\Windows\\SysWOW64\\radardt.dll\"")
#pragma comment(linker, "/export:WdiDiagnosticModuleMain=\"C:\\Windows\\SysWOW64\\radardt.dll\"")
#pragma comment(linker, "/export:WdiGetDiagnosticModuleInterfaceVersion=\"C:\\Windows\\SysWOW64\\radardt.dll\"")
#pragma comment(linker, "/export:WdiHandleInstance=\"C:\\Windows\\SysWOW64\\radardt.dll\"")
