#pragma comment(linker, "/export:InitializeProtocolEngine=\"C:\\Windows\\SysWOW64\\rasppp.dll\"")
#pragma comment(linker, "/export:InitializeServerProtocolEngine=\"C:\\Windows\\SysWOW64\\rasppp.dll\"")
#pragma comment(linker, "/export:PppStop=\"C:\\Windows\\SysWOW64\\rasppp.dll\"")
#pragma comment(linker, "/export:RasCpEnumProtocolIds=\"C:\\Windows\\SysWOW64\\rasppp.dll\"")
#pragma comment(linker, "/export:RasCpGetInfo=\"C:\\Windows\\SysWOW64\\rasppp.dll\"")
#pragma comment(linker, "/export:SendMessageToProtocolEngine=\"C:\\Windows\\SysWOW64\\rasppp.dll\"")
#pragma comment(linker, "/export:UninitializeProtocolEngine=\"C:\\Windows\\SysWOW64\\rasppp.dll\"")
#pragma comment(linker, "/export:UninitializeServerProtocolEngine=\"C:\\Windows\\SysWOW64\\rasppp.dll\"")
