#pragma comment(linker, "/export:MediaVRCreateORTCRenderer=\"C:\\Windows\\SysWOW64\\rtmmvrortc.MediaVRCreateORTCRenderer\"")
#pragma comment(linker, "/export:MediaVRDestroyORTCRenderer=\"C:\\Windows\\SysWOW64\\rtmmvrortc.MediaVRDestroyORTCRenderer\"")
#pragma comment(linker, "/export:MediaVRGetORTCRenderContext=\"C:\\Windows\\SysWOW64\\rtmmvrortc.MediaVRGetORTCRenderContext\"")
#pragma comment(linker, "/export:MediaVRRequestKeyFrame=\"C:\\Windows\\SysWOW64\\rtmmvrortc.MediaVRRequestKeyFrame\"")
#pragma comment(linker, "/export:MediaVRSetDecodingHealth=\"C:\\Windows\\SysWOW64\\rtmmvrortc.MediaVRSetDecodingHealth\"")
