#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\scansetting.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\scansetting.DllMain\"")
#pragma comment(linker, "/export:GetDefaultProfileScan=\"C:\\Windows\\SysWOW64\\scansetting.GetDefaultProfileScan\"")
#pragma comment(linker, "/export:GetImageDialog=\"C:\\Windows\\SysWOW64\\scansetting.GetImageDialog\"")
#pragma comment(linker, "/export:ProfilesDialog=\"C:\\Windows\\SysWOW64\\scansetting.ProfilesDialog\"")
#pragma comment(linker, "/export:ProgDlgTakeFgIfShowing=\"C:\\Windows\\SysWOW64\\scansetting.ProgDlgTakeFgIfShowing\"")
