#pragma comment(linker, "/export:GetOpenCardNameA=\"C:\\Windows\\SysWOW64\\SCardDlg.dll\"")
#pragma comment(linker, "/export:GetOpenCardNameW=\"C:\\Windows\\SysWOW64\\SCardDlg.dll\"")
#pragma comment(linker, "/export:SCardDlgExtendedError=\"C:\\Windows\\SysWOW64\\SCardDlg.dll\"")
#pragma comment(linker, "/export:SCardUIDlgSelectCardA=\"C:\\Windows\\SysWOW64\\SCardDlg.dll\"")
#pragma comment(linker, "/export:SCardUIDlgSelectCardW=\"C:\\Windows\\SysWOW64\\SCardDlg.dll\"")
