#pragma comment(linker, "/export:SRSetRestorePoint=\"C:\\Windows\\SysWOW64\\sfc.SRSetRestorePoint\"")
#pragma comment(linker, "/export:SRSetRestorePointA=\"C:\\Windows\\SysWOW64\\sfc.SRSetRestorePointA\"")
#pragma comment(linker, "/export:SRSetRestorePointW=\"C:\\Windows\\SysWOW64\\sfc.SRSetRestorePointW\"")
#pragma comment(linker, "/export:SfcGetNextProtectedFile=\"C:\\Windows\\SysWOW64\\sfc.SfcGetNextProtectedFile\"")
#pragma comment(linker, "/export:SfcIsFileProtected=\"C:\\Windows\\SysWOW64\\sfc.SfcIsFileProtected\"")
#pragma comment(linker, "/export:SfcIsKeyProtected=\"C:\\Windows\\SysWOW64\\sfc.SfcIsKeyProtected\"")
#pragma comment(linker, "/export:SfpVerifyFile=\"C:\\Windows\\SysWOW64\\sfc.SfpVerifyFile\"")
