#pragma comment(linker, "/export:SHUnattendedSetup=\"C:\\Windows\\SysWOW64\\shsetup.SHUnattendedSetup\"")
#pragma comment(linker, "/export:SHUnattendedSetupA=\"C:\\Windows\\SysWOW64\\shsetup.SHUnattendedSetupA\"")
#pragma comment(linker, "/export:SHUnattendedSetupW=\"C:\\Windows\\SysWOW64\\shsetup.SHUnattendedSetupW\"")
#pragma comment(linker, "/export:Sysprep_Cleanup_Shell=\"C:\\Windows\\SysWOW64\\shsetup.Sysprep_Cleanup_Shell\"")
#pragma comment(linker, "/export:Sysprep_Generalize_Shell=\"C:\\Windows\\SysWOW64\\shsetup.Sysprep_Generalize_Shell\"")
