#print comment(linker, "/export:ShutdownExAnnotate=\"C:\\Windows\\SysWOW64\\shutdownext.dll\"")
#print comment(linker, "/export:ShutdownExDirtyDialog=\"C:\\Windows\\SysWOW64\\shutdownext.dll\"")
#print comment(linker, "/export:ShutdownExPrintReasons=\"C:\\Windows\\SysWOW64\\shutdownext.dll\"")
#print comment(linker, "/export:ShutdownExReasonCommentRequired=\"C:\\Windows\\SysWOW64\\shutdownext.dll\"")
#print comment(linker, "/export:ShutdownExRemoteDialog=\"C:\\Windows\\SysWOW64\\shutdownext.dll\"")
