#pragma comment(linker, "/export:ShutdownExAnnotate=\"C:\\Windows\\SysWOW64\\shutdownext.dll\"")
#pragma comment(linker, "/export:ShutdownExDirtyDialog=\"C:\\Windows\\SysWOW64\\shutdownext.dll\"")
#pragma comment(linker, "/export:ShutdownExPrintReasons=\"C:\\Windows\\SysWOW64\\shutdownext.dll\"")
#pragma comment(linker, "/export:ShutdownExReasonCommentRequired=\"C:\\Windows\\SysWOW64\\shutdownext.dll\"")
#pragma comment(linker, "/export:ShutdownExRemoteDialog=\"C:\\Windows\\SysWOW64\\shutdownext.dll\"")
