#pragma comment(linker, "/export:SssBindServicingStack=\"C:\\Windows\\SysWOW64\\SSShim.dll\"")
#pragma comment(linker, "/export:SssGetServicingStackFilePath=\"C:\\Windows\\SysWOW64\\SSShim.dll\"")
#pragma comment(linker, "/export:SssGetServicingStackFilePathLength=\"C:\\Windows\\SysWOW64\\SSShim.dll\"")
#pragma comment(linker, "/export:SssPreloadDownlevelDependencies=\"C:\\Windows\\SysWOW64\\SSShim.dll\"")
#pragma comment(linker, "/export:SssReleaseServicingStack=\"C:\\Windows\\SysWOW64\\SSShim.dll\"")
