#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\Startupscan.DllMain\"")
#pragma comment(linker, "/export:SusResetNotification=\"C:\\Windows\\SysWOW64\\Startupscan.SusResetNotification\"")
#pragma comment(linker, "/export:SusRunOEMTaskOffline=\"C:\\Windows\\SysWOW64\\Startupscan.SusRunOEMTaskOffline\"")
#pragma comment(linker, "/export:SusRunOEMTaskOnline=\"C:\\Windows\\SysWOW64\\Startupscan.SusRunOEMTaskOnline\"")
#pragma comment(linker, "/export:SusRunTask=\"C:\\Windows\\SysWOW64\\Startupscan.SusRunTask\"")
