#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\SyncSettings.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\SyncSettings.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\SyncSettings.dll\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\SysWOW64\\SyncSettings.dll\"")
#pragma comment(linker, "/export:GetSetting=\"C:\\Windows\\SysWOW64\\SyncSettings.dll\"")
