#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\UiaManager.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\UiaManager.dll\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\SysWOW64\\UiaManager.dll\"")
#pragma comment(linker, "/export:UiaInitCrossMachineConnection=\"C:\\Windows\\SysWOW64\\UiaManager.dll\"")
#pragma comment(linker, "/export:UiaInitCrossMachineConnectionW=\"C:\\Windows\\SysWOW64\\UiaManager.dll\"")
