#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\usbceip.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\usbceip.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\usbceip.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\usbceip.dll\"")
#print comment(linker, "/export:UsbCeip_Execute=\"C:\\Windows\\SysWOW64\\usbceip.dll\"")
