#pragma comment(linker, "/export:CreateCardParser=\"C:\\Windows\\SysWOW64\\VCardParser.dll\"")
#pragma comment(linker, "/export:CreateCardParserEx=\"C:\\Windows\\SysWOW64\\VCardParser.dll\"")
#pragma comment(linker, "/export:CreateCardParserExA=\"C:\\Windows\\SysWOW64\\VCardParser.dll\"")
#pragma comment(linker, "/export:CreateICalGen=\"C:\\Windows\\SysWOW64\\VCardParser.dll\"")
#pragma comment(linker, "/export:CreateVCardGen=\"C:\\Windows\\SysWOW64\\VCardParser.dll\"")
#pragma comment(linker, "/export:EncodeQP=\"C:\\Windows\\SysWOW64\\VCardParser.dll\"")
