#pragma comment(linker, "/export:VM3DGLHelperCleanup=\"C:\\Windows\\SysWOW64\\vm3dglhelper.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperDevLog=\"C:\\Windows\\SysWOW64\\vm3dglhelper.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperGetDevCapMaxCount=\"C:\\Windows\\SysWOW64\\vm3dglhelper.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperInit=\"C:\\Windows\\SysWOW64\\vm3dglhelper.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperLog=\"C:\\Windows\\SysWOW64\\vm3dglhelper.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperRLog=\"C:\\Windows\\SysWOW64\\vm3dglhelper.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperSetLogLevels=\"C:\\Windows\\SysWOW64\\vm3dglhelper.dll\"")
