#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\wdc.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\wdc.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\wdc.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\wdc.dll\"")
#pragma comment(linker, "/export:WdcParseLegacyFile=\"C:\\Windows\\SysWOW64\\wdc.dll\"")
#pragma comment(linker, "/export:WdcRunTaskAsInteractiveUser=\"C:\\Windows\\SysWOW64\\wdc.dll\"")
