#pragma comment(linker, "/export:WSManPluginShutdown=\"C:\\Windows\\SysWOW64\\wevtfwd.dll\"")
#pragma comment(linker, "/export:WSManPluginStartup=\"C:\\Windows\\SysWOW64\\wevtfwd.dll\"")
#pragma comment(linker, "/export:WSManProvPullEvents=\"C:\\Windows\\SysWOW64\\wevtfwd.dll\"")
#pragma comment(linker, "/export:WSManProvSubscribe=\"C:\\Windows\\SysWOW64\\wevtfwd.dll\"")
#pragma comment(linker, "/export:WSManProvUnsubscribe=\"C:\\Windows\\SysWOW64\\wevtfwd.dll\"")
