#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.Mirage.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.Mirage.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactoryMirage=\"C:\\Windows\\SysWOW64\\Windows.Mirage.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.Mirage.dll\"")
#pragma comment(linker, "/export:DllGetClassObjectMirage=\"C:\\Windows\\SysWOW64\\Windows.Mirage.dll\"")
#pragma comment(linker, "/export:InjectDependency=\"C:\\Windows\\SysWOW64\\Windows.Mirage.dll\"")
