#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.dll\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.dll\"")
#pragma comment(linker, "/export:GetDependencyLocatorStorage=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.dll\"")
#pragma comment(linker, "/export:SendTelemetryOnSuspend=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.dll\"")
#pragma comment(linker, "/export:XamlTestHookFreeControlsResourceLibrary=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.dll\"")
