#print comment(linker, "/export:BthEvtBrCreateBroker=\"C:\\Windows\\SysWOW64\\Windows.Internal.Bluetooth.dll\"")
#print comment(linker, "/export:BthEvtBrDeleteBroker=\"C:\\Windows\\SysWOW64\\Windows.Internal.Bluetooth.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.Internal.Bluetooth.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.Internal.Bluetooth.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.Internal.Bluetooth.dll\"")
