#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.Perception.Stub.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.Perception.Stub.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactoryPerceptionStub=\"C:\\Windows\\SysWOW64\\Windows.Perception.Stub.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.Perception.Stub.dll\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\SysWOW64\\Windows.Perception.Stub.dll\"")
