#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.InkControls.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.InkControls.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.InkControls.dll\"")
#pragma comment(linker, "/export:GetDependencyLocatorStorage=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.InkControls.dll\"")
#pragma comment(linker, "/export:XamlTestHookFreeInkControlsResourceLibrary=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.InkControls.dll\"")
