#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\WlanMM.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\WlanMM.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\WlanMM.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\WlanMM.DllUnregisterServer\"")
#pragma comment(linker, "/export:StartDiagnosticsW=\"C:\\Windows\\SysWOW64\\WlanMM.StartDiagnosticsW\"")
