#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\wlangpui.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\wlangpui.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\wlangpui.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\wlangpui.dll\"")
#pragma comment(linker, "/export:GetAdPolicyAsXML=\"C:\\Windows\\SysWOW64\\wlangpui.dll\"")
#pragma comment(linker, "/export:GetWmiPolicyAsXML=\"C:\\Windows\\SysWOW64\\wlangpui.dll\"")
