#pragma comment(linker, "/export:WmsgBroadcastMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.WmsgBroadcastMessage\"")
#pragma comment(linker, "/export:WmsgBroadcastNotifyMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.WmsgBroadcastNotifyMessage\"")
#pragma comment(linker, "/export:WmsgPostMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.WmsgPostMessage\"")
#pragma comment(linker, "/export:WmsgPostNotifyMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.WmsgPostNotifyMessage\"")
#pragma comment(linker, "/export:WmsgSendMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.WmsgSendMessage\"")
#pragma comment(linker, "/export:WmsgSendPSPMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.WmsgSendPSPMessage\"")
