#print comment(linker, "/export:CreateInstance=\"C:\\Windows\\SysWOW64\\WMVDECOD.DLL\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\WMVDECOD.DLL\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\WMVDECOD.DLL\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\WMVDECOD.DLL\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\WMVDECOD.DLL\"")
#print comment(linker, "/export:GetVC1DecoderFunctionTable=\"C:\\Windows\\SysWOW64\\WMVDECOD.DLL\"")
