#pragma comment(linker, "/export:CreateInstance=\"C:\\Windows\\SysWOW64\\WMVSENCD.DLL\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\WMVSENCD.DLL\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\WMVSENCD.DLL\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\WMVSENCD.DLL\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\WMVSENCD.DLL\"")
