#print comment(linker, "/export:WpbcCleanup=\"C:\\Windows\\SysWOW64\\wpbcreds.dll\"")
#print comment(linker, "/export:WpbcCreateRemoveTestCredentials=\"C:\\Windows\\SysWOW64\\wpbcreds.dll\"")
#print comment(linker, "/export:WpbcCreateTestPin=\"C:\\Windows\\SysWOW64\\wpbcreds.dll\"")
#print comment(linker, "/export:WpbcExportCredentials=\"C:\\Windows\\SysWOW64\\wpbcreds.dll\"")
#print comment(linker, "/export:WpbcGetPinInfo=\"C:\\Windows\\SysWOW64\\wpbcreds.dll\"")
#print comment(linker, "/export:WpbcInitialize=\"C:\\Windows\\SysWOW64\\wpbcreds.dll\"")
#print comment(linker, "/export:WpbcVerifyUser=\"C:\\Windows\\SysWOW64\\wpbcreds.dll\"")
