#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Wpc.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Wpc.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Wpc.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\Wpc.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\Wpc.dll\"")
#pragma comment(linker, "/export:WpcTimeRestrictionsCreateLocalOverride=\"C:\\Windows\\SysWOW64\\Wpc.dll\"")
