#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\WpcWebFilter.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\WpcWebFilter.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\WpcWebFilter.dll\"")
#pragma comment(linker, "/export:WpcWebFilterCreate=\"C:\\Windows\\SysWOW64\\WpcWebFilter.dll\"")
#pragma comment(linker, "/export:WpcWebFilterDestroy=\"C:\\Windows\\SysWOW64\\WpcWebFilter.dll\"")
#pragma comment(linker, "/export:WpcWebFilterGet=\"C:\\Windows\\SysWOW64\\WpcWebFilter.dll\"")
