#pragma comment(linker, "/export:DtcGetTransactionManager=\"C:\\Windows\\SysWOW64\\xolehlp.DtcGetTransactionManager\"")
#pragma comment(linker, "/export:DtcGetTransactionManagerC=\"C:\\Windows\\SysWOW64\\xolehlp.DtcGetTransactionManagerC\"")
#pragma comment(linker, "/export:DtcGetTransactionManagerEx=\"C:\\Windows\\SysWOW64\\xolehlp.DtcGetTransactionManagerEx\"")
#pragma comment(linker, "/export:DtcGetTransactionManagerExA=\"C:\\Windows\\SysWOW64\\xolehlp.DtcGetTransactionManagerExA\"")
#pragma comment(linker, "/export:DtcGetTransactionManagerExW=\"C:\\Windows\\SysWOW64\\xolehlp.DtcGetTransactionManagerExW\"")
#pragma comment(linker, "/export:FreezeLocalTransactionManagers=\"C:\\Windows\\SysWOW64\\xolehlp.FreezeLocalTransactionManagers\"")
#pragma comment(linker, "/export:GetDtcLocaleResourceHandle=\"C:\\Windows\\SysWOW64\\xolehlp.GetDtcLocaleResourceHandle\"")
#pragma comment(linker, "/export:ThawLocalTransactionManagers=\"C:\\Windows\\SysWOW64\\xolehlp.ThawLocalTransactionManagers\"")
