#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\XpsDocumentTargetPrint.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\XpsDocumentTargetPrint.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\XpsDocumentTargetPrint.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\XpsDocumentTargetPrint.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\XpsDocumentTargetPrint.DllUnregisterServer\"")
