#pragma comment(linker, "/export:AppCleanup=\"C:\\Windows\\SysWOW64\\avicap32.AppCleanup\"")
#pragma comment(linker, "/export:capCreateCaptureWindowA=\"C:\\Windows\\SysWOW64\\avicap32.capCreateCaptureWindowA\"")
#pragma comment(linker, "/export:capCreateCaptureWindowW=\"C:\\Windows\\SysWOW64\\avicap32.capCreateCaptureWindowW\"")
#pragma comment(linker, "/export:capGetDriverDescriptionA=\"C:\\Windows\\SysWOW64\\avicap32.capGetDriverDescriptionA\"")
#pragma comment(linker, "/export:capGetDriverDescriptionW=\"C:\\Windows\\SysWOW64\\avicap32.capGetDriverDescriptionW\"")
#pragma comment(linker, "/export:videoThunk32=\"C:\\Windows\\SysWOW64\\avicap32.videoThunk32\"")
