#pragma comment(linker, "/export:CAPISysPrep_Generalize=\"C:\\Windows\\SysWOW64\\capisp.CAPISysPrep_Generalize\"")
#pragma comment(linker, "/export:CryptoSysPrep_Clean=\"C:\\Windows\\SysWOW64\\capisp.CryptoSysPrep_Clean\"")
#pragma comment(linker, "/export:CryptoSysPrep_Specialize=\"C:\\Windows\\SysWOW64\\capisp.CryptoSysPrep_Specialize\"")
#pragma comment(linker, "/export:CryptoSysPrep_Specialize_Clone=\"C:\\Windows\\SysWOW64\\capisp.CryptoSysPrep_Specialize_Clone\"")
#pragma comment(linker, "/export:CryptoSysPrep_Specialize_Offline=\"C:\\Windows\\SysWOW64\\capisp.CryptoSysPrep_Specialize_Offline\"")
