#pragma comment(linker, "/export:DebugSetMute=\"C:\\Windows\\SysWOW64\\d3d8.DebugSetMute\"")
#pragma comment(linker, "/export:Direct3D8EnableMaximizedWindowedModeShim=\"C:\\Windows\\SysWOW64\\d3d8.Direct3D8EnableMaximizedWindowedModeShim\"")
#pragma comment(linker, "/export:Direct3DCreate8=\"C:\\Windows\\SysWOW64\\d3d8.Direct3DCreate8\"")
#pragma comment(linker, "/export:ValidatePixelShader=\"C:\\Windows\\SysWOW64\\d3d8.ValidatePixelShader\"")
#pragma comment(linker, "/export:ValidateVertexShader=\"C:\\Windows\\SysWOW64\\d3d8.ValidateVertexShader\"")
