#pragma comment(linker, "/export:DirectInputCreateA=\"C:\\Windows\\SysWOW64\\dinput.DirectInputCreateA\"")
#pragma comment(linker, "/export:DirectInputCreateEx=\"C:\\Windows\\SysWOW64\\dinput.DirectInputCreateEx\"")
#pragma comment(linker, "/export:DirectInputCreateW=\"C:\\Windows\\SysWOW64\\dinput.DirectInputCreateW\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\dinput.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\dinput.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\dinput.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\dinput.DllUnregisterServer\"")
