#pragma comment(linker, "/export:ActivatePackage=\"C:\\Windows\\SysWOW64\\embeddedmodesvcapi.ActivatePackage\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\embeddedmodesvcapi.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\embeddedmodesvcapi.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\embeddedmodesvcapi.DllGetClassObject\"")
#pragma comment(linker, "/export:IsEmbeddedModeAllowed=\"C:\\Windows\\SysWOW64\\embeddedmodesvcapi.IsEmbeddedModeAllowed\"")
