#pragma comment(linker, "/export:CreateExecutivePlatform=\"C:\\Windows\\SysWOW64\\mmcndmgr.CreateExecutivePlatform\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\mmcndmgr.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\mmcndmgr.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\mmcndmgr.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\mmcndmgr.DllUnregisterServer\"")
