#pragma comment(linker, "/export:PcaGetFileInfoFromPath=\"C:\\Windows\\SysWOW64\\pcacli.PcaGetFileInfoFromPath\"")
#pragma comment(linker, "/export:PcaIsPcaDisabled=\"C:\\Windows\\SysWOW64\\pcacli.PcaIsPcaDisabled\"")
#pragma comment(linker, "/export:PcaLinkChildProcessToParent=\"C:\\Windows\\SysWOW64\\pcacli.PcaLinkChildProcessToParent\"")
#pragma comment(linker, "/export:PcaMonitorProcess=\"C:\\Windows\\SysWOW64\\pcacli.PcaMonitorProcess\"")
#pragma comment(linker, "/export:PcaMonitorProcess2=\"C:\\Windows\\SysWOW64\\pcacli.PcaMonitorProcess2\"")
#pragma comment(linker, "/export:PcaNotifyMsiInstall=\"C:\\Windows\\SysWOW64\\pcacli.PcaNotifyMsiInstall\"")
#pragma comment(linker, "/export:PcaNotifyStatusIcon=\"C:\\Windows\\SysWOW64\\pcacli.PcaNotifyStatusIcon\"")
#pragma comment(linker, "/export:PcaSendToService=\"C:\\Windows\\SysWOW64\\pcacli.PcaSendToService\"")
