#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\racpldlg.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\racpldlg.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\racpldlg.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\racpldlg.DllUnregisterServer\"")
#pragma comment(linker, "/export:ShowPasswordDialog=\"C:\\Windows\\SysWOW64\\racpldlg.ShowPasswordDialog\"")
