#pragma comment(linker, "/export:drvCommConfigDialogA=\"C:\\Windows\\SysWOW64\\serialui.drvCommConfigDialogA\"")
#pragma comment(linker, "/export:drvCommConfigDialogW=\"C:\\Windows\\SysWOW64\\serialui.drvCommConfigDialogW\"")
#pragma comment(linker, "/export:drvGetDefaultCommConfigA=\"C:\\Windows\\SysWOW64\\serialui.drvGetDefaultCommConfigA\"")
#pragma comment(linker, "/export:drvGetDefaultCommConfigW=\"C:\\Windows\\SysWOW64\\serialui.drvGetDefaultCommConfigW\"")
#pragma comment(linker, "/export:drvSetDefaultCommConfigA=\"C:\\Windows\\SysWOW64\\serialui.drvSetDefaultCommConfigA\"")
#pragma comment(linker, "/export:drvSetDefaultCommConfigW=\"C:\\Windows\\SysWOW64\\serialui.drvSetDefaultCommConfigW\"")
