#pragma comment(linker, "/export:VM3DGLHelperCleanup=\"C:\\Windows\\SysWOW64\\vm3dglhelper.VM3DGLHelperCleanup\"")
#pragma comment(linker, "/export:VM3DGLHelperDevLog=\"C:\\Windows\\SysWOW64\\vm3dglhelper.VM3DGLHelperDevLog\"")
#pragma comment(linker, "/export:VM3DGLHelperGetDevCapMaxCount=\"C:\\Windows\\SysWOW64\\vm3dglhelper.VM3DGLHelperGetDevCapMaxCount\"")
#pragma comment(linker, "/export:VM3DGLHelperInit=\"C:\\Windows\\SysWOW64\\vm3dglhelper.VM3DGLHelperInit\"")
#pragma comment(linker, "/export:VM3DGLHelperLog=\"C:\\Windows\\SysWOW64\\vm3dglhelper.VM3DGLHelperLog\"")
#pragma comment(linker, "/export:VM3DGLHelperRLog=\"C:\\Windows\\SysWOW64\\vm3dglhelper.VM3DGLHelperRLog\"")
#pragma comment(linker, "/export:VM3DGLHelperSetLogLevels=\"C:\\Windows\\SysWOW64\\vm3dglhelper.VM3DGLHelperSetLogLevels\"")
