#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\AudioSes.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\AudioSes.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\AudioSes.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\AudioSes.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\AudioSes.DllUnregisterServer\"")
