#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\eapphost.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\eapphost.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\eapphost.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\eapphost.DllUnregisterServer\"")
#pragma comment(linker, "/export:InitializeEapHost=\"C:\\Windows\\SysWOW64\\eapphost.InitializeEapHost\"")
#pragma comment(linker, "/export:OnSessionChange=\"C:\\Windows\\SysWOW64\\eapphost.OnSessionChange\"")
#pragma comment(linker, "/export:StopServiceOnLowPower=\"C:\\Windows\\SysWOW64\\eapphost.StopServiceOnLowPower\"")
#pragma comment(linker, "/export:UninitializeEapHost=\"C:\\Windows\\SysWOW64\\eapphost.UninitializeEapHost\"")
