#pragma comment(linker, "/export:DoAction=\"C:\\Windows\\SysWOW64\\elslad.DoAction\"")
#pragma comment(linker, "/export:FreePropertyBag=\"C:\\Windows\\SysWOW64\\elslad.FreePropertyBag\"")
#pragma comment(linker, "/export:FreeService=\"C:\\Windows\\SysWOW64\\elslad.FreeService\"")
#pragma comment(linker, "/export:InitService=\"C:\\Windows\\SysWOW64\\elslad.InitService\"")
#pragma comment(linker, "/export:RecognizeText=\"C:\\Windows\\SysWOW64\\elslad.RecognizeText\"")
