#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\iscsiwmiv2.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\iscsiwmiv2.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\iscsiwmiv2.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\iscsiwmiv2.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\iscsiwmiv2.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProviderClassID=\"C:\\Windows\\SysWOW64\\iscsiwmiv2.GetProviderClassID\"")
#pragma comment(linker, "/export:MI_Main=\"C:\\Windows\\SysWOW64\\iscsiwmiv2.MI_Main\"")
