#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\jscript9diag.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\jscript9diag.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\jscript9diag.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\jscript9diag.DllUnregisterServer\"")
#pragma comment(linker, "/export:FreeDumpStreams=\"C:\\Windows\\SysWOW64\\jscript9diag.FreeDumpStreams\"")
#pragma comment(linker, "/export:GetDumpStreams=\"C:\\Windows\\SysWOW64\\jscript9diag.GetDumpStreams\"")
