#pragma comment(linker, "/export:NetDriverInstallClose=\"C:\\Windows\\SysWOW64\\NetDriverInstall.NetDriverInstallClose\"")
#pragma comment(linker, "/export:NetDriverInstallCommit=\"C:\\Windows\\SysWOW64\\NetDriverInstall.NetDriverInstallCommit\"")
#pragma comment(linker, "/export:NetDriverInstallInitialize=\"C:\\Windows\\SysWOW64\\NetDriverInstall.NetDriverInstallInitialize\"")
#pragma comment(linker, "/export:NetDriverInstallProcessAdditions=\"C:\\Windows\\SysWOW64\\NetDriverInstall.NetDriverInstallProcessAdditions\"")
#pragma comment(linker, "/export:NetDriverInstallProcessRemovals=\"C:\\Windows\\SysWOW64\\NetDriverInstall.NetDriverInstallProcessRemovals\"")
#pragma comment(linker, "/export:NetDriverInstallSync=\"C:\\Windows\\SysWOW64\\NetDriverInstall.NetDriverInstallSync\"")
