#pragma comment(linker, "/export:ShutdownExAnnotate=\"C:\\Windows\\SysWOW64\\shutdownext.ShutdownExAnnotate\"")
#pragma comment(linker, "/export:ShutdownExDirtyDialog=\"C:\\Windows\\SysWOW64\\shutdownext.ShutdownExDirtyDialog\"")
#pragma comment(linker, "/export:ShutdownExPrintReasons=\"C:\\Windows\\SysWOW64\\shutdownext.ShutdownExPrintReasons\"")
#pragma comment(linker, "/export:ShutdownExReasonCommentRequired=\"C:\\Windows\\SysWOW64\\shutdownext.ShutdownExReasonCommentRequired\"")
#pragma comment(linker, "/export:ShutdownExRemoteDialog=\"C:\\Windows\\SysWOW64\\shutdownext.ShutdownExRemoteDialog\"")
