#pragma comment(linker, "/export:AttemptToUpdateTimeZone=\"C:\\Windows\\SysWOW64\\tzautoupdate.AttemptToUpdateTimeZone\"")
#pragma comment(linker, "/export:AttemptToUpdateTimeZoneAndEnableChangeDetection=\"C:\\Windows\\SysWOW64\\tzautoupdate.AttemptToUpdateTimeZoneAndEnableChangeDetection\"")
#pragma comment(linker, "/export:DisableTimeZoneAutoUpdate=\"C:\\Windows\\SysWOW64\\tzautoupdate.DisableTimeZoneAutoUpdate\"")
#pragma comment(linker, "/export:EnableTimeZoneAutoUpdate=\"C:\\Windows\\SysWOW64\\tzautoupdate.EnableTimeZoneAutoUpdate\"")
#pragma comment(linker, "/export:IsTimeZoneAutoUpdateEnabled=\"C:\\Windows\\SysWOW64\\tzautoupdate.IsTimeZoneAutoUpdateEnabled\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\SysWOW64\\tzautoupdate.ServiceMain\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\SysWOW64\\tzautoupdate.SvchostPushServiceGlobals\"")
