#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.InkControls.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.InkControls.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.InkControls.DllGetClassObject\"")
#pragma comment(linker, "/export:GetDependencyLocatorStorage=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.InkControls.GetDependencyLocatorStorage\"")
#pragma comment(linker, "/export:XamlTestHookFreeInkControlsResourceLibrary=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.InkControls.XamlTestHookFreeInkControlsResourceLibrary\"")
