#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.DllMain\"")
#pragma comment(linker, "/export:GetDependencyLocatorStorage=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.GetDependencyLocatorStorage\"")
#pragma comment(linker, "/export:SendTelemetryOnSuspend=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.SendTelemetryOnSuspend\"")
#pragma comment(linker, "/export:XamlTestHookFreeControlsResourceLibrary=\"C:\\Windows\\SysWOW64\\Windows.UI.Xaml.Controls.XamlTestHookFreeControlsResourceLibrary\"")
