#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\wkspbrokerAx.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\wkspbrokerAx.DllGetClassObject\"")
#pragma comment(linker, "/export:DllInstall=\"C:\\Windows\\SysWOW64\\wkspbrokerAx.DllInstall\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\wkspbrokerAx.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\wkspbrokerAx.DllUnregisterServer\"")
