#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\wlangpui.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\wlangpui.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\wlangpui.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\wlangpui.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetAdPolicyAsXML=\"C:\\Windows\\SysWOW64\\wlangpui.GetAdPolicyAsXML\"")
#pragma comment(linker, "/export:GetWmiPolicyAsXML=\"C:\\Windows\\SysWOW64\\wlangpui.GetWmiPolicyAsXML\"")
