#pragma comment(linker, "/export:CreateSecurityPage=\"C:\\Windows\\System32\\aclui.CreateSecurityPage\"")
#pragma comment(linker, "/export:EditConditionalAceClaims=\"C:\\Windows\\System32\\aclui.EditConditionalAceClaims\"")
#pragma comment(linker, "/export:EditResourceCondition=\"C:\\Windows\\System32\\aclui.EditResourceCondition\"")
#pragma comment(linker, "/export:EditSecurity=\"C:\\Windows\\System32\\aclui.EditSecurity\"")
#pragma comment(linker, "/export:EditSecurityAdvanced=\"C:\\Windows\\System32\\aclui.EditSecurityAdvanced\"")
#pragma comment(linker, "/export:GetLocalizedStringForCondition=\"C:\\Windows\\System32\\aclui.GetLocalizedStringForCondition\"")
#pragma comment(linker, "/export:GetTlsIndexForClaimDictionary=\"C:\\Windows\\System32\\aclui.GetTlsIndexForClaimDictionary\"")
#pragma comment(linker, "/export:IID_ISecurityInformation=\"C:\\Windows\\System32\\aclui.IID_ISecurityInformation\"")
