#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Analog.Shell.Broker.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Analog.Shell.Broker.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Analog.Shell.Broker.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\Analog.Shell.Broker.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\Analog.Shell.Broker.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\Analog.Shell.Broker.DllUnregisterServer\"")
