#pragma comment(linker, "/export:AuthzGetAccountType=\"C:\\Windows\\System32\\authentication.AuthzGetAccountType\"")
#pragma comment(linker, "/export:AuthzRequestTicketWithWindow=\"C:\\Windows\\System32\\authentication.AuthzRequestTicketWithWindow\"")
#pragma comment(linker, "/export:AuthzRequestTicketWithoutWindow=\"C:\\Windows\\System32\\authentication.AuthzRequestTicketWithoutWindow\"")
#pragma comment(linker, "/export:GetAccountType=\"C:\\Windows\\System32\\authentication.GetAccountType\"")
#pragma comment(linker, "/export:RequestTicketWithWindow=\"C:\\Windows\\System32\\authentication.RequestTicketWithWindow\"")
#pragma comment(linker, "/export:RequestTicketWithoutWindow=\"C:\\Windows\\System32\\authentication.RequestTicketWithoutWindow\"")
