#pragma comment(linker, "/export:PsmBiExtInitialize=\"C:\\Windows\\System32\\bisrv.PsmBiExtInitialize\"")
#pragma comment(linker, "/export:PsmBiExtNotifyAppState=\"C:\\Windows\\System32\\bisrv.PsmBiExtNotifyAppState\"")
#pragma comment(linker, "/export:PsmBiExtNotifySessionStateChange=\"C:\\Windows\\System32\\bisrv.PsmBiExtNotifySessionStateChange\"")
#pragma comment(linker, "/export:PsmBiExtNotifySessionUserStateChange=\"C:\\Windows\\System32\\bisrv.PsmBiExtNotifySessionUserStateChange\"")
#pragma comment(linker, "/export:PsmBiExtNotifyWerReportProgress=\"C:\\Windows\\System32\\bisrv.PsmBiExtNotifyWerReportProgress\"")
#pragma comment(linker, "/export:PsmBiExtPrepareToSuspendPackage=\"C:\\Windows\\System32\\bisrv.PsmBiExtPrepareToSuspendPackage\"")
#pragma comment(linker, "/export:PsmBiExtResumePackage=\"C:\\Windows\\System32\\bisrv.PsmBiExtResumePackage\"")
