#pragma comment(linker, "/export:CreateDCOMSecurityUIPage=\"C:\\Windows\\System32\\comuid.CreateDCOMSecurityUIPage\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\comuid.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\comuid.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\comuid.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\comuid.DllUnregisterServer\"")
