#pragma comment(linker, "/export:ConfigureRegistrationIEZoneMappings=\"C:\\Windows\\System32\\deviceregistration.ConfigureRegistrationIEZoneMappings\"")
#pragma comment(linker, "/export:DiscoverRegistrationService=\"C:\\Windows\\System32\\deviceregistration.DiscoverRegistrationService\"")
#pragma comment(linker, "/export:GetRegistrationInfo=\"C:\\Windows\\System32\\deviceregistration.GetRegistrationInfo\"")
#pragma comment(linker, "/export:IsRegistrationAvailable=\"C:\\Windows\\System32\\deviceregistration.IsRegistrationAvailable\"")
#pragma comment(linker, "/export:RegisterDevice=\"C:\\Windows\\System32\\deviceregistration.RegisterDevice\"")
#pragma comment(linker, "/export:UnRegisterDevice=\"C:\\Windows\\System32\\deviceregistration.UnRegisterDevice\"")
