#pragma comment(linker, "/export:EseShadowCreateShadow=\"C:\\Windows\\System32\\esevss.EseShadowCreateShadow\"")
#pragma comment(linker, "/export:EseShadowCreateSimpleShadow=\"C:\\Windows\\System32\\esevss.EseShadowCreateSimpleShadow\"")
#pragma comment(linker, "/export:EseShadowInit=\"C:\\Windows\\System32\\esevss.EseShadowInit\"")
#pragma comment(linker, "/export:EseShadowMountShadow=\"C:\\Windows\\System32\\esevss.EseShadowMountShadow\"")
#pragma comment(linker, "/export:EseShadowMountSimpleShadow=\"C:\\Windows\\System32\\esevss.EseShadowMountSimpleShadow\"")
#pragma comment(linker, "/export:EseShadowPurgeShadow=\"C:\\Windows\\System32\\esevss.EseShadowPurgeShadow\"")
#pragma comment(linker, "/export:EseShadowTerm=\"C:\\Windows\\System32\\esevss.EseShadowTerm\"")
#pragma comment(linker, "/export:VssIdToString=\"C:\\Windows\\System32\\esevss.VssIdToString\"")
