#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\fcon.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\fcon.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\fcon.DllGetClassObject\"")
#pragma comment(linker, "/export:GetCtacPropertyAlloc=\"C:\\Windows\\System32\\fcon.GetCtacPropertyAlloc\"")
#pragma comment(linker, "/export:ModifyStagingControls=\"C:\\Windows\\System32\\fcon.ModifyStagingControls\"")
