#pragma comment(linker, "/export:FthSysprepSpecialize=\"C:\\Windows\\System32\\fthsvc.FthSysprepSpecialize\"")
#pragma comment(linker, "/export:FthSysprepSpecializeOffline=\"C:\\Windows\\System32\\fthsvc.FthSysprepSpecializeOffline\"")
#pragma comment(linker, "/export:WdiDiagnosticModuleMain=\"C:\\Windows\\System32\\fthsvc.WdiDiagnosticModuleMain\"")
#pragma comment(linker, "/export:WdiGetDiagnosticModuleInterfaceVersion=\"C:\\Windows\\System32\\fthsvc.WdiGetDiagnosticModuleInterfaceVersion\"")
#pragma comment(linker, "/export:WdiHandleInstance=\"C:\\Windows\\System32\\fthsvc.WdiHandleInstance\"")
