#pragma comment(linker, "/export:CreateHrtfApo=\"C:\\Windows\\System32\\HrtfApo.CreateHrtfApo\"")
#pragma comment(linker, "/export:CreateHrtfApoWithDatasetType=\"C:\\Windows\\System32\\HrtfApo.CreateHrtfApoWithDatasetType\"")
#pragma comment(linker, "/export:CreateHrtfEngineFactory=\"C:\\Windows\\System32\\HrtfApo.CreateHrtfEngineFactory\"")
#pragma comment(linker, "/export:GetHrtfEngineMinFrameCount=\"C:\\Windows\\System32\\HrtfApo.GetHrtfEngineMinFrameCount\"")
#pragma comment(linker, "/export:IsHrtfApoAvailable=\"C:\\Windows\\System32\\HrtfApo.IsHrtfApoAvailable\"")
