#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Microsoft.Uev.PrinterCustomActions.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Microsoft.Uev.PrinterCustomActions.DllGetClassObject\"")
#pragma comment(linker, "/export:DllInstall=\"C:\\Windows\\System32\\Microsoft.Uev.PrinterCustomActions.DllInstall\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\Microsoft.Uev.PrinterCustomActions.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\Microsoft.Uev.PrinterCustomActions.DllUnregisterServer\"")
