#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MitigationClient.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\MitigationClient.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MitigationClient.DllGetClassObject\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\MitigationClient.ServiceMain\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\MitigationClient.SvchostPushServiceGlobals\"")
