#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\NgcIsoCtnr.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\NgcIsoCtnr.DllGetClassObject\"")
#pragma comment(linker, "/export:NgcIsoCtnrInitialize=\"C:\\Windows\\System32\\NgcIsoCtnr.NgcIsoCtnrInitialize\"")
#pragma comment(linker, "/export:NgcIsoCtnrInitializePregenPool=\"C:\\Windows\\System32\\NgcIsoCtnr.NgcIsoCtnrInitializePregenPool\"")
#pragma comment(linker, "/export:NgcIsoCtnrTriggerPregen=\"C:\\Windows\\System32\\NgcIsoCtnr.NgcIsoCtnrTriggerPregen\"")
#pragma comment(linker, "/export:NgcIsoCtnrUninitializePregenPool=\"C:\\Windows\\System32\\NgcIsoCtnr.NgcIsoCtnrUninitializePregenPool\"")
