#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\pcsvDevice.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\pcsvDevice.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\pcsvDevice.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\pcsvDevice.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\pcsvDevice.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProviderClassID=\"C:\\Windows\\System32\\pcsvDevice.GetProviderClassID\"")
#pragma comment(linker, "/export:MI_Main=\"C:\\Windows\\System32\\pcsvDevice.MI_Main\"")
