#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\pnpclean.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\pnpclean.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\pnpclean.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\pnpclean.DllUnregisterServer\"")
#pragma comment(linker, "/export:RunDLL_PnpClean=\"C:\\Windows\\System32\\pnpclean.RunDLL_PnpClean\"")
