#pragma comment(linker, "/export:ConnectToRoamingVhdProfile=\"C:\\Windows\\System32\\profsvcext.ConnectToRoamingVhdProfile\"")
#pragma comment(linker, "/export:CreateRoamingProviderInstance=\"C:\\Windows\\System32\\profsvcext.CreateRoamingProviderInstance\"")
#pragma comment(linker, "/export:InitializeSuspendFolderPolicyAndUploadTaskConfig=\"C:\\Windows\\System32\\profsvcext.InitializeSuspendFolderPolicyAndUploadTaskConfig\"")
#pragma comment(linker, "/export:RefreshSuspendFolderPolicyAndUploadTaskConfig=\"C:\\Windows\\System32\\profsvcext.RefreshSuspendFolderPolicyAndUploadTaskConfig\"")
#pragma comment(linker, "/export:StartRoamingClassFactories=\"C:\\Windows\\System32\\profsvcext.StartRoamingClassFactories\"")
#pragma comment(linker, "/export:StopRoamingClassFactories=\"C:\\Windows\\System32\\profsvcext.StopRoamingClassFactories\"")
#pragma comment(linker, "/export:WaitForNetworkForRoamingProfile=\"C:\\Windows\\System32\\profsvcext.WaitForNetworkForRoamingProfile\"")
