#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\rdpendp.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\rdpendp.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\rdpendp.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\rdpendp.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetTSAudioEndpointEnumeratorForSession=\"C:\\Windows\\System32\\rdpendp.GetTSAudioEndpointEnumeratorForSession\"")
