#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\sdengin2.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\sdengin2.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\sdengin2.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\sdengin2.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\sdengin2.DllUnregisterServer\"")
#pragma comment(linker, "/export:ExecuteScheduledBackup=\"C:\\Windows\\System32\\sdengin2.ExecuteScheduledBackup\"")
#pragma comment(linker, "/export:SdCheck=\"C:\\Windows\\System32\\sdengin2.SdCheck\"")
