#pragma comment(linker, "/export:SensNotifyNetconEvent=\"C:\\Windows\\System32\\Sens.SensNotifyNetconEvent\"")
#pragma comment(linker, "/export:SensNotifyRasEvent=\"C:\\Windows\\System32\\Sens.SensNotifyRasEvent\"")
#pragma comment(linker, "/export:SensNotifyWinlogonEvent=\"C:\\Windows\\System32\\Sens.SensNotifyWinlogonEvent\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\Sens.ServiceMain\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\Sens.SvchostPushServiceGlobals\"")
