#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\SensorsClassExtension.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\SensorsClassExtension.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\SensorsClassExtension.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\SensorsClassExtension.DllUnregisterServer\"")
#pragma comment(linker, "/export:Microsoft_WDF_UMDF_Version=\"C:\\Windows\\System32\\SensorsClassExtension.Microsoft_WDF_UMDF_Version\"")
