#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\Startupscan.DllMain\"")
#pragma comment(linker, "/export:SusResetNotification=\"C:\\Windows\\System32\\Startupscan.SusResetNotification\"")
#pragma comment(linker, "/export:SusRunOEMTaskOffline=\"C:\\Windows\\System32\\Startupscan.SusRunOEMTaskOffline\"")
#pragma comment(linker, "/export:SusRunOEMTaskOnline=\"C:\\Windows\\System32\\Startupscan.SusRunOEMTaskOnline\"")
#pragma comment(linker, "/export:SusRunTask=\"C:\\Windows\\System32\\Startupscan.SusRunTask\"")
