#pragma comment(linker, "/export:CdeGetProfileList=\"C:\\Windows\\System32\\wcmsvc.CdeGetProfileList\"")
#pragma comment(linker, "/export:CdeQueryParameter=\"C:\\Windows\\System32\\wcmsvc.CdeQueryParameter\"")
#pragma comment(linker, "/export:CdeSetParameter=\"C:\\Windows\\System32\\wcmsvc.CdeSetParameter\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\wcmsvc.SvchostPushServiceGlobals\"")
#pragma comment(linker, "/export:WcmSvcMain=\"C:\\Windows\\System32\\wcmsvc.WcmSvcMain\"")
