#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wlanui.DllGetClassObject\"")
#pragma comment(linker, "/export:WLFreeProfile=\"C:\\Windows\\System32\\wlanui.WLFreeProfile\"")
#pragma comment(linker, "/export:WLFreeProfileXml=\"C:\\Windows\\System32\\wlanui.WLFreeProfileXml\"")
#pragma comment(linker, "/export:WLInvokeProfileUI=\"C:\\Windows\\System32\\wlanui.WLInvokeProfileUI\"")
#pragma comment(linker, "/export:WLInvokeProfileUIFromXMLFile=\"C:\\Windows\\System32\\wlanui.WLInvokeProfileUIFromXMLFile\"")
#pragma comment(linker, "/export:WlanUIEditProfile=\"C:\\Windows\\System32\\wlanui.WlanUIEditProfile\"")
