#pragma comment(linker, "/export:CDefFolderMenu_MergeMenu=\"C:\\Windows\\System32\\wpdshext.CDefFolderMenu_MergeMenu\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\wpdshext.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wpdshext.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\wpdshext.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\wpdshext.DllUnregisterServer\"")
