#pragma comment(linker, "/export:WpxCreateConfig=\"C:\\Windows\\System32\\wpx.WpxCreateConfig\"")
#pragma comment(linker, "/export:WpxCreateWriteOpt=\"C:\\Windows\\System32\\wpx.WpxCreateWriteOpt\"")
#pragma comment(linker, "/export:WpxGetAnswerFileType=\"C:\\Windows\\System32\\wpx.WpxGetAnswerFileType\"")
#pragma comment(linker, "/export:WpxGetDeplSettings=\"C:\\Windows\\System32\\wpx.WpxGetDeplSettings\"")
#pragma comment(linker, "/export:WpxResetDeplSettings=\"C:\\Windows\\System32\\wpx.WpxResetDeplSettings\"")
#pragma comment(linker, "/export:WpxSetDeplSettings=\"C:\\Windows\\System32\\wpx.WpxSetDeplSettings\"")
#pragma comment(linker, "/export:WpxSetLogger=\"C:\\Windows\\System32\\wpx.WpxSetLogger\"")
#pragma comment(linker, "/export:WpxSetScratchDirectory=\"C:\\Windows\\System32\\wpx.WpxSetScratchDirectory\"")
