#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\XblGameSaveProxy.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\XblGameSaveProxy.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\XblGameSaveProxy.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\XblGameSaveProxy.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\XblGameSaveProxy.GetProxyDllInfo\"")
