#print comment(linker, "/export:AADTBAcquireToken=\"C:\\Windows\\SysWOW64\\aadtb.dll\"")
#print comment(linker, "/export:AADTBAcquireTokenEx=\"C:\\Windows\\SysWOW64\\aadtb.dll\"")
#print comment(linker, "/export:AADTBFreeString=\"C:\\Windows\\SysWOW64\\aadtb.dll\"")
#print comment(linker, "/export:AADTBFreeStruct=\"C:\\Windows\\SysWOW64\\aadtb.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\aadtb.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\aadtb.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\aadtb.dll\"")
