#pragma comment(linker, "/export:AADTBAcquireToken=\"C:\\Windows\\System32\\aadtb.dll\"")
#pragma comment(linker, "/export:AADTBAcquireTokenEx=\"C:\\Windows\\System32\\aadtb.dll\"")
#pragma comment(linker, "/export:AADTBFreeString=\"C:\\Windows\\System32\\aadtb.dll\"")
#pragma comment(linker, "/export:AADTBFreeStruct=\"C:\\Windows\\System32\\aadtb.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\aadtb.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\aadtb.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\aadtb.dll\"")
