#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\acledit.dll\"")
#pragma comment(linker, "/export:EditAuditInfo=\"C:\\Windows\\System32\\acledit.dll\"")
#pragma comment(linker, "/export:EditOwnerInfo=\"C:\\Windows\\System32\\acledit.dll\"")
#pragma comment(linker, "/export:EditPermissionInfo=\"C:\\Windows\\System32\\acledit.dll\"")
#pragma comment(linker, "/export:FMExtensionProcW=\"C:\\Windows\\System32\\acledit.dll\"")
#pragma comment(linker, "/export:SedDiscretionaryAclEditor=\"C:\\Windows\\System32\\acledit.dll\"")
#pragma comment(linker, "/export:SedSystemAclEditor=\"C:\\Windows\\System32\\acledit.dll\"")
#pragma comment(linker, "/export:SedTakeOwnership=\"C:\\Windows\\System32\\acledit.dll\"")
