#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\acledit.DllMain\"")
#pragma comment(linker, "/export:EditAuditInfo=\"C:\\Windows\\System32\\acledit.EditAuditInfo\"")
#pragma comment(linker, "/export:EditOwnerInfo=\"C:\\Windows\\System32\\acledit.EditOwnerInfo\"")
#pragma comment(linker, "/export:EditPermissionInfo=\"C:\\Windows\\System32\\acledit.EditPermissionInfo\"")
#pragma comment(linker, "/export:FMExtensionProcW=\"C:\\Windows\\System32\\acledit.FMExtensionProcW\"")
#pragma comment(linker, "/export:SedDiscretionaryAclEditor=\"C:\\Windows\\System32\\acledit.SedDiscretionaryAclEditor\"")
#pragma comment(linker, "/export:SedSystemAclEditor=\"C:\\Windows\\System32\\acledit.SedSystemAclEditor\"")
#pragma comment(linker, "/export:SedTakeOwnership=\"C:\\Windows\\System32\\acledit.SedTakeOwnership\"")
