#print comment(linker, "/export:CreateSecurityPage=\"C:\\Windows\\SysWOW64\\aclui.dll\"")
#print comment(linker, "/export:EditConditionalAceClaims=\"C:\\Windows\\SysWOW64\\aclui.dll\"")
#print comment(linker, "/export:EditResourceCondition=\"C:\\Windows\\SysWOW64\\aclui.dll\"")
#print comment(linker, "/export:EditSecurity=\"C:\\Windows\\SysWOW64\\aclui.dll\"")
#print comment(linker, "/export:EditSecurityAdvanced=\"C:\\Windows\\SysWOW64\\aclui.dll\"")
#print comment(linker, "/export:GetLocalizedStringForCondition=\"C:\\Windows\\SysWOW64\\aclui.dll\"")
#print comment(linker, "/export:GetTlsIndexForClaimDictionary=\"C:\\Windows\\SysWOW64\\aclui.dll\"")
#print comment(linker, "/export:IID_ISecurityInformation=\"C:\\Windows\\SysWOW64\\aclui.dll\"")
