#pragma comment(linker, "/export:CreateSecurityPage=\"C:\\Windows\\System32\\aclui.dll\"")
#pragma comment(linker, "/export:EditConditionalAceClaims=\"C:\\Windows\\System32\\aclui.dll\"")
#pragma comment(linker, "/export:EditResourceCondition=\"C:\\Windows\\System32\\aclui.dll\"")
#pragma comment(linker, "/export:EditSecurity=\"C:\\Windows\\System32\\aclui.dll\"")
#pragma comment(linker, "/export:EditSecurityAdvanced=\"C:\\Windows\\System32\\aclui.dll\"")
#pragma comment(linker, "/export:GetLocalizedStringForCondition=\"C:\\Windows\\System32\\aclui.dll\"")
#pragma comment(linker, "/export:GetTlsIndexForClaimDictionary=\"C:\\Windows\\System32\\aclui.dll\"")
#pragma comment(linker, "/export:IID_ISecurityInformation=\"C:\\Windows\\System32\\aclui.dll\"")
