#print comment(linker, "/export:Deinitialize=\"C:\\Windows\\System32\\AppVCatalog.dll\"")
#print comment(linker, "/export:GetClientCatalog=\"C:\\Windows\\System32\\AppVCatalog.dll\"")
#print comment(linker, "/export:GetComponent=\"C:\\Windows\\System32\\AppVCatalog.dll\"")
#print comment(linker, "/export:Initialize=\"C:\\Windows\\System32\\AppVCatalog.dll\"")
#print comment(linker, "/export:InitializeISV=\"C:\\Windows\\System32\\AppVCatalog.dll\"")
