#print comment(linker, "/export:APIExportForDetours=\"C:\\Windows\\System32\\AppVEntSubsystems64.dll\"")
#print comment(linker, "/export:CurrentThreadIsVirtualized=\"C:\\Windows\\System32\\AppVEntSubsystems64.dll\"")
#print comment(linker, "/export:IsProcessHooked=\"C:\\Windows\\System32\\AppVEntSubsystems64.dll\"")
#print comment(linker, "/export:RequestUnhookedFunctionList=\"C:\\Windows\\System32\\AppVEntSubsystems64.dll\"")
#print comment(linker, "/export:VirtualizeCurrentProcess=\"C:\\Windows\\System32\\AppVEntSubsystems64.dll\"")
#print comment(linker, "/export:VirtualizeCurrentThread=\"C:\\Windows\\System32\\AppVEntSubsystems64.dll\"")
