#print comment(linker, "/export:Deinitialize=\"C:\\Windows\\System32\\AppVOrchestration.dll\"")
#print comment(linker, "/export:GetControllerComponent=\"C:\\Windows\\System32\\AppVOrchestration.dll\"")
#print comment(linker, "/export:GetControllerRequests=\"C:\\Windows\\System32\\AppVOrchestration.dll\"")
#print comment(linker, "/export:Initialize=\"C:\\Windows\\System32\\AppVOrchestration.dll\"")
#print comment(linker, "/export:InitializeISV=\"C:\\Windows\\System32\\AppVOrchestration.dll\"")
