#pragma comment(linker, "/export:APIExportForDetours=\"C:\\Windows\\System32\\AppVEntSubsystems64.APIExportForDetours\"")
#pragma comment(linker, "/export:CurrentThreadIsVirtualized=\"C:\\Windows\\System32\\AppVEntSubsystems64.CurrentThreadIsVirtualized\"")
#pragma comment(linker, "/export:IsProcessHooked=\"C:\\Windows\\System32\\AppVEntSubsystems64.IsProcessHooked\"")
#pragma comment(linker, "/export:RequestUnhookedFunctionList=\"C:\\Windows\\System32\\AppVEntSubsystems64.RequestUnhookedFunctionList\"")
#pragma comment(linker, "/export:VirtualizeCurrentProcess=\"C:\\Windows\\System32\\AppVEntSubsystems64.VirtualizeCurrentProcess\"")
#pragma comment(linker, "/export:VirtualizeCurrentThread=\"C:\\Windows\\System32\\AppVEntSubsystems64.VirtualizeCurrentThread\"")
