#pragma comment(linker, "/export:Deinitialize=\"C:\\Windows\\System32\\AppVCatalog.Deinitialize\"")
#pragma comment(linker, "/export:GetClientCatalog=\"C:\\Windows\\System32\\AppVCatalog.GetClientCatalog\"")
#pragma comment(linker, "/export:GetComponent=\"C:\\Windows\\System32\\AppVCatalog.GetComponent\"")
#pragma comment(linker, "/export:Initialize=\"C:\\Windows\\System32\\AppVCatalog.Initialize\"")
#pragma comment(linker, "/export:InitializeISV=\"C:\\Windows\\System32\\AppVCatalog.InitializeISV\"")
