#print comment(linker, "/export:CreateSerializedBundleManifestStatement=\"C:\\Windows\\System32\\AppXApplicabilityBlob.dll\"")
#print comment(linker, "/export:GetApplicabilityFactory=\"C:\\Windows\\System32\\AppXApplicabilityBlob.dll\"")
#print comment(linker, "/export:IsAppx=\"C:\\Windows\\System32\\AppXApplicabilityBlob.dll\"")
#print comment(linker, "/export:IsModernApp=\"C:\\Windows\\System32\\AppXApplicabilityBlob.dll\"")
#print comment(linker, "/export:IsPreThresholdDesktop=\"C:\\Windows\\System32\\AppXApplicabilityBlob.dll\"")
#print comment(linker, "/export:IsPreThresholdPhone=\"C:\\Windows\\System32\\AppXApplicabilityBlob.dll\"")
#print comment(linker, "/export:IsXAP=\"C:\\Windows\\System32\\AppXApplicabilityBlob.dll\"")
