#pragma comment(linker, "/export:AERT_Allocate=\"C:\\Windows\\System32\\AudioEng.dll\"")
#pragma comment(linker, "/export:AERT_Free=\"C:\\Windows\\System32\\AudioEng.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\AudioEng.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\AudioEng.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\AudioEng.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\AudioEng.dll\"")
