#print comment(linker, "/export:AERT_Allocate=\"C:\\Windows\\SysWOW64\\AudioEng.dll\"")
#print comment(linker, "/export:AERT_Free=\"C:\\Windows\\SysWOW64\\AudioEng.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\AudioEng.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\AudioEng.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\AudioEng.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\AudioEng.dll\"")
