#pragma comment(linker, "/export:AuthzGetAccountType=\"C:\\Windows\\System32\\authentication.dll\"")
#pragma comment(linker, "/export:AuthzRequestTicketWithWindow=\"C:\\Windows\\System32\\authentication.dll\"")
#pragma comment(linker, "/export:AuthzRequestTicketWithoutWindow=\"C:\\Windows\\System32\\authentication.dll\"")
#pragma comment(linker, "/export:GetAccountType=\"C:\\Windows\\System32\\authentication.dll\"")
#pragma comment(linker, "/export:RequestTicketWithWindow=\"C:\\Windows\\System32\\authentication.dll\"")
#pragma comment(linker, "/export:RequestTicketWithoutWindow=\"C:\\Windows\\System32\\authentication.dll\"")
