#print comment(linker, "/export:AzGenerateAudit=\"C:\\Windows\\SysWOW64\\AzSqlExt.dll\"")
#print comment(linker, "/export:__GetXpVersion=\"C:\\Windows\\SysWOW64\\AzSqlExt.dll\"")
#print comment(linker, "/export:xp_AzManAddRole=\"C:\\Windows\\SysWOW64\\AzSqlExt.dll\"")
#print comment(linker, "/export:xp_AzManAddUserToRole=\"C:\\Windows\\SysWOW64\\AzSqlExt.dll\"")
#print comment(linker, "/export:xp_AzManDeleteRole=\"C:\\Windows\\SysWOW64\\AzSqlExt.dll\"")
#print comment(linker, "/export:xp_AzManRemoveUserFromRole=\"C:\\Windows\\SysWOW64\\AzSqlExt.dll\"")
