#pragma comment(linker, "/export:BamCreateSettingsClientLib=\"C:\\Windows\\System32\\BamSettingsClient.dll\"")
#pragma comment(linker, "/export:BamDestroySettingsClientLib=\"C:\\Windows\\System32\\BamSettingsClient.dll\"")
#pragma comment(linker, "/export:BamFreeQueriedApplications=\"C:\\Windows\\System32\\BamSettingsClient.dll\"")
#pragma comment(linker, "/export:BamQueryKnownApplications=\"C:\\Windows\\System32\\BamSettingsClient.dll\"")
#pragma comment(linker, "/export:BamSetUserManagementState=\"C:\\Windows\\System32\\BamSettingsClient.dll\"")
