#pragma comment(linker, "/export:BaseGetProcessCrtlRoutine=\"C:\\Windows\\System32\\basesrv.dll\"")
#pragma comment(linker, "/export:BaseSetProcessCreateNotify=\"C:\\Windows\\System32\\basesrv.dll\"")
#pragma comment(linker, "/export:BaseSrvNlsLogon=\"C:\\Windows\\System32\\basesrv.dll\"")
#pragma comment(linker, "/export:BaseSrvNlsUpdateRegistryCache=\"C:\\Windows\\System32\\basesrv.dll\"")
#pragma comment(linker, "/export:BaseSrvRegisterSxS=\"C:\\Windows\\System32\\basesrv.dll\"")
#pragma comment(linker, "/export:ServerDllInitialization=\"C:\\Windows\\System32\\basesrv.dll\"")
