#print comment(linker, "/export:PsmBiExtInitialize=\"C:\\Windows\\System32\\bisrv.dll\"")
#print comment(linker, "/export:PsmBiExtNotifyAppState=\"C:\\Windows\\System32\\bisrv.dll\"")
#print comment(linker, "/export:PsmBiExtNotifySessionStateChange=\"C:\\Windows\\System32\\bisrv.dll\"")
#print comment(linker, "/export:PsmBiExtNotifySessionUserStateChange=\"C:\\Windows\\System32\\bisrv.dll\"")
#print comment(linker, "/export:PsmBiExtNotifyWerReportProgress=\"C:\\Windows\\System32\\bisrv.dll\"")
#print comment(linker, "/export:PsmBiExtPrepareToSuspendPackage=\"C:\\Windows\\System32\\bisrv.dll\"")
#print comment(linker, "/export:PsmBiExtResumePackage=\"C:\\Windows\\System32\\bisrv.dll\"")
