#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\blb_ps.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\blb_ps.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\blb_ps.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\blb_ps.dll\"")
#print comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\blb_ps.dll\"")
