#print comment(linker, "/export:BthCollectFingerprintInfo=\"C:\\Windows\\System32\\BthTelemetry.dll\"")
#print comment(linker, "/export:BthProcessEventDataDword=\"C:\\Windows\\System32\\BthTelemetry.dll\"")
#print comment(linker, "/export:BthProcessEventOccurrence=\"C:\\Windows\\System32\\BthTelemetry.dll\"")
#print comment(linker, "/export:BthProcessEventOccurrenceBthaddr=\"C:\\Windows\\System32\\BthTelemetry.dll\"")
#print comment(linker, "/export:BthProcessEventOccurrenceResult=\"C:\\Windows\\System32\\BthTelemetry.dll\"")
#print comment(linker, "/export:BthProcessEventOccurrenceResultBthaddr=\"C:\\Windows\\System32\\BthTelemetry.dll\"")
#print comment(linker, "/export:BthProcessRpalEventOccurrence=\"C:\\Windows\\System32\\BthTelemetry.dll\"")
