#print comment(linker, "/export:CAPISysPrep_Generalize=\"C:\\Windows\\System32\\capisp.dll\"")
#print comment(linker, "/export:CryptoSysPrep_Clean=\"C:\\Windows\\System32\\capisp.dll\"")
#print comment(linker, "/export:CryptoSysPrep_Specialize=\"C:\\Windows\\System32\\capisp.dll\"")
#print comment(linker, "/export:CryptoSysPrep_Specialize_Clone=\"C:\\Windows\\System32\\capisp.dll\"")
#print comment(linker, "/export:CryptoSysPrep_Specialize_Offline=\"C:\\Windows\\System32\\capisp.dll\"")
