#pragma comment(linker, "/export:CreateViewObjectForContentDirectoryFolder=\"C:\\Windows\\System32\\CastingShellExt.CreateViewObjectForContentDirectoryFolder\"")
#pragma comment(linker, "/export:CreateViewObjectForMediaServerFolder=\"C:\\Windows\\System32\\CastingShellExt.CreateViewObjectForMediaServerFolder\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\CastingShellExt.DllMain\"")
#pragma comment(linker, "/export:GetContextMenuForContentDirectoryFolder=\"C:\\Windows\\System32\\CastingShellExt.GetContextMenuForContentDirectoryFolder\"")
#pragma comment(linker, "/export:GetContextMenuForMediaServerFolder=\"C:\\Windows\\System32\\CastingShellExt.GetContextMenuForMediaServerFolder\"")
#pragma comment(linker, "/export:GetExtractIconForContentDirectoryFolder=\"C:\\Windows\\System32\\CastingShellExt.GetExtractIconForContentDirectoryFolder\"")
#pragma comment(linker, "/export:GetExtractIconForMediaServerFolder=\"C:\\Windows\\System32\\CastingShellExt.GetExtractIconForMediaServerFolder\"")
