#print comment(linker, "/export:CreateViewObjectForContentDirectoryFolder=\"C:\\Windows\\System32\\CastingShellExt.dll\"")
#print comment(linker, "/export:CreateViewObjectForMediaServerFolder=\"C:\\Windows\\System32\\CastingShellExt.dll\"")
#print comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\CastingShellExt.dll\"")
#print comment(linker, "/export:GetContextMenuForContentDirectoryFolder=\"C:\\Windows\\System32\\CastingShellExt.dll\"")
#print comment(linker, "/export:GetContextMenuForMediaServerFolder=\"C:\\Windows\\System32\\CastingShellExt.dll\"")
#print comment(linker, "/export:GetExtractIconForContentDirectoryFolder=\"C:\\Windows\\System32\\CastingShellExt.dll\"")
#print comment(linker, "/export:GetExtractIconForMediaServerFolder=\"C:\\Windows\\System32\\CastingShellExt.dll\"")
