#pragma comment(linker, "/export:CLSID_CfgComp=\"C:\\Windows\\System32\\cfgbkend.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\cfgbkend.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\cfgbkend.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\cfgbkend.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\cfgbkend.dll\"")
#pragma comment(linker, "/export:IID_ICfgComp=\"C:\\Windows\\System32\\cfgbkend.dll\"")
#pragma comment(linker, "/export:IID_ISettingsComp=\"C:\\Windows\\System32\\cfgbkend.dll\"")
#pragma comment(linker, "/export:IID_ISettingsComp2=\"C:\\Windows\\System32\\cfgbkend.dll\"")
