#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Chakradiag.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Chakradiag.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\Chakradiag.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\Chakradiag.dll\"")
#print comment(linker, "/export:FreeDumpStreams=\"C:\\Windows\\System32\\Chakradiag.dll\"")
#print comment(linker, "/export:GetDumpStreams=\"C:\\Windows\\System32\\Chakradiag.dll\"")
