#print comment(linker, "/export:CvCloseDataSource=\"C:\\Windows\\System32\\chartv.dll\"")
#print comment(linker, "/export:CvCreateDataSource=\"C:\\Windows\\System32\\chartv.dll\"")
#print comment(linker, "/export:CvGetData=\"C:\\Windows\\System32\\chartv.dll\"")
#print comment(linker, "/export:CvGetDataSourceName=\"C:\\Windows\\System32\\chartv.dll\"")
#print comment(linker, "/export:CvInitialize=\"C:\\Windows\\System32\\chartv.dll\"")
#print comment(linker, "/export:CvSetData=\"C:\\Windows\\System32\\chartv.dll\"")
#print comment(linker, "/export:CvSetDataSourceName=\"C:\\Windows\\System32\\chartv.dll\"")
#print comment(linker, "/export:CvUninitialize=\"C:\\Windows\\System32\\chartv.dll\"")
