#print comment(linker, "/export:ClbAddData=\"C:\\Windows\\System32\\clb.dll\"")
#print comment(linker, "/export:ClbSetColumnWidths=\"C:\\Windows\\System32\\clb.dll\"")
#print comment(linker, "/export:ClbStyleW=\"C:\\Windows\\System32\\clb.dll\"")
#print comment(linker, "/export:ClbWndProc=\"C:\\Windows\\System32\\clb.dll\"")
#print comment(linker, "/export:CustomControlInfoW=\"C:\\Windows\\System32\\clb.dll\"")
