#print comment(linker, "/export:DllAddRef=\"C:\\Windows\\System32\\cmstplua.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\cmstplua.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\cmstplua.dll\"")
#print comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\cmstplua.dll\"")
#print comment(linker, "/export:DllRelease=\"C:\\Windows\\System32\\cmstplua.dll\"")
