#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\colbact.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\colbact.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\colbact.dll\"")
#print comment(linker, "/export:GetClassInfoForCurrentUser=\"C:\\Windows\\System32\\colbact.dll\"")
#print comment(linker, "/export:GetDefaultPartitionForCurrentUser=\"C:\\Windows\\System32\\colbact.dll\"")
#print comment(linker, "/export:GetDefaultPartitionForSid=\"C:\\Windows\\System32\\colbact.dll\"")
#print comment(linker, "/export:PartitionAccessCheck=\"C:\\Windows\\System32\\colbact.dll\"")
