#print comment(linker, "/export:ModernColorGetGDILutFromHDC=\"C:\\Windows\\System32\\coloradapterclient.dll\"")
#print comment(linker, "/export:ModernColorSetGDILut=\"C:\\Windows\\System32\\coloradapterclient.dll\"")
#print comment(linker, "/export:ModernColorSetGDILutFromHDC=\"C:\\Windows\\System32\\coloradapterclient.dll\"")
#print comment(linker, "/export:ModernColorSetLut=\"C:\\Windows\\System32\\coloradapterclient.dll\"")
#print comment(linker, "/export:ModernColorSetMatrix=\"C:\\Windows\\System32\\coloradapterclient.dll\"")
#print comment(linker, "/export:ModernColorSetMatrixFromHDC=\"C:\\Windows\\System32\\coloradapterclient.dll\"")
