#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\colorui.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\colorui.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\colorui.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\colorui.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\colorui.DllUnregisterServer\"")
#pragma comment(linker, "/export:LaunchColorCpl=\"C:\\Windows\\System32\\colorui.LaunchColorCpl\"")
