#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\colorui.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\colorui.dll\"")
#print comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\colorui.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\colorui.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\colorui.dll\"")
#print comment(linker, "/export:LaunchColorCpl=\"C:\\Windows\\System32\\colorui.dll\"")
