#pragma comment(linker, "/export:AwaitContactPickerResults=\"C:\\Windows\\System32\\ContactActivation.AwaitContactPickerResults\"")
#pragma comment(linker, "/export:ContactToVCardString=\"C:\\Windows\\System32\\ContactActivation.ContactToVCardString\"")
#pragma comment(linker, "/export:DeserializeContactFromString=\"C:\\Windows\\System32\\ContactActivation.DeserializeContactFromString\"")
#pragma comment(linker, "/export:SerializeContactToString=\"C:\\Windows\\System32\\ContactActivation.SerializeContactToString\"")
#pragma comment(linker, "/export:SerializeContactToVCard=\"C:\\Windows\\System32\\ContactActivation.SerializeContactToVCard\"")
#pragma comment(linker, "/export:ShowContactPickerAsync=\"C:\\Windows\\System32\\ContactActivation.ShowContactPickerAsync\"")
#pragma comment(linker, "/export:VCardStringToContact=\"C:\\Windows\\System32\\ContactActivation.VCardStringToContact\"")
