#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\CPFilters.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\CPFilters.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\CPFilters.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\CPFilters.dll\"")
#pragma comment(linker, "/export:UpdatePlayready=\"C:\\Windows\\System32\\CPFilters.dll\"")
