#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\CPFilters.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\CPFilters.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\CPFilters.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\CPFilters.DllUnregisterServer\"")
#pragma comment(linker, "/export:UpdatePlayready=\"C:\\Windows\\System32\\CPFilters.UpdatePlayready\"")
