#pragma comment(linker, "/export:CryptUIWizBuildCTL=\"C:\\Windows\\System32\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:CryptUIWizDigitalSign=\"C:\\Windows\\System32\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:CryptUIWizExport=\"C:\\Windows\\System32\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:CryptUIWizFreeDigitalSignContext=\"C:\\Windows\\System32\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:CryptUIWizImport=\"C:\\Windows\\System32\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:CryptUIWizImportInternal=\"C:\\Windows\\System32\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\cryptuiwizard.dll\"")
#pragma comment(linker, "/export:GetFunctionTable=\"C:\\Windows\\System32\\cryptuiwizard.dll\"")
