#print comment(linker, "/export:CscNetApiGetInterface=\"C:\\Windows\\System32\\cscapi.dll\"")
#print comment(linker, "/export:CscSearchApiGetInterface=\"C:\\Windows\\System32\\cscapi.dll\"")
#print comment(linker, "/export:OfflineFilesEnable=\"C:\\Windows\\System32\\cscapi.dll\"")
#print comment(linker, "/export:OfflineFilesGetShareCachingMode=\"C:\\Windows\\System32\\cscapi.dll\"")
#print comment(linker, "/export:OfflineFilesQueryStatus=\"C:\\Windows\\System32\\cscapi.dll\"")
#print comment(linker, "/export:OfflineFilesQueryStatusEx=\"C:\\Windows\\System32\\cscapi.dll\"")
#print comment(linker, "/export:OfflineFilesStart=\"C:\\Windows\\System32\\cscapi.dll\"")
