#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\cscobj.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\cscobj.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\cscobj.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\cscobj.dll\"")
#pragma comment(linker, "/export:ProcessGroupPolicy=\"C:\\Windows\\System32\\cscobj.dll\"")
#pragma comment(linker, "/export:ProcessPolicy=\"C:\\Windows\\System32\\cscobj.dll\"")
