#pragma comment(linker, "/export:CSebCreateCustomEvent=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.CSebCreateCustomEvent\"")
#pragma comment(linker, "/export:CSebCreatePrivateEvent=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.CSebCreatePrivateEvent\"")
#pragma comment(linker, "/export:CSebCreateWellKnownEvent=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.CSebCreateWellKnownEvent\"")
#pragma comment(linker, "/export:CSebDeleteEvent=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.CSebDeleteEvent\"")
#pragma comment(linker, "/export:CSebEnumerateEvents=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.CSebEnumerateEvents\"")
#pragma comment(linker, "/export:CSebQueryEventData=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.CSebQueryEventData\"")
