#pragma comment(linker, "/export:CSebCreateCustomEvent=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.dll\"")
#pragma comment(linker, "/export:CSebCreatePrivateEvent=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.dll\"")
#pragma comment(linker, "/export:CSebCreateWellKnownEvent=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.dll\"")
#pragma comment(linker, "/export:CSebDeleteEvent=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.dll\"")
#pragma comment(linker, "/export:CSebEnumerateEvents=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.dll\"")
#pragma comment(linker, "/export:CSebQueryEventData=\"C:\\Windows\\System32\\CSystemEventsBrokerClient.dll\"")
