#print comment(linker, "/export:DebugSetMute=\"C:\\Windows\\SysWOW64\\d3d8.dll\"")
#print comment(linker, "/export:Direct3D8EnableMaximizedWindowedModeShim=\"C:\\Windows\\SysWOW64\\d3d8.dll\"")
#print comment(linker, "/export:Direct3DCreate8=\"C:\\Windows\\SysWOW64\\d3d8.dll\"")
#print comment(linker, "/export:ValidatePixelShader=\"C:\\Windows\\SysWOW64\\d3d8.dll\"")
#print comment(linker, "/export:ValidateVertexShader=\"C:\\Windows\\SysWOW64\\d3d8.dll\"")
