#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\DavSyncProvider.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\DavSyncProvider.dll\"")
#print comment(linker, "/export:ForceCalDavCollectionsListRefreshDuringNextSync=\"C:\\Windows\\System32\\DavSyncProvider.dll\"")
#print comment(linker, "/export:HandleWebDavMeetingResponseForAppointment=\"C:\\Windows\\System32\\DavSyncProvider.dll\"")
#print comment(linker, "/export:HandleWebDavMeetingResponseForMeetingNotification=\"C:\\Windows\\System32\\DavSyncProvider.dll\"")
#print comment(linker, "/export:UpdateCalDavTrackingSchema=\"C:\\Windows\\System32\\DavSyncProvider.dll\"")
#print comment(linker, "/export:UpdateGMailContactSyncPartner=\"C:\\Windows\\System32\\DavSyncProvider.dll\"")
