#pragma comment(linker, "/export:GetCensusPropertyAlloc=\"C:\\Windows\\System32\\dcntel.GetCensusPropertyAlloc\"")
#pragma comment(linker, "/export:GetCensusRegistryLocation=\"C:\\Windows\\System32\\dcntel.GetCensusRegistryLocation\"")
#pragma comment(linker, "/export:RunSystemContextCensus=\"C:\\Windows\\System32\\dcntel.RunSystemContextCensus\"")
#pragma comment(linker, "/export:RunUserContextCensus=\"C:\\Windows\\System32\\dcntel.RunUserContextCensus\"")
#pragma comment(linker, "/export:SetCustomTrigger=\"C:\\Windows\\System32\\dcntel.SetCustomTrigger\"")
#pragma comment(linker, "/export:SetCustomTriggerEx=\"C:\\Windows\\System32\\dcntel.SetCustomTriggerEx\"")
#pragma comment(linker, "/export:SysprepCleanupEnableCustomTrigger=\"C:\\Windows\\System32\\dcntel.SysprepCleanupEnableCustomTrigger\"")
