#pragma comment(linker, "/export:GetCensusPropertyAlloc=\"C:\\Windows\\System32\\dcntel.dll\"")
#pragma comment(linker, "/export:GetCensusRegistryLocation=\"C:\\Windows\\System32\\dcntel.dll\"")
#pragma comment(linker, "/export:RunSystemContextCensus=\"C:\\Windows\\System32\\dcntel.dll\"")
#pragma comment(linker, "/export:RunUserContextCensus=\"C:\\Windows\\System32\\dcntel.dll\"")
#pragma comment(linker, "/export:SetCustomTrigger=\"C:\\Windows\\System32\\dcntel.dll\"")
#pragma comment(linker, "/export:SetCustomTriggerEx=\"C:\\Windows\\System32\\dcntel.dll\"")
#pragma comment(linker, "/export:SysprepCleanupEnableCustomTrigger=\"C:\\Windows\\System32\\dcntel.dll\"")
