#pragma comment(linker, "/export:AntiTheftAckProtectionEnabled=\"C:\\Windows\\System32\\DdcAntiTheftApi.AntiTheftAckProtectionEnabled\"")
#pragma comment(linker, "/export:AntiTheftCheckProtectionStatus=\"C:\\Windows\\System32\\DdcAntiTheftApi.AntiTheftCheckProtectionStatus\"")
#pragma comment(linker, "/export:AntiTheftProtectDevice=\"C:\\Windows\\System32\\DdcAntiTheftApi.AntiTheftProtectDevice\"")
#pragma comment(linker, "/export:AntiTheftUnprotectDevice=\"C:\\Windows\\System32\\DdcAntiTheftApi.AntiTheftUnprotectDevice\"")
#pragma comment(linker, "/export:AntiTheftUnprotectDeviceFromOOBE=\"C:\\Windows\\System32\\DdcAntiTheftApi.AntiTheftUnprotectDeviceFromOOBE\"")
