#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\defragsvc.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\defragsvc.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\defragsvc.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\defragsvc.dll\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\defragsvc.dll\"")
