#pragma comment(linker, "/export:CreateDeviceInventory=\"C:\\Windows\\System32\\devinv.dll\"")
#pragma comment(linker, "/export:CreateDeviceInventoryTC=\"C:\\Windows\\System32\\devinv.dll\"")
#pragma comment(linker, "/export:CreateDeviceInventoryTC2=\"C:\\Windows\\System32\\devinv.dll\"")
#pragma comment(linker, "/export:GetDevInventory=\"C:\\Windows\\System32\\devinv.dll\"")
#pragma comment(linker, "/export:ReportDeviceAdd=\"C:\\Windows\\System32\\devinv.dll\"")
#pragma comment(linker, "/export:ReportDeviceRemove=\"C:\\Windows\\System32\\devinv.dll\"")
#pragma comment(linker, "/export:RunDeviceInventoryW=\"C:\\Windows\\System32\\devinv.dll\"")
#pragma comment(linker, "/export:SetDevInvDebugCorrelationVector=\"C:\\Windows\\System32\\devinv.dll\"")
