#pragma comment(linker, "/export:DirectInput8Create=\"C:\\Windows\\System32\\dinput8.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\dinput8.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\dinput8.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\dinput8.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\dinput8.dll\"")
#pragma comment(linker, "/export:GetdfDIJoystick=\"C:\\Windows\\System32\\dinput8.dll\"")
