#print comment(linker, "/export:DirectInputCreateA=\"C:\\Windows\\System32\\dinput.dll\"")
#print comment(linker, "/export:DirectInputCreateEx=\"C:\\Windows\\System32\\dinput.dll\"")
#print comment(linker, "/export:DirectInputCreateW=\"C:\\Windows\\System32\\dinput.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\dinput.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\dinput.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\dinput.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\dinput.dll\"")
