#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\DispBroker.Desktop.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\DispBroker.Desktop.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\DispBroker.Desktop.DllGetClassObject\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\DispBroker.Desktop.ServiceMain\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\DispBroker.Desktop.SvchostPushServiceGlobals\"")
