#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\DispBroker.Desktop.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\DispBroker.Desktop.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\DispBroker.Desktop.dll\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\DispBroker.Desktop.dll\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\DispBroker.Desktop.dll\"")
