#print comment(linker, "/export:DispBrokerTraceLogCallback=\"C:\\Windows\\System32\\DispBroker.dll\"")
#print comment(linker, "/export:DispBrokerTraceLogHelper=\"C:\\Windows\\System32\\DispBroker.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\DispBroker.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\DispBroker.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\DispBroker.dll\"")
