#pragma comment(linker, "/export:CollectDiagnosticsAutoLog=\"C:\\Windows\\System32\\dmenterprisediagnostics.dll\"")
#pragma comment(linker, "/export:GatherAutoLogEventsFromMobile=\"C:\\Windows\\System32\\dmenterprisediagnostics.dll\"")
#pragma comment(linker, "/export:RecordDiagnosticsError=\"C:\\Windows\\System32\\dmenterprisediagnostics.dll\"")
#pragma comment(linker, "/export:SetupAutoLog=\"C:\\Windows\\System32\\dmenterprisediagnostics.dll\"")
#pragma comment(linker, "/export:SetupAutoLogWithTraceLevel=\"C:\\Windows\\System32\\dmenterprisediagnostics.dll\"")
#pragma comment(linker, "/export:StartAutoLog=\"C:\\Windows\\System32\\dmenterprisediagnostics.dll\"")
#pragma comment(linker, "/export:StopAutoLog=\"C:\\Windows\\System32\\dmenterprisediagnostics.dll\"")
#pragma comment(linker, "/export:TearDownAutoLog=\"C:\\Windows\\System32\\dmenterprisediagnostics.dll\"")
