#print comment(linker, "/export:PushRouter_Close=\"C:\\Windows\\System32\\dmpushproxy.dll\"")
#print comment(linker, "/export:PushRouter_FreeGetMessageEventName=\"C:\\Windows\\System32\\dmpushproxy.dll\"")
#print comment(linker, "/export:PushRouter_FreeMessage=\"C:\\Windows\\System32\\dmpushproxy.dll\"")
#print comment(linker, "/export:PushRouter_FreeMessageEx=\"C:\\Windows\\System32\\dmpushproxy.dll\"")
#print comment(linker, "/export:PushRouter_GetMessage=\"C:\\Windows\\System32\\dmpushproxy.dll\"")
#print comment(linker, "/export:PushRouter_GetMessageEx=\"C:\\Windows\\System32\\dmpushproxy.dll\"")
#print comment(linker, "/export:PushRouter_Open=\"C:\\Windows\\System32\\dmpushproxy.dll\"")
#print comment(linker, "/export:PushRouter_SubmitPush=\"C:\\Windows\\System32\\dmpushproxy.dll\"")
