#pragma comment(linker, "/export:DOProcessGroupPolicy=\"C:\\Windows\\System32\\domgmt.DOProcessGroupPolicy\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\domgmt.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\domgmt.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\domgmt.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\domgmt.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\domgmt.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProviderClassID=\"C:\\Windows\\System32\\domgmt.GetProviderClassID\"")
#pragma comment(linker, "/export:MI_Main=\"C:\\Windows\\System32\\domgmt.MI_Main\"")
