#print comment(linker, "/export:DOProcessGroupPolicy=\"C:\\Windows\\System32\\domgmt.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\domgmt.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\domgmt.dll\"")
#print comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\domgmt.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\domgmt.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\domgmt.dll\"")
#print comment(linker, "/export:GetProviderClassID=\"C:\\Windows\\System32\\domgmt.dll\"")
#print comment(linker, "/export:MI_Main=\"C:\\Windows\\System32\\domgmt.dll\"")
