#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\dot3dlg.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\dot3dlg.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\dot3dlg.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\dot3dlg.dll\"")
#pragma comment(linker, "/export:Dot3ACCanShowBalloon=\"C:\\Windows\\System32\\dot3dlg.dll\"")
#pragma comment(linker, "/export:Dot3ACOnBalloonClick=\"C:\\Windows\\System32\\dot3dlg.dll\"")
