#print comment(linker, "/export:CryptProtectDataNoUI=\"C:\\Windows\\SysWOW64\\dpapi.dll\"")
#print comment(linker, "/export:CryptProtectMemory=\"C:\\Windows\\SysWOW64\\dpapi.dll\"")
#print comment(linker, "/export:CryptResetMachineCredentials=\"C:\\Windows\\SysWOW64\\dpapi.dll\"")
#print comment(linker, "/export:CryptUnprotectDataNoUI=\"C:\\Windows\\SysWOW64\\dpapi.dll\"")
#print comment(linker, "/export:CryptUnprotectMemory=\"C:\\Windows\\SysWOW64\\dpapi.dll\"")
#print comment(linker, "/export:CryptUpdateProtectedState=\"C:\\Windows\\SysWOW64\\dpapi.dll\"")
#print comment(linker, "/export:iCryptIdentifyProtection=\"C:\\Windows\\SysWOW64\\dpapi.dll\"")
