#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\DscTimer.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\DscTimer.dll\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\DscTimer.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\DscTimer.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\DscTimer.dll\"")
#pragma comment(linker, "/export:GetProviderClassID=\"C:\\Windows\\System32\\DscTimer.dll\"")
#pragma comment(linker, "/export:MI_Main=\"C:\\Windows\\System32\\DscTimer.dll\"")
