#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\dsquery.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\dsquery.dll\"")
#print comment(linker, "/export:DllInstall=\"C:\\Windows\\System32\\dsquery.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\dsquery.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\dsquery.dll\"")
#print comment(linker, "/export:OpenQueryWindow=\"C:\\Windows\\System32\\dsquery.dll\"")
#print comment(linker, "/export:OpenSavedDsQuery=\"C:\\Windows\\System32\\dsquery.dll\"")
#print comment(linker, "/export:OpenSavedDsQueryW=\"C:\\Windows\\System32\\dsquery.dll\"")
