#pragma comment(linker, "/export:DSCreateISecurityInfoObject=\"C:\\Windows\\System32\\dssec.dll\"")
#pragma comment(linker, "/export:DSCreateISecurityInfoObjectEx=\"C:\\Windows\\System32\\dssec.dll\"")
#pragma comment(linker, "/export:DSCreateSecurityPage=\"C:\\Windows\\System32\\dssec.dll\"")
#pragma comment(linker, "/export:DSEditSecurity=\"C:\\Windows\\System32\\dssec.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\dssec.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\dssec.dll\"")
