#pragma comment(linker, "/export:DSSCreateSharedFileTokenEx=\"C:\\Windows\\System32\\dssvc.dll\"")
#pragma comment(linker, "/export:DSSFreeToken=\"C:\\Windows\\System32\\dssvc.dll\"")
#pragma comment(linker, "/export:InitializeService=\"C:\\Windows\\System32\\dssvc.dll\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\dssvc.dll\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\dssvc.dll\"")
