#print comment(linker, "/export:MilCompositionEngine_GetComposedEventId=\"C:\\Windows\\System32\\dwmcore.dll\"")
#print comment(linker, "/export:MilCompositionEngine_Initialize=\"C:\\Windows\\System32\\dwmcore.dll\"")
#print comment(linker, "/export:MilCompositionEngine_Uninitialize=\"C:\\Windows\\System32\\dwmcore.dll\"")
#print comment(linker, "/export:MilConnection_CreateChannel=\"C:\\Windows\\System32\\dwmcore.dll\"")
#print comment(linker, "/export:MilTransport_AddRef=\"C:\\Windows\\System32\\dwmcore.dll\"")
#print comment(linker, "/export:MilTransport_Release=\"C:\\Windows\\System32\\dwmcore.dll\"")
