#pragma comment(linker, "/export:DwmInitializeEngine=\"C:\\Windows\\System32\\dwmredir.dll\"")
#pragma comment(linker, "/export:DwmInitializePort=\"C:\\Windows\\System32\\dwmredir.dll\"")
#pragma comment(linker, "/export:DwmRedirectionManagerInitialize=\"C:\\Windows\\System32\\dwmredir.dll\"")
#pragma comment(linker, "/export:DwmRedirectionManagerShutdown=\"C:\\Windows\\System32\\dwmredir.dll\"")
#pragma comment(linker, "/export:DwmRenderDesktopForDDA=\"C:\\Windows\\System32\\dwmredir.dll\"")
#pragma comment(linker, "/export:DwmShutdownEngine=\"C:\\Windows\\System32\\dwmredir.dll\"")
#pragma comment(linker, "/export:DwmVersionCheck=\"C:\\Windows\\System32\\dwmredir.dll\"")
