#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\dxtmsft.dll\"")
#pragma comment(linker, "/export:DllEnumClassObjects=\"C:\\Windows\\System32\\dxtmsft.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\dxtmsft.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\dxtmsft.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\dxtmsft.dll\"")
