#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\eapphost.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\eapphost.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\eapphost.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\eapphost.DllUnregisterServer\"")
#pragma comment(linker, "/export:InitializeEapHost=\"C:\\Windows\\System32\\eapphost.InitializeEapHost\"")
#pragma comment(linker, "/export:OnSessionChange=\"C:\\Windows\\System32\\eapphost.OnSessionChange\"")
#pragma comment(linker, "/export:StopServiceOnLowPower=\"C:\\Windows\\System32\\eapphost.StopServiceOnLowPower\"")
#pragma comment(linker, "/export:UninitializeEapHost=\"C:\\Windows\\System32\\eapphost.UninitializeEapHost\"")
