#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\eapputil.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\eapputil.dll\"")
#print comment(linker, "/export:EapConvertHostToWireFormat16=\"C:\\Windows\\System32\\eapputil.dll\"")
#print comment(linker, "/export:EapConvertHostToWireFormat24=\"C:\\Windows\\System32\\eapputil.dll\"")
#print comment(linker, "/export:EapConvertHostToWireFormat32=\"C:\\Windows\\System32\\eapputil.dll\"")
#print comment(linker, "/export:EapConvertWireToHostFormat16=\"C:\\Windows\\System32\\eapputil.dll\"")
#print comment(linker, "/export:EapConvertWireToHostFormat24=\"C:\\Windows\\System32\\eapputil.dll\"")
#print comment(linker, "/export:EapConvertWireToHostFormat32=\"C:\\Windows\\System32\\eapputil.dll\"")
