#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\eapsimextdesktop.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\eapsimextdesktop.dll\"")
#pragma comment(linker, "/export:EapSimExtCallRunWizard=\"C:\\Windows\\System32\\eapsimextdesktop.dll\"")
#pragma comment(linker, "/export:EapSimExtGetIdentityPageGuid=\"C:\\Windows\\System32\\eapsimextdesktop.dll\"")
#pragma comment(linker, "/export:EapSimExtInvokeUIAndGetConfig=\"C:\\Windows\\System32\\eapsimextdesktop.dll\"")
