#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\EdgeContent.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\EdgeContent.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\EdgeContent.dll\"")
#pragma comment(linker, "/export:IEGetWriteableFolderPath=\"C:\\Windows\\System32\\EdgeContent.dll\"")
#pragma comment(linker, "/export:IEIsInPrivateBrowsing=\"C:\\Windows\\System32\\EdgeContent.dll\"")
#pragma comment(linker, "/export:IEIsProtectedModeProcess=\"C:\\Windows\\System32\\EdgeContent.dll\"")
#pragma comment(linker, "/export:IERefreshElevationPolicy=\"C:\\Windows\\System32\\EdgeContent.dll\"")
