#print comment(linker, "/export:MappingDoAction=\"C:\\Windows\\System32\\ELSCore.dll\"")
#print comment(linker, "/export:MappingFreePropertyBag=\"C:\\Windows\\System32\\ELSCore.dll\"")
#print comment(linker, "/export:MappingFreeServices=\"C:\\Windows\\System32\\ELSCore.dll\"")
#print comment(linker, "/export:MappingGetServices=\"C:\\Windows\\System32\\ELSCore.dll\"")
#print comment(linker, "/export:MappingRecognizeText=\"C:\\Windows\\System32\\ELSCore.dll\"")
