#print comment(linker, "/export:DoAction=\"C:\\Windows\\System32\\elsTrans.dll\"")
#print comment(linker, "/export:EnumServices=\"C:\\Windows\\System32\\elsTrans.dll\"")
#print comment(linker, "/export:FreePropertyBag=\"C:\\Windows\\System32\\elsTrans.dll\"")
#print comment(linker, "/export:FreeService=\"C:\\Windows\\System32\\elsTrans.dll\"")
#print comment(linker, "/export:InitService=\"C:\\Windows\\System32\\elsTrans.dll\"")
#print comment(linker, "/export:RecognizeText=\"C:\\Windows\\System32\\elsTrans.dll\"")
