#pragma comment(linker, "/export:DoAction=\"C:\\Windows\\System32\\elsTrans.DoAction\"")
#pragma comment(linker, "/export:EnumServices=\"C:\\Windows\\System32\\elsTrans.EnumServices\"")
#pragma comment(linker, "/export:FreePropertyBag=\"C:\\Windows\\System32\\elsTrans.FreePropertyBag\"")
#pragma comment(linker, "/export:FreeService=\"C:\\Windows\\System32\\elsTrans.FreeService\"")
#pragma comment(linker, "/export:InitService=\"C:\\Windows\\System32\\elsTrans.InitService\"")
#pragma comment(linker, "/export:RecognizeText=\"C:\\Windows\\System32\\elsTrans.RecognizeText\"")
