#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\es.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\es.dll\"")
#pragma comment(linker, "/export:LCEControlServer=\"C:\\Windows\\System32\\es.dll\"")
#pragma comment(linker, "/export:NotifyLogoffUser=\"C:\\Windows\\System32\\es.dll\"")
#pragma comment(linker, "/export:NotifyLogonUser=\"C:\\Windows\\System32\\es.dll\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\es.dll\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\es.dll\"")
