#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\es.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\es.dll\"")
#print comment(linker, "/export:LCEControlServer=\"C:\\Windows\\SysWOW64\\es.dll\"")
#print comment(linker, "/export:NotifyLogoffUser=\"C:\\Windows\\SysWOW64\\es.dll\"")
#print comment(linker, "/export:NotifyLogonUser=\"C:\\Windows\\SysWOW64\\es.dll\"")
#print comment(linker, "/export:ServiceMain=\"C:\\Windows\\SysWOW64\\es.dll\"")
#print comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\SysWOW64\\es.dll\"")
