#pragma comment(linker, "/export:EseShadowCreateShadow=\"C:\\Windows\\System32\\esevss.dll\"")
#pragma comment(linker, "/export:EseShadowCreateSimpleShadow=\"C:\\Windows\\System32\\esevss.dll\"")
#pragma comment(linker, "/export:EseShadowInit=\"C:\\Windows\\System32\\esevss.dll\"")
#pragma comment(linker, "/export:EseShadowMountShadow=\"C:\\Windows\\System32\\esevss.dll\"")
#pragma comment(linker, "/export:EseShadowMountSimpleShadow=\"C:\\Windows\\System32\\esevss.dll\"")
#pragma comment(linker, "/export:EseShadowPurgeShadow=\"C:\\Windows\\System32\\esevss.dll\"")
#pragma comment(linker, "/export:EseShadowTerm=\"C:\\Windows\\System32\\esevss.dll\"")
#pragma comment(linker, "/export:VssIdToString=\"C:\\Windows\\System32\\esevss.dll\"")
