#pragma comment(linker, "/export:CreateForegroundTaskManager=\"C:\\Windows\\System32\\ExecModelClient.dll\"")
#pragma comment(linker, "/export:CreateModernVoipPolicy=\"C:\\Windows\\System32\\ExecModelClient.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\ExecModelClient.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\ExecModelClient.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\ExecModelClient.dll\"")
#pragma comment(linker, "/export:TestHook_CancelShutdown=\"C:\\Windows\\System32\\ExecModelClient.dll\"")
