#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\fdSSDP.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\fdSSDP.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\fdSSDP.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\fdSSDP.dll\"")
#pragma comment(linker, "/export:FdphostSessionChange=\"C:\\Windows\\System32\\fdSSDP.dll\"")
#pragma comment(linker, "/export:FdphostSetComContext=\"C:\\Windows\\System32\\fdSSDP.dll\"")
#pragma comment(linker, "/export:FdphostSetSharedService=\"C:\\Windows\\System32\\fdSSDP.dll\"")
