#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\fdWSD.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\fdWSD.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\fdWSD.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\fdWSD.DllUnregisterServer\"")
#pragma comment(linker, "/export:FdphostSessionChange=\"C:\\Windows\\System32\\fdWSD.FdphostSessionChange\"")
#pragma comment(linker, "/export:FdphostSetComContext=\"C:\\Windows\\System32\\fdWSD.FdphostSetComContext\"")
#pragma comment(linker, "/export:FdphostSetSharedService=\"C:\\Windows\\System32\\fdWSD.FdphostSetSharedService\"")
