#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\fdWSD.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\fdWSD.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\fdWSD.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\fdWSD.dll\"")
#print comment(linker, "/export:FdphostSessionChange=\"C:\\Windows\\System32\\fdWSD.dll\"")
#print comment(linker, "/export:FdphostSetComContext=\"C:\\Windows\\System32\\fdWSD.dll\"")
#print comment(linker, "/export:FdphostSetSharedService=\"C:\\Windows\\System32\\fdWSD.dll\"")
