#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\fhcleanup.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\fhcleanup.dll\"")
#print comment(linker, "/export:DllInstall=\"C:\\Windows\\System32\\fhcleanup.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\fhcleanup.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\fhcleanup.dll\"")
