#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\fhcleanup.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\fhcleanup.DllGetClassObject\"")
#pragma comment(linker, "/export:DllInstall=\"C:\\Windows\\System32\\fhcleanup.DllInstall\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\fhcleanup.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\fhcleanup.DllUnregisterServer\"")
