#pragma comment(linker, "/export:CacheSettingsDlg=\"C:\\Windows\\System32\\filemgmt.dll\"")
#pragma comment(linker, "/export:CacheSettingsDlg2=\"C:\\Windows\\System32\\filemgmt.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\filemgmt.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\filemgmt.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\filemgmt.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\filemgmt.dll\"")
