#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\FirewallControlPanel.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\FirewallControlPanel.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\FirewallControlPanel.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\FirewallControlPanel.dll\"")
#pragma comment(linker, "/export:ShowNotificationDialogW=\"C:\\Windows\\System32\\FirewallControlPanel.dll\"")
#pragma comment(linker, "/export:ShowWarningDialogW=\"C:\\Windows\\System32\\FirewallControlPanel.dll\"")
