#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\FlightSettings.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\FlightSettings.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\FlightSettings.DllGetClassObject\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\FlightSettings.ServiceMain\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\FlightSettings.SvchostPushServiceGlobals\"")
