#pragma comment(linker, "/export:CloseFileRestoreContext=\"C:\\Windows\\System32\\fmapi.dll\"")
#pragma comment(linker, "/export:CreateFileRestoreContext=\"C:\\Windows\\System32\\fmapi.dll\"")
#pragma comment(linker, "/export:DetectBootSector=\"C:\\Windows\\System32\\fmapi.dll\"")
#pragma comment(linker, "/export:DetectEncryptedVolume=\"C:\\Windows\\System32\\fmapi.dll\"")
#pragma comment(linker, "/export:DetectEncryptedVolumeEx=\"C:\\Windows\\System32\\fmapi.dll\"")
#pragma comment(linker, "/export:RestoreFile=\"C:\\Windows\\System32\\fmapi.dll\"")
#pragma comment(linker, "/export:ScanRestorableFiles=\"C:\\Windows\\System32\\fmapi.dll\"")
#pragma comment(linker, "/export:SupplyDecryptionInfo=\"C:\\Windows\\System32\\fmapi.dll\"")
