#pragma comment(linker, "/export:CanSendToFaxRecipient=\"C:\\Windows\\System32\\FXSUTILITY.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\FXSUTILITY.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\FXSUTILITY.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\FXSUTILITY.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\FXSUTILITY.dll\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\FXSUTILITY.dll\"")
#pragma comment(linker, "/export:SendToFaxRecipient=\"C:\\Windows\\System32\\FXSUTILITY.dll\"")
