#print comment(linker, "/export:?GPHHookWindowPointerDown@CGamePanelExternalHook@@SAIXZ=\"C:\\Windows\\System32\\GamePanelExternalHook.dll\"")
#print comment(linker, "/export:?GetInstance@CGamePanelExternalHook@@SAAEAV1@XZ=\"C:\\Windows\\System32\\GamePanelExternalHook.dll\"")
#print comment(linker, "/export:?Hook@CGamePanelExternalHook@@QEAAXPEAUHWND__@@@Z=\"C:\\Windows\\System32\\GamePanelExternalHook.dll\"")
#print comment(linker, "/export:?SetIntercept@CGamePanelExternalHook@@QEAAX_NPEAUHWND__@@@Z=\"C:\\Windows\\System32\\GamePanelExternalHook.dll\"")
#print comment(linker, "/export:?Unhook@CGamePanelExternalHook@@QEAAXXZ=\"C:\\Windows\\System32\\GamePanelExternalHook.dll\"")
