#pragma comment(linker, "/export:?GPHHookWindowPointerDown@CGamePanelExternalHook@@SAIXZ=\"C:\\Windows\\System32\\GamePanelExternalHook.?GPHHookWindowPointerDown@CGamePanelExternalHook@@SAIXZ\"")
#pragma comment(linker, "/export:?GetInstance@CGamePanelExternalHook@@SAAEAV1@XZ=\"C:\\Windows\\System32\\GamePanelExternalHook.?GetInstance@CGamePanelExternalHook@@SAAEAV1@XZ\"")
#pragma comment(linker, "/export:?Hook@CGamePanelExternalHook@@QEAAXPEAUHWND__@@@Z=\"C:\\Windows\\System32\\GamePanelExternalHook.?Hook@CGamePanelExternalHook@@QEAAXPEAUHWND__@@@Z\"")
#pragma comment(linker, "/export:?SetIntercept@CGamePanelExternalHook@@QEAAX_NPEAUHWND__@@@Z=\"C:\\Windows\\System32\\GamePanelExternalHook.?SetIntercept@CGamePanelExternalHook@@QEAAX_NPEAUHWND__@@@Z\"")
#pragma comment(linker, "/export:?Unhook@CGamePanelExternalHook@@QEAAXXZ=\"C:\\Windows\\System32\\GamePanelExternalHook.?Unhook@CGamePanelExternalHook@@QEAAXXZ\"")
