#print comment(linker, "/export:GMSAAdd=\"C:\\Windows\\System32\\gmsaclient.dll\"")
#print comment(linker, "/export:GMSACheckIfExistsInAD=\"C:\\Windows\\System32\\gmsaclient.dll\"")
#print comment(linker, "/export:GMSACleanup=\"C:\\Windows\\System32\\gmsaclient.dll\"")
#print comment(linker, "/export:GMSADelete=\"C:\\Windows\\System32\\gmsaclient.dll\"")
#print comment(linker, "/export:GMSAGetPassword=\"C:\\Windows\\System32\\gmsaclient.dll\"")
#print comment(linker, "/export:GMSAInit=\"C:\\Windows\\System32\\gmsaclient.dll\"")
#print comment(linker, "/export:GMSARefreshPasswords=\"C:\\Windows\\System32\\gmsaclient.dll\"")
