#pragma comment(linker, "/export:BrowseForGPO=\"C:\\Windows\\System32\\gpedit.BrowseForGPO\"")
#pragma comment(linker, "/export:CreateGPOLink=\"C:\\Windows\\System32\\gpedit.CreateGPOLink\"")
#pragma comment(linker, "/export:DeleteAllGPOLinks=\"C:\\Windows\\System32\\gpedit.DeleteAllGPOLinks\"")
#pragma comment(linker, "/export:DeleteGPOLink=\"C:\\Windows\\System32\\gpedit.DeleteGPOLink\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\gpedit.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\gpedit.DllGetClassObject\"")
#pragma comment(linker, "/export:ExportRSoPData=\"C:\\Windows\\System32\\gpedit.ExportRSoPData\"")
#pragma comment(linker, "/export:ImportRSoPData=\"C:\\Windows\\System32\\gpedit.ImportRSoPData\"")
