#print comment(linker, "/export:BrowseForGPO=\"C:\\Windows\\System32\\gpedit.dll\"")
#print comment(linker, "/export:CreateGPOLink=\"C:\\Windows\\System32\\gpedit.dll\"")
#print comment(linker, "/export:DeleteAllGPOLinks=\"C:\\Windows\\System32\\gpedit.dll\"")
#print comment(linker, "/export:DeleteGPOLink=\"C:\\Windows\\System32\\gpedit.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\gpedit.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\gpedit.dll\"")
#print comment(linker, "/export:ExportRSoPData=\"C:\\Windows\\System32\\gpedit.dll\"")
#print comment(linker, "/export:ImportRSoPData=\"C:\\Windows\\System32\\gpedit.dll\"")
