#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\gpprnext.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\gpprnext.dll\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\gpprnext.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\gpprnext.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\gpprnext.dll\"")
#pragma comment(linker, "/export:PrinterGenerateGroupPolicy=\"C:\\Windows\\System32\\gpprnext.dll\"")
#pragma comment(linker, "/export:PrinterProcessGroupPolicy=\"C:\\Windows\\System32\\gpprnext.dll\"")
#pragma comment(linker, "/export:PrinterProcessGroupPolicyEx=\"C:\\Windows\\System32\\gpprnext.dll\"")
