#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\gptext.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\gptext.DllUnregisterServer\"")
#pragma comment(linker, "/export:ProcessConnectivityPlatformPolicy=\"C:\\Windows\\System32\\gptext.ProcessConnectivityPlatformPolicy\"")
#pragma comment(linker, "/export:ProcessEQoSPolicy=\"C:\\Windows\\System32\\gptext.ProcessEQoSPolicy\"")
#pragma comment(linker, "/export:ProcessPSCHEDPolicy=\"C:\\Windows\\System32\\gptext.ProcessPSCHEDPolicy\"")
#pragma comment(linker, "/export:ProcessTCPIPPolicy=\"C:\\Windows\\System32\\gptext.ProcessTCPIPPolicy\"")
