#pragma comment(linker, "/export:CreateHolographicCompositor=\"C:\\Windows\\System32\\HologramCompositor.dll\"")
#pragma comment(linker, "/export:DwmInitializeEngine=\"C:\\Windows\\System32\\HologramCompositor.dll\"")
#pragma comment(linker, "/export:DwmInitializePort=\"C:\\Windows\\System32\\HologramCompositor.dll\"")
#pragma comment(linker, "/export:DwmRenderDesktopForDDA=\"C:\\Windows\\System32\\HologramCompositor.dll\"")
#pragma comment(linker, "/export:DwmShutdownEngine=\"C:\\Windows\\System32\\HologramCompositor.dll\"")
#pragma comment(linker, "/export:DwmVersionCheck=\"C:\\Windows\\System32\\HologramCompositor.dll\"")
#pragma comment(linker, "/export:GetMPCInputPostProcessor=\"C:\\Windows\\System32\\HologramCompositor.dll\"")
