#print comment(linker, "/export:ProxyHelperGetProxyEventInformation=\"C:\\Windows\\System32\\httpprxp.dll\"")
#print comment(linker, "/export:ProxyHelperProviderConnectToServer=\"C:\\Windows\\System32\\httpprxp.dll\"")
#print comment(linker, "/export:ProxyHelperProviderDisconnectFromServer=\"C:\\Windows\\System32\\httpprxp.dll\"")
#print comment(linker, "/export:ProxyHelperProviderFreeMemory=\"C:\\Windows\\System32\\httpprxp.dll\"")
#print comment(linker, "/export:ProxyHelperProviderRegisterForEventNotification=\"C:\\Windows\\System32\\httpprxp.dll\"")
#print comment(linker, "/export:ProxyHelperProviderSetProxyConfiguration=\"C:\\Windows\\System32\\httpprxp.dll\"")
#print comment(linker, "/export:ProxyHelperProviderSetProxyCredentials=\"C:\\Windows\\System32\\httpprxp.dll\"")
#print comment(linker, "/export:ProxyHelperProviderUnregisterEventNotification=\"C:\\Windows\\System32\\httpprxp.dll\"")
