#print comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\htui.dll\"")
#print comment(linker, "/export:HTUI_ColorAdjustment=\"C:\\Windows\\System32\\htui.dll\"")
#print comment(linker, "/export:HTUI_ColorAdjustmentA=\"C:\\Windows\\System32\\htui.dll\"")
#print comment(linker, "/export:HTUI_ColorAdjustmentW=\"C:\\Windows\\System32\\htui.dll\"")
#print comment(linker, "/export:HTUI_DeviceColorAdjustment=\"C:\\Windows\\System32\\htui.dll\"")
#print comment(linker, "/export:HTUI_DeviceColorAdjustmentA=\"C:\\Windows\\System32\\htui.dll\"")
#print comment(linker, "/export:HTUI_DeviceColorAdjustmentW=\"C:\\Windows\\System32\\htui.dll\"")
