#print comment(linker, "/export:HvlExchangeDispatchInterface=\"C:\\Windows\\System32\\hvloader.dll\"")
#print comment(linker, "/export:HvlLaunchHypervisor=\"C:\\Windows\\System32\\hvloader.dll\"")
#print comment(linker, "/export:HvlLoadHypervisor=\"C:\\Windows\\System32\\hvloader.dll\"")
#print comment(linker, "/export:HvlPreloadHypervisor=\"C:\\Windows\\System32\\hvloader.dll\"")
#print comment(linker, "/export:HvlRegisterRuntimeRange=\"C:\\Windows\\System32\\hvloader.dll\"")
#print comment(linker, "/export:HvlRescindVsm=\"C:\\Windows\\System32\\hvloader.dll\"")
#print comment(linker, "/export:HvlUpdateMcUpdateStatus=\"C:\\Windows\\System32\\hvloader.dll\"")
