#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\iassam.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\iassam.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\iassam.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\iassam.DllUnregisterServer\"")
#pragma comment(linker, "/export:IASParmsQueryUserProperty=\"C:\\Windows\\System32\\iassam.IASParmsQueryUserProperty\"")
