#print comment(linker, "/export:IcmpCloseHandle=\"C:\\Windows\\SysWOW64\\icmp.dll\"")
#print comment(linker, "/export:IcmpCreateFile=\"C:\\Windows\\SysWOW64\\icmp.dll\"")
#print comment(linker, "/export:IcmpParseReplies=\"C:\\Windows\\SysWOW64\\icmp.dll\"")
#print comment(linker, "/export:IcmpSendEcho=\"C:\\Windows\\SysWOW64\\icmp.dll\"")
#print comment(linker, "/export:IcmpSendEcho2=\"C:\\Windows\\SysWOW64\\icmp.dll\"")
#print comment(linker, "/export:do_echo_rep=\"C:\\Windows\\SysWOW64\\icmp.dll\"")
#print comment(linker, "/export:do_echo_req=\"C:\\Windows\\SysWOW64\\icmp.dll\"")
#print comment(linker, "/export:register_icmp=\"C:\\Windows\\SysWOW64\\icmp.dll\"")
