#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\icsvc.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\icsvc.dll\"")
#print comment(linker, "/export:GuestInterfaceServiceMain=\"C:\\Windows\\System32\\icsvc.dll\"")
#print comment(linker, "/export:HeartbeatServiceMain=\"C:\\Windows\\System32\\icsvc.dll\"")
#print comment(linker, "/export:KvpexchangeServiceMain=\"C:\\Windows\\System32\\icsvc.dll\"")
#print comment(linker, "/export:ShutdownServiceMain=\"C:\\Windows\\System32\\icsvc.dll\"")
#print comment(linker, "/export:TimesyncServiceMain=\"C:\\Windows\\System32\\icsvc.dll\"")
#print comment(linker, "/export:VMSessionServiceMain=\"C:\\Windows\\System32\\icsvc.dll\"")
