#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\icsvc.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\icsvc.DllUnregisterServer\"")
#pragma comment(linker, "/export:GuestInterfaceServiceMain=\"C:\\Windows\\System32\\icsvc.GuestInterfaceServiceMain\"")
#pragma comment(linker, "/export:HeartbeatServiceMain=\"C:\\Windows\\System32\\icsvc.HeartbeatServiceMain\"")
#pragma comment(linker, "/export:KvpexchangeServiceMain=\"C:\\Windows\\System32\\icsvc.KvpexchangeServiceMain\"")
#pragma comment(linker, "/export:ShutdownServiceMain=\"C:\\Windows\\System32\\icsvc.ShutdownServiceMain\"")
#pragma comment(linker, "/export:TimesyncServiceMain=\"C:\\Windows\\System32\\icsvc.TimesyncServiceMain\"")
#pragma comment(linker, "/export:VMSessionServiceMain=\"C:\\Windows\\System32\\icsvc.VMSessionServiceMain\"")
