#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\iepeers.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllEnumClassObjects=\"C:\\Windows\\System32\\iepeers.DllEnumClassObjects\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\iepeers.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\iepeers.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\iepeers.DllUnregisterServer\"")
