#print comment(linker, "/export:IEApplyCurrentHardening=\"C:\\Windows\\System32\\iesetup.dll\"")
#print comment(linker, "/export:IEHardenAdmin=\"C:\\Windows\\System32\\iesetup.dll\"")
#print comment(linker, "/export:IEHardenAdminNow=\"C:\\Windows\\System32\\iesetup.dll\"")
#print comment(linker, "/export:IEHardenLMSettings=\"C:\\Windows\\System32\\iesetup.dll\"")
#print comment(linker, "/export:IEHardenMachineNow=\"C:\\Windows\\System32\\iesetup.dll\"")
#print comment(linker, "/export:IEHardenUser=\"C:\\Windows\\System32\\iesetup.dll\"")
#print comment(linker, "/export:IEShowHardeningDialog=\"C:\\Windows\\System32\\iesetup.dll\"")
