#print comment(linker, "/export:Sysprep_Cleanup_IE=\"C:\\Windows\\System32\\iesysprep.dll\"")
#print comment(linker, "/export:Sysprep_Generalize_IE=\"C:\\Windows\\System32\\iesysprep.dll\"")
#print comment(linker, "/export:Sysprep_Offline_Specialize_IE=\"C:\\Windows\\System32\\iesysprep.dll\"")
#print comment(linker, "/export:Sysprep_Online_Specialize_IE=\"C:\\Windows\\System32\\iesysprep.dll\"")
#print comment(linker, "/export:Sysprep_Specialize_IE=\"C:\\Windows\\System32\\iesysprep.dll\"")
