#print comment(linker, "/export:CheckSnapshotPresence=\"C:\\Windows\\System32\\ifsutilx.dll\"")
#print comment(linker, "/export:CreateVolumeSnapshot=\"C:\\Windows\\System32\\ifsutilx.dll\"")
#print comment(linker, "/export:GetSnapshotErrorMessage=\"C:\\Windows\\System32\\ifsutilx.dll\"")
#print comment(linker, "/export:InitializeCOM=\"C:\\Windows\\System32\\ifsutilx.dll\"")
#print comment(linker, "/export:ReleaseVolumeSnapshot=\"C:\\Windows\\System32\\ifsutilx.dll\"")
#print comment(linker, "/export:UninitializeCOM=\"C:\\Windows\\System32\\ifsutilx.dll\"")
