#pragma comment(linker, "/export:ImplatMuxDispatch=\"C:\\Windows\\System32\\ImplatSetup.dll\"")
#pragma comment(linker, "/export:ImplatMuxMemberUninstall=\"C:\\Windows\\System32\\ImplatSetup.dll\"")
#pragma comment(linker, "/export:ImplatMuxModified=\"C:\\Windows\\System32\\ImplatSetup.dll\"")
#pragma comment(linker, "/export:ImplatMuxVirtualInterfaceChanged=\"C:\\Windows\\System32\\ImplatSetup.dll\"")
#pragma comment(linker, "/export:ImplatMuxVirtualInterfaces=\"C:\\Windows\\System32\\ImplatSetup.dll\"")
#pragma comment(linker, "/export:ImplatTransactionDispatch=\"C:\\Windows\\System32\\ImplatSetup.dll\"")
#pragma comment(linker, "/export:ImplatVmsBinding=\"C:\\Windows\\System32\\ImplatSetup.dll\"")
