#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\InstallServiceTasks.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\InstallServiceTasks.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\InstallServiceTasks.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\InstallServiceTasks.dll\"")
#print comment(linker, "/export:ForceAppInUseRestart=\"C:\\Windows\\System32\\InstallServiceTasks.dll\"")
