#pragma comment(linker, "/export:CreateInternetMailSyncServiceLayer=\"C:\\Windows\\System32\\internetmail.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\internetmail.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\internetmail.dll\"")
#pragma comment(linker, "/export:GetAutoConfigManager=\"C:\\Windows\\System32\\internetmail.dll\"")
#pragma comment(linker, "/export:OneStopFactory=\"C:\\Windows\\System32\\internetmail.dll\"")
