#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\invagent.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\invagent.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\invagent.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\invagent.dll\"")
#print comment(linker, "/export:GetDetailedAppInventoryReport=\"C:\\Windows\\System32\\invagent.dll\"")
#print comment(linker, "/export:GetFileSigningInfoTC=\"C:\\Windows\\System32\\invagent.dll\"")
#print comment(linker, "/export:RunUpdate=\"C:\\Windows\\System32\\invagent.dll\"")
#print comment(linker, "/export:RunUpdateTC=\"C:\\Windows\\System32\\invagent.dll\"")
