#pragma comment(linker, "/export:CleanUpIpPriority=\"C:\\Windows\\System32\\iprtprio.CleanUpIpPriority\"")
#pragma comment(linker, "/export:ComputeRouteMetric=\"C:\\Windows\\System32\\iprtprio.ComputeRouteMetric\"")
#pragma comment(linker, "/export:ComputeRouteMetricEx=\"C:\\Windows\\System32\\iprtprio.ComputeRouteMetricEx\"")
#pragma comment(linker, "/export:GetPriorityInfo=\"C:\\Windows\\System32\\iprtprio.GetPriorityInfo\"")
#pragma comment(linker, "/export:SetPriorityInfo=\"C:\\Windows\\System32\\iprtprio.SetPriorityInfo\"")
