#print comment(linker, "/export:InternetDeInitializeAutoProxyDll=\"C:\\Windows\\System32\\jsproxy.dll\"")
#print comment(linker, "/export:InternetDeInitializeAutoProxyDllEx=\"C:\\Windows\\System32\\jsproxy.dll\"")
#print comment(linker, "/export:InternetGetProxyInfo=\"C:\\Windows\\System32\\jsproxy.dll\"")
#print comment(linker, "/export:InternetGetProxyInfoEx=\"C:\\Windows\\System32\\jsproxy.dll\"")
#print comment(linker, "/export:InternetInitializeAutoProxyDll=\"C:\\Windows\\System32\\jsproxy.dll\"")
#print comment(linker, "/export:InternetInitializeAutoProxyDllEx=\"C:\\Windows\\System32\\jsproxy.dll\"")
