#pragma comment(linker, "/export:KbdLayerDescriptor=\"C:\\Windows\\System32\\KBDJPN.KbdLayerDescriptor\"")
#pragma comment(linker, "/export:KbdLayerMultiDescriptor=\"C:\\Windows\\System32\\KBDJPN.KbdLayerMultiDescriptor\"")
#pragma comment(linker, "/export:KbdLayerRealDllFile=\"C:\\Windows\\System32\\KBDJPN.KbdLayerRealDllFile\"")
#pragma comment(linker, "/export:KbdLayerRealDllFileNT4=\"C:\\Windows\\System32\\KBDJPN.KbdLayerRealDllFileNT4\"")
#pragma comment(linker, "/export:KbdNlsLayerDescriptor=\"C:\\Windows\\System32\\KBDJPN.KbdNlsLayerDescriptor\"")
