#print comment(linker, "/export:KbdLayerDescriptor=\"C:\\Windows\\System32\\KBDKOR.DLL\"")
#print comment(linker, "/export:KbdLayerMultiDescriptor=\"C:\\Windows\\System32\\KBDKOR.DLL\"")
#print comment(linker, "/export:KbdLayerRealDllFile=\"C:\\Windows\\System32\\KBDKOR.DLL\"")
#print comment(linker, "/export:KbdLayerRealDllFileNT4=\"C:\\Windows\\System32\\KBDKOR.DLL\"")
#print comment(linker, "/export:KbdNlsLayerDescriptor=\"C:\\Windows\\System32\\KBDKOR.DLL\"")
