#pragma comment(linker, "/export:KdInitialize=\"C:\\Windows\\System32\\kd.KdInitialize\"")
#pragma comment(linker, "/export:KdPower=\"C:\\Windows\\System32\\kd.KdPower\"")
#pragma comment(linker, "/export:KdReceivePacket=\"C:\\Windows\\System32\\kd.KdReceivePacket\"")
#pragma comment(linker, "/export:KdSendPacket=\"C:\\Windows\\System32\\kd.KdSendPacket\"")
#pragma comment(linker, "/export:KdSetHiberRange=\"C:\\Windows\\System32\\kd.KdSetHiberRange\"")
