#pragma comment(linker, "/export:KdInitialize=\"C:\\Windows\\System32\\kdcom.KdInitialize\"")
#pragma comment(linker, "/export:KdPower=\"C:\\Windows\\System32\\kdcom.KdPower\"")
#pragma comment(linker, "/export:KdReceivePacket=\"C:\\Windows\\System32\\kdcom.KdReceivePacket\"")
#pragma comment(linker, "/export:KdSendPacket=\"C:\\Windows\\System32\\kdcom.KdSendPacket\"")
#pragma comment(linker, "/export:KdSetHiberRange=\"C:\\Windows\\System32\\kdcom.KdSetHiberRange\"")
