#pragma comment(linker, "/export:KdInitialize=\"C:\\Windows\\System32\\kdnet.KdInitialize\"")
#pragma comment(linker, "/export:KdPower=\"C:\\Windows\\System32\\kdnet.KdPower\"")
#pragma comment(linker, "/export:KdReceivePacket=\"C:\\Windows\\System32\\kdnet.KdReceivePacket\"")
#pragma comment(linker, "/export:KdSendPacket=\"C:\\Windows\\System32\\kdnet.KdSendPacket\"")
#pragma comment(linker, "/export:KdSetHiberRange=\"C:\\Windows\\System32\\kdnet.KdSetHiberRange\"")
