#pragma comment(linker, "/export:KdInitialize=\"C:\\Windows\\System32\\kdnet.dll\"")
#pragma comment(linker, "/export:KdPower=\"C:\\Windows\\System32\\kdnet.dll\"")
#pragma comment(linker, "/export:KdReceivePacket=\"C:\\Windows\\System32\\kdnet.dll\"")
#pragma comment(linker, "/export:KdSendPacket=\"C:\\Windows\\System32\\kdnet.dll\"")
#pragma comment(linker, "/export:KdSetHiberRange=\"C:\\Windows\\System32\\kdnet.dll\"")
