#pragma comment(linker, "/export:KsCreateAllocator=\"C:\\Windows\\System32\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreateAllocator2=\"C:\\Windows\\System32\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreateClock=\"C:\\Windows\\System32\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreateClock2=\"C:\\Windows\\System32\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreatePin=\"C:\\Windows\\System32\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreatePin2=\"C:\\Windows\\System32\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreateTopologyNode=\"C:\\Windows\\System32\\ksuser.dll\"")
#pragma comment(linker, "/export:KsCreateTopologyNode2=\"C:\\Windows\\System32\\ksuser.dll\"")
