#print comment(linker, "/export:L2GPPolicyDataDelete=\"C:\\Windows\\System32\\l2gpstore.dll\"")
#print comment(linker, "/export:L2GPPolicyDataDeleteAll=\"C:\\Windows\\System32\\l2gpstore.dll\"")
#print comment(linker, "/export:L2GPPolicyDataRead=\"C:\\Windows\\System32\\l2gpstore.dll\"")
#print comment(linker, "/export:L2GPPolicyDataWrite=\"C:\\Windows\\System32\\l2gpstore.dll\"")
#print comment(linker, "/export:L2GPPolicyFreeMem=\"C:\\Windows\\System32\\l2gpstore.dll\"")
#print comment(linker, "/export:L2GPPolicyStoreClose=\"C:\\Windows\\System32\\l2gpstore.dll\"")
#print comment(linker, "/export:L2GPPolicyStoreOpen=\"C:\\Windows\\System32\\l2gpstore.dll\"")
