#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\lltdapi.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\lltdapi.dll\"")
#pragma comment(linker, "/export:LLTDCreateEnumerator=\"C:\\Windows\\System32\\lltdapi.dll\"")
#pragma comment(linker, "/export:LLTDCreateMapFromXML=\"C:\\Windows\\System32\\lltdapi.dll\"")
#pragma comment(linker, "/export:LLTDCreateMapper=\"C:\\Windows\\System32\\lltdapi.dll\"")
#pragma comment(linker, "/export:LLTDCreateNode=\"C:\\Windows\\System32\\lltdapi.dll\"")
