#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\LockHostingFramework.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\LockHostingFramework.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\LockHostingFramework.dll\"")
#pragma comment(linker, "/export:ShutdownLockAppHostServer=\"C:\\Windows\\System32\\LockHostingFramework.dll\"")
#pragma comment(linker, "/export:StartLockAppHostServer=\"C:\\Windows\\System32\\LockHostingFramework.dll\"")
