#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\LockHostingFramework.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\LockHostingFramework.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\LockHostingFramework.DllGetClassObject\"")
#pragma comment(linker, "/export:ShutdownLockAppHostServer=\"C:\\Windows\\System32\\LockHostingFramework.ShutdownLockAppHostServer\"")
#pragma comment(linker, "/export:StartLockAppHostServer=\"C:\\Windows\\System32\\LockHostingFramework.StartLockAppHostServer\"")
