#print comment(linker, "/export:GetLicensingTelemetryCommonData=\"C:\\Windows\\System32\\lstelemetry.dll\"")
#print comment(linker, "/export:InitRDLSTelemetryCommonData=\"C:\\Windows\\System32\\lstelemetry.dll\"")
#print comment(linker, "/export:LogRDLSSettingsTelemetryData=\"C:\\Windows\\System32\\lstelemetry.dll\"")
#print comment(linker, "/export:LogTSLSTelemetryEvent=\"C:\\Windows\\System32\\lstelemetry.dll\"")
#print comment(linker, "/export:LogTSLSTelemetryRDSEvent=\"C:\\Windows\\System32\\lstelemetry.dll\"")
#print comment(linker, "/export:RegisterAndEnableLicensingTelemetry=\"C:\\Windows\\System32\\lstelemetry.dll\"")
#print comment(linker, "/export:UnregisterLicensingTelemetry=\"C:\\Windows\\System32\\lstelemetry.dll\"")
#print comment(linker, "/export:UpdateRDLSTelemetryCommonData=\"C:\\Windows\\System32\\lstelemetry.dll\"")
