#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MaintenanceUI.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MaintenanceUI.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\MaintenanceUI.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\MaintenanceUI.dll\"")
#pragma comment(linker, "/export:StartMaintenance=\"C:\\Windows\\System32\\MaintenanceUI.dll\"")
#pragma comment(linker, "/export:StopMaintenance=\"C:\\Windows\\System32\\MaintenanceUI.dll\"")
