#print comment(linker, "/export:??0MbaeXmlParser@@QEAA@$$QEAV0@@Z=\"C:\\Windows\\System32\\MbaeXmlParser.dll\"")
#print comment(linker, "/export:??0MbaeXmlParser@@QEAA@AEBV0@@Z=\"C:\\Windows\\System32\\MbaeXmlParser.dll\"")
#print comment(linker, "/export:??0MbaeXmlParser@@QEAA@XZ=\"C:\\Windows\\System32\\MbaeXmlParser.dll\"")
#print comment(linker, "/export:??4MbaeXmlParser@@QEAAAEAV0@$$QEAV0@@Z=\"C:\\Windows\\System32\\MbaeXmlParser.dll\"")
#print comment(linker, "/export:??4MbaeXmlParser@@QEAAAEAV0@AEBV0@@Z=\"C:\\Windows\\System32\\MbaeXmlParser.dll\"")
#print comment(linker, "/export:??_7MbaeXmlParser@@6B@=\"C:\\Windows\\System32\\MbaeXmlParser.dll\"")
#print comment(linker, "/export:?Create@MbaeXmlParser@@SAJPEAPEAV1@@Z=\"C:\\Windows\\System32\\MbaeXmlParser.dll\"")
