#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\mfnetsrc.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\mfnetsrc.dll\"")
#pragma comment(linker, "/export:MFCreateByteCacheFile=\"C:\\Windows\\System32\\mfnetsrc.dll\"")
#pragma comment(linker, "/export:MFCreateCacheManager=\"C:\\Windows\\System32\\mfnetsrc.dll\"")
#pragma comment(linker, "/export:MFCreateFileBlockMap=\"C:\\Windows\\System32\\mfnetsrc.dll\"")
