#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\mfnetsrc.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\mfnetsrc.DllGetClassObject\"")
#pragma comment(linker, "/export:MFCreateByteCacheFile=\"C:\\Windows\\System32\\mfnetsrc.MFCreateByteCacheFile\"")
#pragma comment(linker, "/export:MFCreateCacheManager=\"C:\\Windows\\System32\\mfnetsrc.MFCreateCacheManager\"")
#pragma comment(linker, "/export:MFCreateFileBlockMap=\"C:\\Windows\\System32\\mfnetsrc.MFCreateFileBlockMap\"")
