#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\MFPlay.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\MFPlay.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\MFPlay.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\MFPlay.dll\"")
#print comment(linker, "/export:MFPCreateMediaPlayer=\"C:\\Windows\\SysWOW64\\MFPlay.dll\"")
#print comment(linker, "/export:MFPCreateMediaPlayerEx=\"C:\\Windows\\SysWOW64\\MFPlay.dll\"")
