#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MFPlay.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MFPlay.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\MFPlay.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\MFPlay.dll\"")
#print comment(linker, "/export:MFPCreateMediaPlayer=\"C:\\Windows\\System32\\MFPlay.dll\"")
#print comment(linker, "/export:MFPCreateMediaPlayerEx=\"C:\\Windows\\System32\\MFPlay.dll\"")
