#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\mfsvr.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\mfsvr.dll\"")
#pragma comment(linker, "/export:MFCreateHDCPStatus=\"C:\\Windows\\System32\\mfsvr.dll\"")
#pragma comment(linker, "/export:MFCreateMediaEngineVideoOTA=\"C:\\Windows\\System32\\mfsvr.dll\"")
#pragma comment(linker, "/export:MFCreateOPMHelper=\"C:\\Windows\\System32\\mfsvr.dll\"")
#pragma comment(linker, "/export:MFCreateTimedTextRenderer=\"C:\\Windows\\System32\\mfsvr.dll\"")
