#pragma comment(linker, "/export:GetTranscodeComponentCreator=\"C:\\Windows\\System32\\mftranscode.dll\"")
#pragma comment(linker, "/export:MFCreateSmartRemuxEngine=\"C:\\Windows\\System32\\mftranscode.dll\"")
#pragma comment(linker, "/export:MFCreateTranscodeEngine=\"C:\\Windows\\System32\\mftranscode.dll\"")
#pragma comment(linker, "/export:MFCreateTranscodeProfile=\"C:\\Windows\\System32\\mftranscode.dll\"")
#pragma comment(linker, "/export:MFCreateTranscodeSinkActivate=\"C:\\Windows\\System32\\mftranscode.dll\"")
#pragma comment(linker, "/export:MFCreateTranscodeTopology=\"C:\\Windows\\System32\\mftranscode.dll\"")
#pragma comment(linker, "/export:MFCreateTranscodeTopologyFromByteStream=\"C:\\Windows\\System32\\mftranscode.dll\"")
#pragma comment(linker, "/export:MFTranscodeGetAudioOutputAvailableTypes=\"C:\\Windows\\System32\\mftranscode.dll\"")
