#pragma comment(linker, "/export:ClearSettingGroupValue=\"C:\\Windows\\System32\\Microsoft.Uev.ConfigWrapper.dll\"")
#pragma comment(linker, "/export:ClearSettingValue=\"C:\\Windows\\System32\\Microsoft.Uev.ConfigWrapper.dll\"")
#pragma comment(linker, "/export:GetSettingGroupValue=\"C:\\Windows\\System32\\Microsoft.Uev.ConfigWrapper.dll\"")
#pragma comment(linker, "/export:GetSettingValue=\"C:\\Windows\\System32\\Microsoft.Uev.ConfigWrapper.dll\"")
#pragma comment(linker, "/export:SetSettingGroupValue=\"C:\\Windows\\System32\\Microsoft.Uev.ConfigWrapper.dll\"")
#pragma comment(linker, "/export:SetSettingValue=\"C:\\Windows\\System32\\Microsoft.Uev.ConfigWrapper.dll\"")
