#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MiracastReceiverExt.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MiracastReceiverExt.dll\"")
#print comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\MiracastReceiverExt.dll\"")
#print comment(linker, "/export:GetPlatformSpecificLockScreenAppLauncher=\"C:\\Windows\\System32\\MiracastReceiverExt.dll\"")
#print comment(linker, "/export:IsLockScreenActive=\"C:\\Windows\\System32\\MiracastReceiverExt.dll\"")
