#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MitigationConfiguration.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MitigationConfiguration.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\MitigationConfiguration.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\MitigationConfiguration.dll\"")
#pragma comment(linker, "/export:ExportMitigation=\"C:\\Windows\\System32\\MitigationConfiguration.dll\"")
#pragma comment(linker, "/export:ImportMitigation=\"C:\\Windows\\System32\\MitigationConfiguration.dll\"")
#pragma comment(linker, "/export:ValidateXML=\"C:\\Windows\\System32\\MitigationConfiguration.dll\"")
#pragma comment(linker, "/export:ValidateXMLFromManaged=\"C:\\Windows\\System32\\MitigationConfiguration.dll\"")
