#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MixedRealityRuntime.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\MixedRealityRuntime.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MixedRealityRuntime.DllGetClassObject\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\MixedRealityRuntime.ServiceMain\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\MixedRealityRuntime.SvchostPushServiceGlobals\"")
#pragma comment(linker, "/export:xrNegotiateLoaderRuntimeInterface=\"C:\\Windows\\System32\\MixedRealityRuntime.xrNegotiateLoaderRuntimeInterface\"")
