#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\MixedRealityRuntime.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\MixedRealityRuntime.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\MixedRealityRuntime.dll\"")
#print comment(linker, "/export:ServiceMain=\"C:\\Windows\\SysWOW64\\MixedRealityRuntime.dll\"")
#print comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\SysWOW64\\MixedRealityRuntime.dll\"")
#print comment(linker, "/export:xrNegotiateLoaderRuntimeInterface=\"C:\\Windows\\SysWOW64\\MixedRealityRuntime.dll\"")
