#pragma comment(linker, "/export:CreateInstance=\"C:\\Windows\\System32\\MP3DMOD.CreateInstance\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MP3DMOD.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MP3DMOD.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\MP3DMOD.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\MP3DMOD.DllUnregisterServer\"")
