#pragma comment(linker, "/export:CreateInstance=\"C:\\Windows\\System32\\MP43DECD.CreateInstance\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MP43DECD.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MP43DECD.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\MP43DECD.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\MP43DECD.DllUnregisterServer\"")
