#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\msdtcuiu.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\msdtcuiu.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\msdtcuiu.dll\"")
#print comment(linker, "/export:DtcPerfClose=\"C:\\Windows\\System32\\msdtcuiu.dll\"")
#print comment(linker, "/export:DtcPerfCollect=\"C:\\Windows\\System32\\msdtcuiu.dll\"")
#print comment(linker, "/export:DtcPerfOpen=\"C:\\Windows\\System32\\msdtcuiu.dll\"")
#print comment(linker, "/export:PerfDllRegisterServer=\"C:\\Windows\\System32\\msdtcuiu.dll\"")
