#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\mshtmled.dll\"")
#print comment(linker, "/export:DllEnumClassObjects=\"C:\\Windows\\SysWOW64\\mshtmled.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\mshtmled.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\mshtmled.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\mshtmled.dll\"")
