#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\msimtf.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\msimtf.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\msimtf.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\msimtf.dll\"")
#pragma comment(linker, "/export:MsimtfIsGuidMapEnable=\"C:\\Windows\\System32\\msimtf.dll\"")
#pragma comment(linker, "/export:MsimtfIsWindowFiltered=\"C:\\Windows\\System32\\msimtf.dll\"")
