#print comment(linker, "/export:AlphaBlend=\"C:\\Windows\\SysWOW64\\msimg32.dll\"")
#print comment(linker, "/export:DllInitialize=\"C:\\Windows\\SysWOW64\\msimg32.dll\"")
#print comment(linker, "/export:GradientFill=\"C:\\Windows\\SysWOW64\\msimg32.dll\"")
#print comment(linker, "/export:TransparentBlt=\"C:\\Windows\\SysWOW64\\msimg32.dll\"")
#print comment(linker, "/export:vSetDdrawflag=\"C:\\Windows\\SysWOW64\\msimg32.dll\"")
