#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\msisip.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\msisip.dll\"")
#print comment(linker, "/export:MsiSIPCreateIndirectData=\"C:\\Windows\\System32\\msisip.dll\"")
#print comment(linker, "/export:MsiSIPGetSignedDataMsg=\"C:\\Windows\\System32\\msisip.dll\"")
#print comment(linker, "/export:MsiSIPIsMyTypeOfFile=\"C:\\Windows\\System32\\msisip.dll\"")
#print comment(linker, "/export:MsiSIPPutSignedDataMsg=\"C:\\Windows\\System32\\msisip.dll\"")
#print comment(linker, "/export:MsiSIPRemoveSignedDataMsg=\"C:\\Windows\\System32\\msisip.dll\"")
#print comment(linker, "/export:MsiSIPVerifyIndirectData=\"C:\\Windows\\System32\\msisip.dll\"")
