#pragma comment(linker, "/export:?GetSurface@CVIDEOfilter@@QEAAJHPEAEJ@Z=\"C:\\Windows\\System32\\msmpeg2vdec.dll\"")
#pragma comment(linker, "/export:?GetSurfaceSize@CVIDEOfilter@@QEAAJHPEAJ@Z=\"C:\\Windows\\System32\\msmpeg2vdec.dll\"")
#pragma comment(linker, "/export:?LoadSurface@CVIDEOfilter@@QEAAJHPEAEK@Z=\"C:\\Windows\\System32\\msmpeg2vdec.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\msmpeg2vdec.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\msmpeg2vdec.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\msmpeg2vdec.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\msmpeg2vdec.dll\"")
#pragma comment(linker, "/export:GetH264DecoderFunctionTable=\"C:\\Windows\\System32\\msmpeg2vdec.dll\"")
