#print comment(linker, "/export:Close=\"C:\\Windows\\System32\\msscntrs.dll\"")
#print comment(linker, "/export:Collect=\"C:\\Windows\\System32\\msscntrs.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\msscntrs.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\msscntrs.dll\"")
#print comment(linker, "/export:Open=\"C:\\Windows\\System32\\msscntrs.dll\"")
