#print comment(linker, "/export:ClosePopupTipbar=\"C:\\Windows\\System32\\msutb.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\msutb.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\msutb.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\msutb.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\msutb.dll\"")
#print comment(linker, "/export:GetChildTipbar=\"C:\\Windows\\System32\\msutb.dll\"")
#print comment(linker, "/export:GetPopupTipbar=\"C:\\Windows\\System32\\msutb.dll\"")
#print comment(linker, "/export:SetRegisterLangBand=\"C:\\Windows\\System32\\msutb.dll\"")
