#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MSVidCtl.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MSVidCtl.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\MSVidCtl.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\MSVidCtl.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\MSVidCtl.GetProxyDllInfo\"")
