#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MSVideoDSP.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\MSVideoDSP.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MSVideoDSP.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\MSVideoDSP.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\MSVideoDSP.DllUnregisterServer\"")
