#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\msxml6.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\msxml6.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\msxml6.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\msxml6.DllRegisterServer\"")
#pragma comment(linker, "/export:DllSetProperty=\"C:\\Windows\\System32\\msxml6.DllSetProperty\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\msxml6.DllUnregisterServer\"")
