#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\msxml6.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\msxml6.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\msxml6.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\msxml6.dll\"")
#print comment(linker, "/export:DllSetProperty=\"C:\\Windows\\System32\\msxml6.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\msxml6.dll\"")
