#pragma comment(linker, "/export:OnMachineUILanguageClear=\"C:\\Windows\\System32\\MUILanguageCleanup.dll\"")
#pragma comment(linker, "/export:OnMachineUILanguageInit=\"C:\\Windows\\System32\\MUILanguageCleanup.dll\"")
#pragma comment(linker, "/export:OnMachineUILanguageSwitch=\"C:\\Windows\\System32\\MUILanguageCleanup.dll\"")
#pragma comment(linker, "/export:OnUILanguageAdd=\"C:\\Windows\\System32\\MUILanguageCleanup.dll\"")
#pragma comment(linker, "/export:OnUILanguageRemove=\"C:\\Windows\\System32\\MUILanguageCleanup.dll\"")
