#print comment(linker, "/export:NetDriverInstallClose=\"C:\\Windows\\System32\\NetDriverInstall.dll\"")
#print comment(linker, "/export:NetDriverInstallCommit=\"C:\\Windows\\System32\\NetDriverInstall.dll\"")
#print comment(linker, "/export:NetDriverInstallInitialize=\"C:\\Windows\\System32\\NetDriverInstall.dll\"")
#print comment(linker, "/export:NetDriverInstallProcessAdditions=\"C:\\Windows\\System32\\NetDriverInstall.dll\"")
#print comment(linker, "/export:NetDriverInstallProcessRemovals=\"C:\\Windows\\System32\\NetDriverInstall.dll\"")
#print comment(linker, "/export:NetDriverInstallSync=\"C:\\Windows\\System32\\NetDriverInstall.dll\"")
