#print comment(linker, "/export:HelperTraceEvent=\"C:\\Windows\\System32\\netdiagfx.dll\"")
#print comment(linker, "/export:HelperTraceInitialize=\"C:\\Windows\\System32\\netdiagfx.dll\"")
#print comment(linker, "/export:HelperTraceUninitialize=\"C:\\Windows\\System32\\netdiagfx.dll\"")
#print comment(linker, "/export:WdiDiagnosticModuleMain=\"C:\\Windows\\System32\\netdiagfx.dll\"")
#print comment(linker, "/export:WdiGetDiagnosticModuleInterfaceVersion=\"C:\\Windows\\System32\\netdiagfx.dll\"")
#print comment(linker, "/export:WdiHandleInstance=\"C:\\Windows\\System32\\netdiagfx.dll\"")
