#pragma comment(linker, "/export:ClearAutoLogon=\"C:\\Windows\\System32\\netplwiz.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\netplwiz.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\netplwiz.dll\"")
#pragma comment(linker, "/export:NetAccessWizard=\"C:\\Windows\\System32\\netplwiz.dll\"")
#pragma comment(linker, "/export:NetPlacesWizardDoModal=\"C:\\Windows\\System32\\netplwiz.dll\"")
#pragma comment(linker, "/export:SHDisconnectNetDrives=\"C:\\Windows\\System32\\netplwiz.dll\"")
#pragma comment(linker, "/export:UsersRunDllW=\"C:\\Windows\\System32\\netplwiz.dll\"")
