#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\NetSetupShim.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\NetSetupShim.dll\"")
#print comment(linker, "/export:NetSetupCreateBindingMap=\"C:\\Windows\\System32\\NetSetupShim.dll\"")
#print comment(linker, "/export:NetSetupExportDatabase=\"C:\\Windows\\System32\\NetSetupShim.dll\"")
#print comment(linker, "/export:NetSetupResetBindings=\"C:\\Windows\\System32\\NetSetupShim.dll\"")
#print comment(linker, "/export:NetSetupShimExecuteInfSection=\"C:\\Windows\\System32\\NetSetupShim.dll\"")
