#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\NetworkUXBroker.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\NetworkUXBroker.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\NetworkUXBroker.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\NetworkUXBroker.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\NetworkUXBroker.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\NetworkUXBroker.DllUnregisterServer\"")
