#pragma comment(linker, "/export:NgcLocalAddCredential=\"C:\\Windows\\System32\\ngclocal.NgcLocalAddCredential\"")
#pragma comment(linker, "/export:NgcLocalAddCredentialSilent=\"C:\\Windows\\System32\\ngclocal.NgcLocalAddCredentialSilent\"")
#pragma comment(linker, "/export:NgcLocalChangeCredential=\"C:\\Windows\\System32\\ngclocal.NgcLocalChangeCredential\"")
#pragma comment(linker, "/export:NgcLocalFindCredential=\"C:\\Windows\\System32\\ngclocal.NgcLocalFindCredential\"")
#pragma comment(linker, "/export:NgcLocalRemoveCredential=\"C:\\Windows\\System32\\ngclocal.NgcLocalRemoveCredential\"")
