#pragma comment(linker, "/export:NgcIsPinRecoveryEnabled=\"C:\\Windows\\System32\\ngcrecovery.dll\"")
#pragma comment(linker, "/export:NgcProtectPinRecoverySecret=\"C:\\Windows\\System32\\ngcrecovery.dll\"")
#pragma comment(linker, "/export:NgcRecoverPin=\"C:\\Windows\\System32\\ngcrecovery.dll\"")
#pragma comment(linker, "/export:NgcRecoverPinSilent=\"C:\\Windows\\System32\\ngcrecovery.dll\"")
#pragma comment(linker, "/export:NgcVerifyPinRecoverySecret=\"C:\\Windows\\System32\\ngcrecovery.dll\"")
