#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\ngctasks.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\ngctasks.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\ngctasks.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\ngctasks.dll\"")
#pragma comment(linker, "/export:GetRetryTimeStamp=\"C:\\Windows\\System32\\ngctasks.dll\"")
#pragma comment(linker, "/export:NgcTriggerTaskForOobe=\"C:\\Windows\\System32\\ngctasks.dll\"")
#pragma comment(linker, "/export:SetAikTimeTrigger=\"C:\\Windows\\System32\\ngctasks.dll\"")
