#print comment(linker, "/export:AddDemoAppLicense=\"C:\\Windows\\System32\\oemlicense.dll\"")
#print comment(linker, "/export:HrAddAppxLicense=\"C:\\Windows\\System32\\oemlicense.dll\"")
#print comment(linker, "/export:HrInstallClipLicense=\"C:\\Windows\\System32\\oemlicense.dll\"")
#print comment(linker, "/export:HrNotifyPhoneLicenseReady=\"C:\\Windows\\System32\\oemlicense.dll\"")
#print comment(linker, "/export:HrRemoveAppxLicense=\"C:\\Windows\\System32\\oemlicense.dll\"")
#print comment(linker, "/export:RemoveDemoAppLicense=\"C:\\Windows\\System32\\oemlicense.dll\"")
