#print comment(linker, "/export:PcaGetFileInfoFromPath=\"C:\\Windows\\System32\\pcacli.dll\"")
#print comment(linker, "/export:PcaIsPcaDisabled=\"C:\\Windows\\System32\\pcacli.dll\"")
#print comment(linker, "/export:PcaLinkChildProcessToParent=\"C:\\Windows\\System32\\pcacli.dll\"")
#print comment(linker, "/export:PcaMonitorProcess=\"C:\\Windows\\System32\\pcacli.dll\"")
#print comment(linker, "/export:PcaMonitorProcess2=\"C:\\Windows\\System32\\pcacli.dll\"")
#print comment(linker, "/export:PcaNotifyMsiInstall=\"C:\\Windows\\System32\\pcacli.dll\"")
#print comment(linker, "/export:PcaNotifyStatusIcon=\"C:\\Windows\\System32\\pcacli.dll\"")
#print comment(linker, "/export:PcaSendToService=\"C:\\Windows\\System32\\pcacli.dll\"")
