#pragma comment(linker, "/export:PcaPatchSdbTask=\"C:\\Windows\\System32\\pcasvc.dll\"")
#pragma comment(linker, "/export:QueryEncapsulationSettings=\"C:\\Windows\\System32\\pcasvc.dll\"")
#pragma comment(linker, "/export:QueryEncapsulationSettingsTC=\"C:\\Windows\\System32\\pcasvc.dll\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\pcasvc.dll\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\pcasvc.dll\"")
