#print comment(linker, "/export:CreatePerceptionSimulationManager=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
#print comment(linker, "/export:CreatePerceptionSimulationRecording=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
#print comment(linker, "/export:GetControlMode=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
#print comment(linker, "/export:GetIsUsingDriver=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
#print comment(linker, "/export:LoadPerceptionSimulationRecording=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
#print comment(linker, "/export:SetControlMode=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
