#pragma comment(linker, "/export:CreatePerceptionSimulationManager=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
#pragma comment(linker, "/export:CreatePerceptionSimulationRecording=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
#pragma comment(linker, "/export:GetControlMode=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
#pragma comment(linker, "/export:GetIsUsingDriver=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
#pragma comment(linker, "/export:LoadPerceptionSimulationRecording=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
#pragma comment(linker, "/export:SetControlMode=\"C:\\Windows\\System32\\PerceptionSimulationManager.dll\"")
