#pragma comment(linker, "/export:CreatePerceptionSimulationManager=\"C:\\Windows\\System32\\PerceptionSimulationManager.CreatePerceptionSimulationManager\"")
#pragma comment(linker, "/export:CreatePerceptionSimulationRecording=\"C:\\Windows\\System32\\PerceptionSimulationManager.CreatePerceptionSimulationRecording\"")
#pragma comment(linker, "/export:GetControlMode=\"C:\\Windows\\System32\\PerceptionSimulationManager.GetControlMode\"")
#pragma comment(linker, "/export:GetIsUsingDriver=\"C:\\Windows\\System32\\PerceptionSimulationManager.GetIsUsingDriver\"")
#pragma comment(linker, "/export:LoadPerceptionSimulationRecording=\"C:\\Windows\\System32\\PerceptionSimulationManager.LoadPerceptionSimulationRecording\"")
#pragma comment(linker, "/export:SetControlMode=\"C:\\Windows\\System32\\PerceptionSimulationManager.SetControlMode\"")
