#pragma comment(linker, "/export:CloseLagPerfData=\"C:\\Windows\\System32\\perfts.dll\"")
#pragma comment(linker, "/export:CloseTSObject=\"C:\\Windows\\System32\\perfts.dll\"")
#pragma comment(linker, "/export:CollectLagPerfData=\"C:\\Windows\\System32\\perfts.dll\"")
#pragma comment(linker, "/export:CollectTSObjectData=\"C:\\Windows\\System32\\perfts.dll\"")
#pragma comment(linker, "/export:OpenLagPerfData=\"C:\\Windows\\System32\\perfts.dll\"")
#pragma comment(linker, "/export:OpenTSObject=\"C:\\Windows\\System32\\perfts.dll\"")
