#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\perftrack.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\perftrack.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\perftrack.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\perftrack.DllUnregisterServer\"")
#pragma comment(linker, "/export:WdiDiagnosticModuleMain=\"C:\\Windows\\System32\\perftrack.WdiDiagnosticModuleMain\"")
#pragma comment(linker, "/export:WdiGetDiagnosticModuleInterfaceVersion=\"C:\\Windows\\System32\\perftrack.WdiGetDiagnosticModuleInterfaceVersion\"")
#pragma comment(linker, "/export:WdiHandleInstance=\"C:\\Windows\\System32\\perftrack.WdiHandleInstance\"")
