#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\photowiz.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\photowiz.dll\"")
#print comment(linker, "/export:DllInstall=\"C:\\Windows\\SysWOW64\\photowiz.dll\"")
#print comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\photowiz.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\photowiz.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\photowiz.dll\"")
#print comment(linker, "/export:UsePPWForPrintTo=\"C:\\Windows\\SysWOW64\\photowiz.dll\"")
