#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\pnpclean.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\pnpclean.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\pnpclean.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\pnpclean.dll\"")
#print comment(linker, "/export:RunDLL_PnpClean=\"C:\\Windows\\System32\\pnpclean.dll\"")
