#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\pnpui.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\pnpui.dll\"")
#pragma comment(linker, "/export:InstallSecurityPrompt=\"C:\\Windows\\System32\\pnpui.dll\"")
#pragma comment(linker, "/export:InstallSecurityPromptLUA=\"C:\\Windows\\System32\\pnpui.dll\"")
#pragma comment(linker, "/export:InstallSecurityPromptRunDllW=\"C:\\Windows\\System32\\pnpui.dll\"")
#pragma comment(linker, "/export:NotifyDevicesNeedRebootRunDllW=\"C:\\Windows\\System32\\pnpui.dll\"")
#pragma comment(linker, "/export:SimplifiedDINotificationW=\"C:\\Windows\\System32\\pnpui.dll\"")
