#pragma comment(linker, "/export:PolicyManagerTranslationProxy_GetPolicyValue=\"C:\\Windows\\System32\\policymanagerprecheck.PolicyManagerTranslationProxy_GetPolicyValue\"")
#pragma comment(linker, "/export:PolicyManagerTranslationProxy_SetPolicyValue=\"C:\\Windows\\System32\\policymanagerprecheck.PolicyManagerTranslationProxy_SetPolicyValue\"")
#pragma comment(linker, "/export:PolicyManager_Apply=\"C:\\Windows\\System32\\policymanagerprecheck.PolicyManager_Apply\"")
#pragma comment(linker, "/export:PolicyManager_PostApply=\"C:\\Windows\\System32\\policymanagerprecheck.PolicyManager_PostApply\"")
#pragma comment(linker, "/export:PolicyManager_PreCheck=\"C:\\Windows\\System32\\policymanagerprecheck.PolicyManager_PreCheck\"")
