#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\PresentationHostProxy.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\PresentationHostProxy.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\PresentationHostProxy.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\PresentationHostProxy.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\PresentationHostProxy.DllUnregisterServer\"")
