#pragma comment(linker, "/export:AsyncUILoaderEntryW=\"C:\\Windows\\System32\\prnntfy.AsyncUILoaderEntryW\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\prnntfy.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\prnntfy.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\prnntfy.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\prnntfy.DllUnregisterServer\"")
#pragma comment(linker, "/export:PrintNotifyTray_Exit=\"C:\\Windows\\System32\\prnntfy.PrintNotifyTray_Exit\"")
#pragma comment(linker, "/export:PrintNotifyTray_Init=\"C:\\Windows\\System32\\prnntfy.PrintNotifyTray_Init\"")
