#pragma comment(linker, "/export:ConnectToRoamingVhdProfile=\"C:\\Windows\\System32\\profsvcext.dll\"")
#pragma comment(linker, "/export:CreateRoamingProviderInstance=\"C:\\Windows\\System32\\profsvcext.dll\"")
#pragma comment(linker, "/export:InitializeSuspendFolderPolicyAndUploadTaskConfig=\"C:\\Windows\\System32\\profsvcext.dll\"")
#pragma comment(linker, "/export:RefreshSuspendFolderPolicyAndUploadTaskConfig=\"C:\\Windows\\System32\\profsvcext.dll\"")
#pragma comment(linker, "/export:StartRoamingClassFactories=\"C:\\Windows\\System32\\profsvcext.dll\"")
#pragma comment(linker, "/export:StopRoamingClassFactories=\"C:\\Windows\\System32\\profsvcext.dll\"")
#pragma comment(linker, "/export:WaitForNetworkForRoamingProfile=\"C:\\Windows\\System32\\profsvcext.dll\"")
