#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\provdatastore.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\provdatastore.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\provdatastore.dll\"")
#pragma comment(linker, "/export:MvDsGetInfoFromMcc=\"C:\\Windows\\System32\\provdatastore.dll\"")
#pragma comment(linker, "/export:MvGetMccFromGeoId=\"C:\\Windows\\System32\\provdatastore.dll\"")
#pragma comment(linker, "/export:ValidateMnc=\"C:\\Windows\\System32\\provdatastore.dll\"")
