#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\provdatastore.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\provdatastore.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\provdatastore.DllGetClassObject\"")
#pragma comment(linker, "/export:MvDsGetInfoFromMcc=\"C:\\Windows\\System32\\provdatastore.MvDsGetInfoFromMcc\"")
#pragma comment(linker, "/export:MvGetMccFromGeoId=\"C:\\Windows\\System32\\provdatastore.MvGetMccFromGeoId\"")
#pragma comment(linker, "/export:ValidateMnc=\"C:\\Windows\\System32\\provdatastore.ValidateMnc\"")
