#pragma comment(linker, "/export:CleanupProximityService=\"C:\\Windows\\System32\\ProximityService.dll\"")
#pragma comment(linker, "/export:GetProximityClientCount=\"C:\\Windows\\System32\\ProximityService.dll\"")
#pragma comment(linker, "/export:InitProximityService=\"C:\\Windows\\System32\\ProximityService.dll\"")
#pragma comment(linker, "/export:InitProximityServiceEx=\"C:\\Windows\\System32\\ProximityService.dll\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\ProximityService.dll\"")
#pragma comment(linker, "/export:SessionChangedEvent=\"C:\\Windows\\System32\\ProximityService.dll\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\ProximityService.dll\"")
