#print comment(linker, "/export:PAL_App2DeviceFindAllPeers=\"C:\\Windows\\SysWOW64\\ProximityRtapiPal.dll\"")
#print comment(linker, "/export:PAL_CheckForApp2DeviceAlternateId=\"C:\\Windows\\SysWOW64\\ProximityRtapiPal.dll\"")
#print comment(linker, "/export:PAL_CheckForBluetoothSupport=\"C:\\Windows\\SysWOW64\\ProximityRtapiPal.dll\"")
#print comment(linker, "/export:PAL_GetCurrentProcessExplicitAppUserModelID=\"C:\\Windows\\SysWOW64\\ProximityRtapiPal.dll\"")
#print comment(linker, "/export:PAL_ParseAppUserModelId=\"C:\\Windows\\SysWOW64\\ProximityRtapiPal.dll\"")
#print comment(linker, "/export:PAL_SetCurrentProcessExplicitAppUserModelID=\"C:\\Windows\\SysWOW64\\ProximityRtapiPal.dll\"")
