#print comment(linker, "/export:PAL_AppHasPackage=\"C:\\Windows\\System32\\ProximityCommonPal.dll\"")
#print comment(linker, "/export:PAL_FreeTransientObjectSecurityAttribute=\"C:\\Windows\\System32\\ProximityCommonPal.dll\"")
#print comment(linker, "/export:PAL_GetAppPlatformQualifier=\"C:\\Windows\\System32\\ProximityCommonPal.dll\"")
#print comment(linker, "/export:PAL_GetSupportedBrowseTypes=\"C:\\Windows\\System32\\ProximityCommonPal.dll\"")
#print comment(linker, "/export:PAL_HoldReferenceUntilAppExit=\"C:\\Windows\\System32\\ProximityCommonPal.dll\"")
#print comment(linker, "/export:PAL_QueryTransientObjectSecurityAttribute=\"C:\\Windows\\System32\\ProximityCommonPal.dll\"")
#print comment(linker, "/export:PAL_RegisterAppSuspendResumeCallback=\"C:\\Windows\\System32\\ProximityCommonPal.dll\"")
#print comment(linker, "/export:PAL_UnregisterAppSuspendResumeCallback=\"C:\\Windows\\System32\\ProximityCommonPal.dll\"")
