#pragma comment(linker, "/export:PAL_App2DeviceFindAllPeers=\"C:\\Windows\\System32\\ProximityRtapiPal.dll\"")
#pragma comment(linker, "/export:PAL_CheckForApp2DeviceAlternateId=\"C:\\Windows\\System32\\ProximityRtapiPal.dll\"")
#pragma comment(linker, "/export:PAL_CheckForBluetoothSupport=\"C:\\Windows\\System32\\ProximityRtapiPal.dll\"")
#pragma comment(linker, "/export:PAL_GetCurrentProcessExplicitAppUserModelID=\"C:\\Windows\\System32\\ProximityRtapiPal.dll\"")
#pragma comment(linker, "/export:PAL_ParseAppUserModelId=\"C:\\Windows\\System32\\ProximityRtapiPal.dll\"")
#pragma comment(linker, "/export:PAL_SetCurrentProcessExplicitAppUserModelID=\"C:\\Windows\\System32\\ProximityRtapiPal.dll\"")
