#print comment(linker, "/export:??0MIFree@@QEAA@PEAX@Z=\"C:\\Windows\\System32\\prvdmofcomp.dll\"")
#print comment(linker, "/export:??1MIFree@@QEAA@XZ=\"C:\\Windows\\System32\\prvdmofcomp.dll\"")
#print comment(linker, "/export:??4MIServer@@QEAAAEAV0@$$QEAV0@@Z=\"C:\\Windows\\System32\\prvdmofcomp.dll\"")
#print comment(linker, "/export:??4MIServer@@QEAAAEAV0@AEBV0@@Z=\"C:\\Windows\\System32\\prvdmofcomp.dll\"")
#print comment(linker, "/export:CompileSchemaToWMI=\"C:\\Windows\\System32\\prvdmofcomp.dll\"")
#print comment(linker, "/export:CreateRegisterParameter=\"C:\\Windows\\System32\\prvdmofcomp.dll\"")
#print comment(linker, "/export:GetProviderSchema=\"C:\\Windows\\System32\\prvdmofcomp.dll\"")
#print comment(linker, "/export:GetProviderSchemaFile=\"C:\\Windows\\System32\\prvdmofcomp.dll\"")
