#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\PSModuleDiscoveryProvider.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\PSModuleDiscoveryProvider.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\PSModuleDiscoveryProvider.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\PSModuleDiscoveryProvider.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\PSModuleDiscoveryProvider.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProviderClassID=\"C:\\Windows\\System32\\PSModuleDiscoveryProvider.GetProviderClassID\"")
#pragma comment(linker, "/export:MI_Main=\"C:\\Windows\\System32\\PSModuleDiscoveryProvider.MI_Main\"")
