#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\pstorec.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\pstorec.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\pstorec.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\pstorec.dll\"")
#print comment(linker, "/export:PStoreCreateInstance=\"C:\\Windows\\System32\\pstorec.dll\"")
#print comment(linker, "/export:PStoreEnumProviders=\"C:\\Windows\\System32\\pstorec.dll\"")
