#print comment(linker, "/export:AMGetErrorTextA=\"C:\\Windows\\System32\\quartz.dll\"")
#print comment(linker, "/export:AMGetErrorTextW=\"C:\\Windows\\System32\\quartz.dll\"")
#print comment(linker, "/export:AmpFactorToDB=\"C:\\Windows\\System32\\quartz.dll\"")
#print comment(linker, "/export:DBToAmpFactor=\"C:\\Windows\\System32\\quartz.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\quartz.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\quartz.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\quartz.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\quartz.dll\"")
