#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\racpldlg.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\racpldlg.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\racpldlg.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\racpldlg.dll\"")
#print comment(linker, "/export:ShowPasswordDialog=\"C:\\Windows\\System32\\racpldlg.dll\"")
