#print comment(linker, "/export:RdrSysprepSpecialize=\"C:\\Windows\\System32\\radardt.dll\"")
#print comment(linker, "/export:RdrSysprepSpecializeOffline=\"C:\\Windows\\System32\\radardt.dll\"")
#print comment(linker, "/export:WdiDiagnosticModuleMain=\"C:\\Windows\\System32\\radardt.dll\"")
#print comment(linker, "/export:WdiGetDiagnosticModuleInterfaceVersion=\"C:\\Windows\\System32\\radardt.dll\"")
#print comment(linker, "/export:WdiHandleInstance=\"C:\\Windows\\System32\\radardt.dll\"")
