#pragma comment(linker, "/export:InitializeProtocolEngine=\"C:\\Windows\\System32\\rascustom.dll\"")
#pragma comment(linker, "/export:SendMessageToProtocolEngine=\"C:\\Windows\\System32\\rascustom.dll\"")
#pragma comment(linker, "/export:UninitializeProtocolEngine=\"C:\\Windows\\System32\\rascustom.dll\"")
#pragma comment(linker, "/export:VpnBrokerPluginIsInstalled=\"C:\\Windows\\System32\\rascustom.dll\"")
#pragma comment(linker, "/export:VpnBrokerRegisterForPluginInstallations=\"C:\\Windows\\System32\\rascustom.dll\"")
#pragma comment(linker, "/export:VpnSmCommsPluginsNotifyLogOff=\"C:\\Windows\\System32\\rascustom.dll\"")
#pragma comment(linker, "/export:VpnSmCommsPluginsRoamToBestCostInterface=\"C:\\Windows\\System32\\rascustom.dll\"")
