#print comment(linker, "/export:NlmGetBestCostNetworkConnection=\"C:\\Windows\\System32\\rasmans.dll\"")
#print comment(linker, "/export:NlmGetCostedNetworkSettings=\"C:\\Windows\\System32\\rasmans.dll\"")
#print comment(linker, "/export:NlmSetCostedNetworkSettings=\"C:\\Windows\\System32\\rasmans.dll\"")
#print comment(linker, "/export:ServiceInitialized=\"C:\\Windows\\System32\\rasmans.dll\"")
#print comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\rasmans.dll\"")
#print comment(linker, "/export:ServiceRequestInProcess=\"C:\\Windows\\System32\\rasmans.dll\"")
#print comment(linker, "/export:VpnProfileMatchingNrpt=\"C:\\Windows\\System32\\rasmans.dll\"")
#print comment(linker, "/export:VpnProfileNrptHasExemptions=\"C:\\Windows\\System32\\rasmans.dll\"")
