#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\rdbui.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\rdbui.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\rdbui.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\rdbui.DllUnregisterServer\"")
#pragma comment(linker, "/export:RDBMgmtLaunchPropertiesW=\"C:\\Windows\\System32\\rdbui.RDBMgmtLaunchPropertiesW\"")
