#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\rdpcorets.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\rdpcorets.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\rdpcorets.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\rdpcorets.dll\"")
#print comment(linker, "/export:RFX_CreateGFXService=\"C:\\Windows\\System32\\rdpcorets.dll\"")
#print comment(linker, "/export:RFX_CreatePluginFactory=\"C:\\Windows\\System32\\rdpcorets.dll\"")
