#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\rdpendp.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\rdpendp.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\rdpendp.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\rdpendp.dll\"")
#pragma comment(linker, "/export:GetTSAudioEndpointEnumeratorForSession=\"C:\\Windows\\System32\\rdpendp.dll\"")
