#print comment(linker, "/export:CreateRdpUdpStreamWrapper=\"C:\\Windows\\System32\\rdpnano.dll\"")
#print comment(linker, "/export:CreateRdpWebSocketStreamWrapper=\"C:\\Windows\\System32\\rdpnano.dll\"")
#print comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\rdpnano.dll\"")
#print comment(linker, "/export:FreeRdpUdpStreamWrapper=\"C:\\Windows\\System32\\rdpnano.dll\"")
#print comment(linker, "/export:FreeRdpWebSocketStreamWrapper=\"C:\\Windows\\System32\\rdpnano.dll\"")
