#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\RdpRelayTransport.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\RdpRelayTransport.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\RdpRelayTransport.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\RdpRelayTransport.dll\"")
#pragma comment(linker, "/export:RDPAPI_CreateInstance=\"C:\\Windows\\System32\\RdpRelayTransport.dll\"")
