#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\RDXService.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\RDXService.dll\"")
#print comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\RDXService.dll\"")
#print comment(linker, "/export:OpenRDXDocumentW=\"C:\\Windows\\System32\\RDXService.dll\"")
#print comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\RDXService.dll\"")
