#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\remotepg.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\remotepg.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\remotepg.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\remotepg.DllUnregisterServer\"")
#pragma comment(linker, "/export:LaunchRemoteUsersDialog=\"C:\\Windows\\System32\\remotepg.LaunchRemoteUsersDialog\"")
