#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\rshx32.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\rshx32.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\rshx32.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\rshx32.dll\"")
#print comment(linker, "/export:EditFSSecurity=\"C:\\Windows\\System32\\rshx32.dll\"")
