#print comment(linker, "/export:MediaVRCreateORTCRenderer=\"C:\\Windows\\System32\\rtmmvrortc.dll\"")
#print comment(linker, "/export:MediaVRDestroyORTCRenderer=\"C:\\Windows\\System32\\rtmmvrortc.dll\"")
#print comment(linker, "/export:MediaVRGetORTCRenderContext=\"C:\\Windows\\System32\\rtmmvrortc.dll\"")
#print comment(linker, "/export:MediaVRRequestKeyFrame=\"C:\\Windows\\System32\\rtmmvrortc.dll\"")
#print comment(linker, "/export:MediaVRSetDecodingHealth=\"C:\\Windows\\System32\\rtmmvrortc.dll\"")
