#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\scansetting.dll\"")
#print comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\scansetting.dll\"")
#print comment(linker, "/export:GetDefaultProfileScan=\"C:\\Windows\\System32\\scansetting.dll\"")
#print comment(linker, "/export:GetImageDialog=\"C:\\Windows\\System32\\scansetting.dll\"")
#print comment(linker, "/export:ProfilesDialog=\"C:\\Windows\\System32\\scansetting.dll\"")
#print comment(linker, "/export:ProgDlgTakeFgIfShowing=\"C:\\Windows\\System32\\scansetting.dll\"")
