#print comment(linker, "/export:GetOpenCardNameA=\"C:\\Windows\\System32\\SCardDlg.dll\"")
#print comment(linker, "/export:GetOpenCardNameW=\"C:\\Windows\\System32\\SCardDlg.dll\"")
#print comment(linker, "/export:SCardDlgExtendedError=\"C:\\Windows\\System32\\SCardDlg.dll\"")
#print comment(linker, "/export:SCardUIDlgSelectCardA=\"C:\\Windows\\System32\\SCardDlg.dll\"")
#print comment(linker, "/export:SCardUIDlgSelectCardW=\"C:\\Windows\\System32\\SCardDlg.dll\"")
