#pragma comment(linker, "/export:GetOpenCardNameA=\"C:\\Windows\\System32\\SCardDlg.GetOpenCardNameA\"")
#pragma comment(linker, "/export:GetOpenCardNameW=\"C:\\Windows\\System32\\SCardDlg.GetOpenCardNameW\"")
#pragma comment(linker, "/export:SCardDlgExtendedError=\"C:\\Windows\\System32\\SCardDlg.SCardDlgExtendedError\"")
#pragma comment(linker, "/export:SCardUIDlgSelectCardA=\"C:\\Windows\\System32\\SCardDlg.SCardUIDlgSelectCardA\"")
#pragma comment(linker, "/export:SCardUIDlgSelectCardW=\"C:\\Windows\\System32\\SCardDlg.SCardUIDlgSelectCardW\"")
