#print comment(linker, "/export:DLLGetDocumentation=\"C:\\Windows\\SysWOW64\\scrrun.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\scrrun.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\scrrun.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\scrrun.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\scrrun.dll\"")
#print comment(linker, "/export:DoOpenPipeStream=\"C:\\Windows\\SysWOW64\\scrrun.dll\"")
