#pragma comment(linker, "/export:DLLGetDocumentation=\"C:\\Windows\\System32\\scrrun.DLLGetDocumentation\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\scrrun.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\scrrun.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\scrrun.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\scrrun.DllUnregisterServer\"")
#pragma comment(linker, "/export:DoOpenPipeStream=\"C:\\Windows\\System32\\scrrun.DoOpenPipeStream\"")
