#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\sdengin2.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\sdengin2.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\sdengin2.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\sdengin2.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\sdengin2.dll\"")
#pragma comment(linker, "/export:ExecuteScheduledBackup=\"C:\\Windows\\System32\\sdengin2.dll\"")
#pragma comment(linker, "/export:SdCheck=\"C:\\Windows\\System32\\sdengin2.dll\"")
