#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\sdrsvc.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\sdrsvc.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\sdrsvc.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\sdrsvc.DllUnregisterServer\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\sdrsvc.ServiceMain\"")
