#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\SEMgrSvc.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\SEMgrSvc.dll\"")
#pragma comment(linker, "/export:LaunchModernNfcEventSession=\"C:\\Windows\\System32\\SEMgrSvc.dll\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\SEMgrSvc.dll\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\SEMgrSvc.dll\"")
