#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\SensorsClassExtension.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\SensorsClassExtension.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\SensorsClassExtension.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\SensorsClassExtension.dll\"")
#pragma comment(linker, "/export:Microsoft_WDF_UMDF_Version=\"C:\\Windows\\System32\\SensorsClassExtension.dll\"")
