#print comment(linker, "/export:drvCommConfigDialogA=\"C:\\Windows\\SysWOW64\\serialui.dll\"")
#print comment(linker, "/export:drvCommConfigDialogW=\"C:\\Windows\\SysWOW64\\serialui.dll\"")
#print comment(linker, "/export:drvGetDefaultCommConfigA=\"C:\\Windows\\SysWOW64\\serialui.dll\"")
#print comment(linker, "/export:drvGetDefaultCommConfigW=\"C:\\Windows\\SysWOW64\\serialui.dll\"")
#print comment(linker, "/export:drvSetDefaultCommConfigA=\"C:\\Windows\\SysWOW64\\serialui.dll\"")
#print comment(linker, "/export:drvSetDefaultCommConfigW=\"C:\\Windows\\SysWOW64\\serialui.dll\"")
