#print comment(linker, "/export:drvCommConfigDialogA=\"C:\\Windows\\System32\\serialui.dll\"")
#print comment(linker, "/export:drvCommConfigDialogW=\"C:\\Windows\\System32\\serialui.dll\"")
#print comment(linker, "/export:drvGetDefaultCommConfigA=\"C:\\Windows\\System32\\serialui.dll\"")
#print comment(linker, "/export:drvGetDefaultCommConfigW=\"C:\\Windows\\System32\\serialui.dll\"")
#print comment(linker, "/export:drvSetDefaultCommConfigA=\"C:\\Windows\\System32\\serialui.dll\"")
#print comment(linker, "/export:drvSetDefaultCommConfigW=\"C:\\Windows\\System32\\serialui.dll\"")
