#pragma comment(linker, "/export:SRSetRestorePoint=\"C:\\Windows\\System32\\sfc.dll\"")
#pragma comment(linker, "/export:SRSetRestorePointA=\"C:\\Windows\\System32\\sfc.dll\"")
#pragma comment(linker, "/export:SRSetRestorePointW=\"C:\\Windows\\System32\\sfc.dll\"")
#pragma comment(linker, "/export:SfcGetNextProtectedFile=\"C:\\Windows\\System32\\sfc.dll\"")
#pragma comment(linker, "/export:SfcIsFileProtected=\"C:\\Windows\\System32\\sfc.dll\"")
#pragma comment(linker, "/export:SfcIsKeyProtected=\"C:\\Windows\\System32\\sfc.dll\"")
#pragma comment(linker, "/export:SfpVerifyFile=\"C:\\Windows\\System32\\sfc.dll\"")
