#print comment(linker, "/export:SHUnattendedSetup=\"C:\\Windows\\System32\\shsetup.dll\"")
#print comment(linker, "/export:SHUnattendedSetupA=\"C:\\Windows\\System32\\shsetup.dll\"")
#print comment(linker, "/export:SHUnattendedSetupW=\"C:\\Windows\\System32\\shsetup.dll\"")
#print comment(linker, "/export:Sysprep_Cleanup_Shell=\"C:\\Windows\\System32\\shsetup.dll\"")
#print comment(linker, "/export:Sysprep_Generalize_Shell=\"C:\\Windows\\System32\\shsetup.dll\"")
