#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\smartscreenps.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\smartscreenps.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\smartscreenps.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\smartscreenps.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\smartscreenps.DllUnregisterServer\"")
