#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\smbwmiv2.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\smbwmiv2.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\smbwmiv2.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\smbwmiv2.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\smbwmiv2.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProviderClassID=\"C:\\Windows\\System32\\smbwmiv2.GetProviderClassID\"")
#pragma comment(linker, "/export:MI_Main=\"C:\\Windows\\System32\\smbwmiv2.MI_Main\"")
