#pragma comment(linker, "/export:Sysprep_Clean_Opk=\"C:\\Windows\\System32\\spopk.Sysprep_Clean_Opk\"")
#pragma comment(linker, "/export:Sysprep_Clean_Validate_Opk=\"C:\\Windows\\System32\\spopk.Sysprep_Clean_Validate_Opk\"")
#pragma comment(linker, "/export:Sysprep_Generalize_Opk=\"C:\\Windows\\System32\\spopk.Sysprep_Generalize_Opk\"")
#pragma comment(linker, "/export:Sysprep_Offline_Specialize_Opk=\"C:\\Windows\\System32\\spopk.Sysprep_Offline_Specialize_Opk\"")
#pragma comment(linker, "/export:Sysprep_Online_Specialize_Opk=\"C:\\Windows\\System32\\spopk.Sysprep_Online_Specialize_Opk\"")
