#print comment(linker, "/export:SppPluginCanUnloadNow=\"C:\\Windows\\System32\\sppwinob.dll\"")
#print comment(linker, "/export:SppPluginCreateInstance=\"C:\\Windows\\System32\\sppwinob.dll\"")
#print comment(linker, "/export:SppPluginInitialize=\"C:\\Windows\\System32\\sppwinob.dll\"")
#print comment(linker, "/export:SppPluginShutdown=\"C:\\Windows\\System32\\sppwinob.dll\"")
#print comment(linker, "/export:SppPluginVersion=\"C:\\Windows\\System32\\sppwinob.dll\"")
