#pragma comment(linker, "/export:SppPluginCanUnloadNow=\"C:\\Windows\\System32\\sppwinob.SppPluginCanUnloadNow\"")
#pragma comment(linker, "/export:SppPluginCreateInstance=\"C:\\Windows\\System32\\sppwinob.SppPluginCreateInstance\"")
#pragma comment(linker, "/export:SppPluginInitialize=\"C:\\Windows\\System32\\sppwinob.SppPluginInitialize\"")
#pragma comment(linker, "/export:SppPluginShutdown=\"C:\\Windows\\System32\\sppwinob.SppPluginShutdown\"")
#pragma comment(linker, "/export:SppPluginVersion=\"C:\\Windows\\System32\\sppwinob.SppPluginVersion\"")
