#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\srcore.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\srcore.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\srcore.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\srcore.DllUnregisterServer\"")
#pragma comment(linker, "/export:ShutdownContinuation=\"C:\\Windows\\System32\\srcore.ShutdownContinuation\"")
#pragma comment(linker, "/export:SrFreeRestoreStatus=\"C:\\Windows\\System32\\srcore.SrFreeRestoreStatus\"")
#pragma comment(linker, "/export:SrFreeRpPropArray=\"C:\\Windows\\System32\\srcore.SrFreeRpPropArray\"")
