#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\srcore.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\srcore.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\srcore.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\srcore.dll\"")
#print comment(linker, "/export:ShutdownContinuation=\"C:\\Windows\\System32\\srcore.dll\"")
#print comment(linker, "/export:SrFreeRestoreStatus=\"C:\\Windows\\System32\\srcore.dll\"")
#print comment(linker, "/export:SrFreeRpPropArray=\"C:\\Windows\\System32\\srcore.dll\"")
