#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\srm_ps.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\srm_ps.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\srm_ps.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\srm_ps.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\srm_ps.GetProxyDllInfo\"")
