#pragma comment(linker, "/export:SspiSrvClientCallback=\"C:\\Windows\\System32\\sspisrv.dll\"")
#pragma comment(linker, "/export:SspiSrvInitialize=\"C:\\Windows\\System32\\sspisrv.dll\"")
#pragma comment(linker, "/export:SspirAcquireCredentialsHandle=\"C:\\Windows\\System32\\sspisrv.dll\"")
#pragma comment(linker, "/export:SspirDeleteSecurityContext=\"C:\\Windows\\System32\\sspisrv.dll\"")
#pragma comment(linker, "/export:SspirProcessSecurityContext=\"C:\\Windows\\System32\\sspisrv.dll\"")
