#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\StartTileData.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\StartTileData.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\StartTileData.dll\"")
#print comment(linker, "/export:GetSetting=\"C:\\Windows\\System32\\StartTileData.dll\"")
#print comment(linker, "/export:HasMigratedTDLData=\"C:\\Windows\\System32\\StartTileData.dll\"")
#print comment(linker, "/export:TryMigrateTDLData=\"C:\\Windows\\System32\\StartTileData.dll\"")
