#print comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\Startupscan.dll\"")
#print comment(linker, "/export:SusResetNotification=\"C:\\Windows\\System32\\Startupscan.dll\"")
#print comment(linker, "/export:SusRunOEMTaskOffline=\"C:\\Windows\\System32\\Startupscan.dll\"")
#print comment(linker, "/export:SusRunOEMTaskOnline=\"C:\\Windows\\System32\\Startupscan.dll\"")
#print comment(linker, "/export:SusRunTask=\"C:\\Windows\\System32\\Startupscan.dll\"")
