#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\StorSvc.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\StorSvc.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\StorSvc.dll\"")
#print comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\StorSvc.dll\"")
#print comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\StorSvc.dll\"")
