#print comment(linker, "/export:StreamingDeviceClassInstaller=\"C:\\Windows\\System32\\streamci.dll\"")
#print comment(linker, "/export:StreamingDeviceRemove=\"C:\\Windows\\System32\\streamci.dll\"")
#print comment(linker, "/export:StreamingDeviceRemoveA=\"C:\\Windows\\System32\\streamci.dll\"")
#print comment(linker, "/export:StreamingDeviceRemoveW=\"C:\\Windows\\System32\\streamci.dll\"")
#print comment(linker, "/export:StreamingDeviceSetup=\"C:\\Windows\\System32\\streamci.dll\"")
#print comment(linker, "/export:StreamingDeviceSetupA=\"C:\\Windows\\System32\\streamci.dll\"")
#print comment(linker, "/export:StreamingDeviceSetupW=\"C:\\Windows\\System32\\streamci.dll\"")
#print comment(linker, "/export:SwEnumCoInstaller=\"C:\\Windows\\System32\\streamci.dll\"")
