#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\swprv.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\swprv.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\swprv.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\swprv.DllUnregisterServer\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\swprv.ServiceMain\"")
