#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\SyncInfrastructureps.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\SyncInfrastructureps.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\SyncInfrastructureps.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\SyncInfrastructureps.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\SyncInfrastructureps.GetProxyDllInfo\"")
