#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\TapiMigPlugin.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\TapiMigPlugin.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\TapiMigPlugin.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\TapiMigPlugin.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\TapiMigPlugin.DllUnregisterServer\"")
