#pragma comment(linker, "/export:DeleteTaskNotification=\"C:\\Windows\\System32\\taskcomp.dll\"")
#pragma comment(linker, "/export:InitializeAdapter=\"C:\\Windows\\System32\\taskcomp.dll\"")
#pragma comment(linker, "/export:IsRegistering=\"C:\\Windows\\System32\\taskcomp.dll\"")
#pragma comment(linker, "/export:RegisterTaskNotification=\"C:\\Windows\\System32\\taskcomp.dll\"")
#pragma comment(linker, "/export:SetSdNotification=\"C:\\Windows\\System32\\taskcomp.dll\"")
#pragma comment(linker, "/export:ShutdownAdapter=\"C:\\Windows\\System32\\taskcomp.dll\"")
#pragma comment(linker, "/export:UpdateJobStatus=\"C:\\Windows\\System32\\taskcomp.dll\"")
