#pragma comment(linker, "/export:OslGenRandomBytes=\"C:\\Windows\\System32\\tcbloader.OslGenRandomBytes\"")
#pragma comment(linker, "/export:OslGetControlSubkeyCell=\"C:\\Windows\\System32\\tcbloader.OslGetControlSubkeyCell\"")
#pragma comment(linker, "/export:OslGetExportRoutineInModule=\"C:\\Windows\\System32\\tcbloader.OslGetExportRoutineInModule\"")
#pragma comment(linker, "/export:OslGetStringValue=\"C:\\Windows\\System32\\tcbloader.OslGetStringValue\"")
#pragma comment(linker, "/export:OslGetValue=\"C:\\Windows\\System32\\tcbloader.OslGetValue\"")
#pragma comment(linker, "/export:OslIsRunningInSecureKernel=\"C:\\Windows\\System32\\tcbloader.OslIsRunningInSecureKernel\"")
#pragma comment(linker, "/export:TcbLoadEntry=\"C:\\Windows\\System32\\tcbloader.TcbLoadEntry\"")
#pragma comment(linker, "/export:TcbResumeEntry=\"C:\\Windows\\System32\\tcbloader.TcbResumeEntry\"")
