#pragma comment(linker, "/export:FreeTimeStatusInfo=\"C:\\Windows\\System32\\timesync.FreeTimeStatusInfo\"")
#pragma comment(linker, "/export:GetTimeStatusInfo=\"C:\\Windows\\System32\\timesync.GetTimeStatusInfo\"")
#pragma comment(linker, "/export:SetNTPSync=\"C:\\Windows\\System32\\timesync.SetNTPSync\"")
#pragma comment(linker, "/export:StartTimeService=\"C:\\Windows\\System32\\timesync.StartTimeService\"")
#pragma comment(linker, "/export:SyncW32Time=\"C:\\Windows\\System32\\timesync.SyncW32Time\"")
