#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\TransportDSA.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\TransportDSA.DllGetClassObject\"")
#pragma comment(linker, "/export:DllInstall=\"C:\\Windows\\System32\\TransportDSA.DllInstall\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\TransportDSA.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\TransportDSA.DllUnregisterServer\"")
