#pragma comment(linker, "/export:CreateModernAppToDelete=\"C:\\Windows\\System32\\ttdplm.dll\"")
#pragma comment(linker, "/export:CreateModernAppToTrace=\"C:\\Windows\\System32\\ttdplm.dll\"")
#pragma comment(linker, "/export:GetMaxPackageNameLength=\"C:\\Windows\\System32\\ttdplm.dll\"")
#pragma comment(linker, "/export:GetPackageFromPid=\"C:\\Windows\\System32\\ttdplm.dll\"")
#pragma comment(linker, "/export:SetPermisionsForFolder=\"C:\\Windows\\System32\\ttdplm.dll\"")
