#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\TtlsAuth.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\TtlsAuth.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\TtlsAuth.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\TtlsAuth.dll\"")
#print comment(linker, "/export:EapPeerFreeErrorMemory=\"C:\\Windows\\System32\\TtlsAuth.dll\"")
#print comment(linker, "/export:EapPeerFreeMemory=\"C:\\Windows\\System32\\TtlsAuth.dll\"")
#print comment(linker, "/export:EapPeerGetInfo=\"C:\\Windows\\System32\\TtlsAuth.dll\"")
