#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\UiaManager.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\UiaManager.dll\"")
#print comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\UiaManager.dll\"")
#print comment(linker, "/export:UiaInitCrossMachineConnection=\"C:\\Windows\\System32\\UiaManager.dll\"")
#print comment(linker, "/export:UiaInitCrossMachineConnectionW=\"C:\\Windows\\System32\\UiaManager.dll\"")
