#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\upnp.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\upnp.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\upnp.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\upnp.dll\"")
#print comment(linker, "/export:HrRehydratorCreateServiceObject=\"C:\\Windows\\SysWOW64\\upnp.dll\"")
