#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\usbceip.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\usbceip.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\usbceip.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\usbceip.DllUnregisterServer\"")
#pragma comment(linker, "/export:UsbCeip_Execute=\"C:\\Windows\\System32\\usbceip.UsbCeip_Execute\"")
