#print comment(linker, "/export:UsbPm_AssignConnectorPowerLevel=\"C:\\Windows\\System32\\UsbPmApi.dll\"")
#print comment(linker, "/export:UsbPm_Deregister=\"C:\\Windows\\System32\\UsbPmApi.dll\"")
#print comment(linker, "/export:UsbPm_Register=\"C:\\Windows\\System32\\UsbPmApi.dll\"")
#print comment(linker, "/export:UsbPm_RetrieveConnectorProperties=\"C:\\Windows\\System32\\UsbPmApi.dll\"")
#print comment(linker, "/export:UsbPm_RetrieveConnectorState=\"C:\\Windows\\System32\\UsbPmApi.dll\"")
#print comment(linker, "/export:UsbPm_RetrieveHubConnectorHandles=\"C:\\Windows\\System32\\UsbPmApi.dll\"")
#print comment(linker, "/export:UsbPm_RetrieveHubProperties=\"C:\\Windows\\System32\\UsbPmApi.dll\"")
