#pragma comment(linker, "/export:UsbPm_AssignConnectorPowerLevel=\"C:\\Windows\\System32\\UsbPmApi.UsbPm_AssignConnectorPowerLevel\"")
#pragma comment(linker, "/export:UsbPm_Deregister=\"C:\\Windows\\System32\\UsbPmApi.UsbPm_Deregister\"")
#pragma comment(linker, "/export:UsbPm_Register=\"C:\\Windows\\System32\\UsbPmApi.UsbPm_Register\"")
#pragma comment(linker, "/export:UsbPm_RetrieveConnectorProperties=\"C:\\Windows\\System32\\UsbPmApi.UsbPm_RetrieveConnectorProperties\"")
#pragma comment(linker, "/export:UsbPm_RetrieveConnectorState=\"C:\\Windows\\System32\\UsbPmApi.UsbPm_RetrieveConnectorState\"")
#pragma comment(linker, "/export:UsbPm_RetrieveHubConnectorHandles=\"C:\\Windows\\System32\\UsbPmApi.UsbPm_RetrieveHubConnectorHandles\"")
#pragma comment(linker, "/export:UsbPm_RetrieveHubProperties=\"C:\\Windows\\System32\\UsbPmApi.UsbPm_RetrieveHubProperties\"")
