#pragma comment(linker, "/export:CleanupUDSGlobals=\"C:\\Windows\\System32\\UserDataService.dll\"")
#pragma comment(linker, "/export:CreateInprocConnectionHandle=\"C:\\Windows\\System32\\UserDataService.dll\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\UserDataService.dll\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\UserDataService.dll\"")
#pragma comment(linker, "/export:TeardownInprocConnectionHandle=\"C:\\Windows\\System32\\UserDataService.dll\"")
