#pragma comment(linker, "/export:GetServicingModeState=\"C:\\Windows\\System32\\uwfservicingapi.dll\"")
#pragma comment(linker, "/export:SetServicingModeState=\"C:\\Windows\\System32\\uwfservicingapi.dll\"")
#pragma comment(linker, "/export:UwfServicingCleanup=\"C:\\Windows\\System32\\uwfservicingapi.dll\"")
#pragma comment(linker, "/export:UwfServicingInitialize=\"C:\\Windows\\System32\\uwfservicingapi.dll\"")
#pragma comment(linker, "/export:UwfServicingWinUpdateApply=\"C:\\Windows\\System32\\uwfservicingapi.dll\"")
#pragma comment(linker, "/export:UwfServicingWinupdateCleanup=\"C:\\Windows\\System32\\uwfservicingapi.dll\"")
#pragma comment(linker, "/export:UwfServicingWinupdateInitialize=\"C:\\Windows\\System32\\uwfservicingapi.dll\"")
