#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\vds_ps.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\vds_ps.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\vds_ps.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\vds_ps.dll\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\vds_ps.dll\"")
