#pragma comment(linker, "/export:VhfAsyncOperationComplete=\"C:\\Windows\\System32\\VhfUm.dll\"")
#pragma comment(linker, "/export:VhfCreate=\"C:\\Windows\\System32\\VhfUm.dll\"")
#pragma comment(linker, "/export:VhfDelete=\"C:\\Windows\\System32\\VhfUm.dll\"")
#pragma comment(linker, "/export:VhfReadReportSubmit=\"C:\\Windows\\System32\\VhfUm.dll\"")
#pragma comment(linker, "/export:VhfStart=\"C:\\Windows\\System32\\VhfUm.dll\"")
