#print comment(linker, "/export:CreateInstance=\"C:\\Windows\\System32\\VIDRESZR.DLL\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\VIDRESZR.DLL\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\VIDRESZR.DLL\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\VIDRESZR.DLL\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\VIDRESZR.DLL\"")
