#pragma comment(linker, "/export:VM3DGLHelperCleanup=\"C:\\Windows\\System32\\vm3dglhelper64.VM3DGLHelperCleanup\"")
#pragma comment(linker, "/export:VM3DGLHelperDevLog=\"C:\\Windows\\System32\\vm3dglhelper64.VM3DGLHelperDevLog\"")
#pragma comment(linker, "/export:VM3DGLHelperGetDevCapMaxCount=\"C:\\Windows\\System32\\vm3dglhelper64.VM3DGLHelperGetDevCapMaxCount\"")
#pragma comment(linker, "/export:VM3DGLHelperInit=\"C:\\Windows\\System32\\vm3dglhelper64.VM3DGLHelperInit\"")
#pragma comment(linker, "/export:VM3DGLHelperLog=\"C:\\Windows\\System32\\vm3dglhelper64.VM3DGLHelperLog\"")
#pragma comment(linker, "/export:VM3DGLHelperRLog=\"C:\\Windows\\System32\\vm3dglhelper64.VM3DGLHelperRLog\"")
#pragma comment(linker, "/export:VM3DGLHelperSetLogLevels=\"C:\\Windows\\System32\\vm3dglhelper64.VM3DGLHelperSetLogLevels\"")
