#pragma comment(linker, "/export:VM3DGLHelperCleanup=\"C:\\Windows\\System32\\vm3dglhelper64.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperDevLog=\"C:\\Windows\\System32\\vm3dglhelper64.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperGetDevCapMaxCount=\"C:\\Windows\\System32\\vm3dglhelper64.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperInit=\"C:\\Windows\\System32\\vm3dglhelper64.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperLog=\"C:\\Windows\\System32\\vm3dglhelper64.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperRLog=\"C:\\Windows\\System32\\vm3dglhelper64.dll\"")
#pragma comment(linker, "/export:VM3DGLHelperSetLogLevels=\"C:\\Windows\\System32\\vm3dglhelper64.dll\"")
