#print comment(linker, "/export:InitializeProtocolEngine=\"C:\\Windows\\System32\\vpnike.dll\"")
#print comment(linker, "/export:InitializeServerProtocolEngine=\"C:\\Windows\\System32\\vpnike.dll\"")
#print comment(linker, "/export:SendMessageToProtocolEngine=\"C:\\Windows\\System32\\vpnike.dll\"")
#print comment(linker, "/export:UninitializeProtocolEngine=\"C:\\Windows\\System32\\vpnike.dll\"")
#print comment(linker, "/export:UninitializeServerProtocolEngine=\"C:\\Windows\\System32\\vpnike.dll\"")
#print comment(linker, "/export:VpnIkeRoamToBestCostInterface=\"C:\\Windows\\System32\\vpnike.dll\"")
