#pragma comment(linker, "/export:OutOfProcessExceptionEventCallback=\"C:\\Windows\\System32\\wbiosrvc.OutOfProcessExceptionEventCallback\"")
#pragma comment(linker, "/export:OutOfProcessExceptionEventDebuggerLaunchCallback=\"C:\\Windows\\System32\\wbiosrvc.OutOfProcessExceptionEventDebuggerLaunchCallback\"")
#pragma comment(linker, "/export:OutOfProcessExceptionEventSignatureCallback=\"C:\\Windows\\System32\\wbiosrvc.OutOfProcessExceptionEventSignatureCallback\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\wbiosrvc.ServiceMain\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\wbiosrvc.SvchostPushServiceGlobals\"")
