#print comment(linker, "/export:OutOfProcessExceptionEventCallback=\"C:\\Windows\\System32\\wbiosrvc.dll\"")
#print comment(linker, "/export:OutOfProcessExceptionEventDebuggerLaunchCallback=\"C:\\Windows\\System32\\wbiosrvc.dll\"")
#print comment(linker, "/export:OutOfProcessExceptionEventSignatureCallback=\"C:\\Windows\\System32\\wbiosrvc.dll\"")
#print comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\wbiosrvc.dll\"")
#print comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\wbiosrvc.dll\"")
