#pragma comment(linker, "/export:EthernetCspDeInit=\"C:\\Windows\\System32\\wcmcsp.EthernetCspDeInit\"")
#pragma comment(linker, "/export:EthernetCspInit=\"C:\\Windows\\System32\\wcmcsp.EthernetCspInit\"")
#pragma comment(linker, "/export:WlanCspDeInit=\"C:\\Windows\\System32\\wcmcsp.WlanCspDeInit\"")
#pragma comment(linker, "/export:WlanCspInit=\"C:\\Windows\\System32\\wcmcsp.WlanCspInit\"")
#pragma comment(linker, "/export:WwanCspDeInit=\"C:\\Windows\\System32\\wcmcsp.WwanCspDeInit\"")
#pragma comment(linker, "/export:WwanCspInit=\"C:\\Windows\\System32\\wcmcsp.WwanCspInit\"")
