#pragma comment(linker, "/export:CdeGetProfileList=\"C:\\Windows\\System32\\wcmsvc.dll\"")
#pragma comment(linker, "/export:CdeQueryParameter=\"C:\\Windows\\System32\\wcmsvc.dll\"")
#pragma comment(linker, "/export:CdeSetParameter=\"C:\\Windows\\System32\\wcmsvc.dll\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\wcmsvc.dll\"")
#pragma comment(linker, "/export:WcmSvcMain=\"C:\\Windows\\System32\\wcmsvc.dll\"")
