#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\wdc.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wdc.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\wdc.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\wdc.dll\"")
#print comment(linker, "/export:WdcParseLegacyFile=\"C:\\Windows\\System32\\wdc.dll\"")
#print comment(linker, "/export:WdcRunTaskAsInteractiveUser=\"C:\\Windows\\System32\\wdc.dll\"")
