#pragma comment(linker, "/export:CreateMessagePortEventDispatcher=\"C:\\Windows\\System32\\WebRuntimeManager.CreateMessagePortEventDispatcher\"")
#pragma comment(linker, "/export:CreateServiceWorkerClientMessageDispatcher=\"C:\\Windows\\System32\\WebRuntimeManager.CreateServiceWorkerClientMessageDispatcher\"")
#pragma comment(linker, "/export:CreateWebRuntimeFactory=\"C:\\Windows\\System32\\WebRuntimeManager.CreateWebRuntimeFactory\"")
#pragma comment(linker, "/export:CreateWebRuntimeNotificationFromEventArg=\"C:\\Windows\\System32\\WebRuntimeManager.CreateWebRuntimeNotificationFromEventArg\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\WebRuntimeManager.DllGetActivationFactory\"")
#pragma comment(linker, "/export:EnsureServiceWorkerManagerComponent=\"C:\\Windows\\System32\\WebRuntimeManager.EnsureServiceWorkerManagerComponent\"")
