#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\wercplsupport.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wercplsupport.dll\"")
#print comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\wercplsupport.dll\"")
#print comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\wercplsupport.dll\"")
#print comment(linker, "/export:WerComGetAdminStores=\"C:\\Windows\\System32\\wercplsupport.dll\"")
