#print comment(linker, "/export:CloseFindContext=\"C:\\Windows\\System32\\wiadss.dll\"")
#print comment(linker, "/export:FindFirstImportDS=\"C:\\Windows\\System32\\wiadss.dll\"")
#print comment(linker, "/export:FindImportDSByDeviceName=\"C:\\Windows\\System32\\wiadss.dll\"")
#print comment(linker, "/export:FindNextImportDS=\"C:\\Windows\\System32\\wiadss.dll\"")
#print comment(linker, "/export:GetLoaderStatus=\"C:\\Windows\\System32\\wiadss.dll\"")
#print comment(linker, "/export:LoadImportDS=\"C:\\Windows\\System32\\wiadss.dll\"")
#print comment(linker, "/export:UnloadImportDS=\"C:\\Windows\\System32\\wiadss.dll\"")
