#pragma comment(linker, "/export:WIATRACE_DecrementIndentLevel=\"C:\\Windows\\System32\\wiatrace.dll\"")
#pragma comment(linker, "/export:WIATRACE_GetIndentLevel=\"C:\\Windows\\System32\\wiatrace.dll\"")
#pragma comment(linker, "/export:WIATRACE_GetTraceSettings=\"C:\\Windows\\System32\\wiatrace.dll\"")
#pragma comment(linker, "/export:WIATRACE_IncrementIndentLevel=\"C:\\Windows\\System32\\wiatrace.dll\"")
#pragma comment(linker, "/export:WIATRACE_Init=\"C:\\Windows\\System32\\wiatrace.dll\"")
#pragma comment(linker, "/export:WIATRACE_OutputString=\"C:\\Windows\\System32\\wiatrace.dll\"")
#pragma comment(linker, "/export:WIATRACE_SetTraceSettings=\"C:\\Windows\\System32\\wiatrace.dll\"")
#pragma comment(linker, "/export:WIATRACE_Term=\"C:\\Windows\\System32\\wiatrace.dll\"")
