#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.UI.Xaml.InkControls.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.UI.Xaml.InkControls.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.UI.Xaml.InkControls.dll\"")
#print comment(linker, "/export:GetDependencyLocatorStorage=\"C:\\Windows\\System32\\Windows.UI.Xaml.InkControls.dll\"")
#print comment(linker, "/export:XamlTestHookFreeInkControlsResourceLibrary=\"C:\\Windows\\System32\\Windows.UI.Xaml.InkControls.dll\"")
