#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Mirage.Internal.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Mirage.Internal.dll\"")
#print comment(linker, "/export:DllGetActivationFactoryMirageInternal=\"C:\\Windows\\System32\\Windows.Mirage.Internal.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Mirage.Internal.dll\"")
#print comment(linker, "/export:InjectDependencyInternal=\"C:\\Windows\\System32\\Windows.Mirage.Internal.dll\"")
