#print comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\Windows.StateRepository.dll\"")
#print comment(linker, "/export:StateRepository_DataAccessLayer_DatabaseCache_Add=\"C:\\Windows\\System32\\Windows.StateRepository.dll\"")
#print comment(linker, "/export:StateRepository_DataAccessLayer_DatabaseCache_Get=\"C:\\Windows\\System32\\Windows.StateRepository.dll\"")
#print comment(linker, "/export:StateRepository_Initialize=\"C:\\Windows\\System32\\Windows.StateRepository.dll\"")
#print comment(linker, "/export:StateRepository_Service_UpdateStatus=\"C:\\Windows\\System32\\Windows.StateRepository.dll\"")
#print comment(linker, "/export:StateRepository_Shutdown=\"C:\\Windows\\System32\\Windows.StateRepository.dll\"")
#print comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\Windows.StateRepository.dll\"")
