#pragma comment(linker, "/export:BootstrapReleaseUnusedResources=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.BootstrapReleaseUnusedResources\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.DllGetClassObject\"")
#pragma comment(linker, "/export:MSPRMFDllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.MSPRMFDllCanUnloadNow\"")
#pragma comment(linker, "/export:MSPRMFGetClassObject=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.MSPRMFGetClassObject\"")
