#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Data.Activities.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Data.Activities.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Data.Activities.dll\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\Windows.Data.Activities.dll\"")
#pragma comment(linker, "/export:GetSetting=\"C:\\Windows\\System32\\Windows.Data.Activities.dll\"")
