#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.dll\"")
#print comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.dll\"")
