#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Mirage.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Mirage.dll\"")
#print comment(linker, "/export:DllGetActivationFactoryMirage=\"C:\\Windows\\System32\\Windows.Mirage.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Mirage.dll\"")
#print comment(linker, "/export:DllGetClassObjectMirage=\"C:\\Windows\\System32\\Windows.Mirage.dll\"")
#print comment(linker, "/export:InjectDependency=\"C:\\Windows\\System32\\Windows.Mirage.dll\"")
