#print comment(linker, "/export:AqsFreeDevQueryFilter=\"C:\\Windows\\SysWOW64\\Windows.Devices.Enumeration.dll\"")
#print comment(linker, "/export:AqsToDevQueryFilter=\"C:\\Windows\\SysWOW64\\Windows.Devices.Enumeration.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.Devices.Enumeration.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.Devices.Enumeration.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.Devices.Enumeration.dll\"")
