#pragma comment(linker, "/export:BootstrapReleaseUnusedResources=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.dll\"")
#pragma comment(linker, "/export:MSPRMFDllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.dll\"")
#pragma comment(linker, "/export:MSPRMFGetClassObject=\"C:\\Windows\\System32\\Windows.Media.Protection.PlayReady.dll\"")
