#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.UI.Xaml.Maps.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.UI.Xaml.Maps.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.UI.Xaml.Maps.dll\"")
#print comment(linker, "/export:GetDependencyLocatorStorage=\"C:\\Windows\\System32\\Windows.UI.Xaml.Maps.dll\"")
#print comment(linker, "/export:XamlTestHookFreeMapsResourceLibrary=\"C:\\Windows\\System32\\Windows.UI.Xaml.Maps.dll\"")
