#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.Networking.BackgroundTransfer.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.Networking.BackgroundTransfer.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.Networking.BackgroundTransfer.dll\"")
#print comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\Windows.Networking.BackgroundTransfer.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\Windows.Networking.BackgroundTransfer.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\Windows.Networking.BackgroundTransfer.dll\"")
