#print comment(linker, "/export:CreateControlInput=\"C:\\Windows\\SysWOW64\\Windows.UI.dll\"")
#print comment(linker, "/export:CreateControlInputEx=\"C:\\Windows\\SysWOW64\\Windows.UI.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.UI.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.UI.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.UI.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\Windows.UI.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\Windows.UI.dll\"")
