#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Perception.Stub.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Perception.Stub.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetActivationFactoryPerceptionStub=\"C:\\Windows\\System32\\Windows.Perception.Stub.DllGetActivationFactoryPerceptionStub\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Perception.Stub.DllGetClassObject\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\Windows.Perception.Stub.GetProxyDllInfo\"")
