#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Security.Authentication.Web.Core.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Security.Authentication.Web.Core.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Security.Authentication.Web.Core.dll\"")
#print comment(linker, "/export:FreeIdentityProviderCookies=\"C:\\Windows\\System32\\Windows.Security.Authentication.Web.Core.dll\"")
#print comment(linker, "/export:GetIdentityProviderCookies=\"C:\\Windows\\System32\\Windows.Security.Authentication.Web.Core.dll\"")
