#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Storage.Compression.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Storage.Compression.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Storage.Compression.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\Windows.Storage.Compression.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\Windows.Storage.Compression.dll\"")
