#pragma comment(linker, "/export:CreateControlInput=\"C:\\Windows\\System32\\Windows.UI.dll\"")
#pragma comment(linker, "/export:CreateControlInputEx=\"C:\\Windows\\System32\\Windows.UI.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.UI.dll\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.UI.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.UI.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\Windows.UI.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\Windows.UI.dll\"")
