#print comment(linker, "/export:CleanupHotspotProfiles=\"C:\\Windows\\System32\\Windows.Networking.NetworkOperators.HotspotAuthentication.dll\"")
#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Networking.NetworkOperators.HotspotAuthentication.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Networking.NetworkOperators.HotspotAuthentication.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Networking.NetworkOperators.HotspotAuthentication.dll\"")
#print comment(linker, "/export:RegisterHotspotProfile=\"C:\\Windows\\System32\\Windows.Networking.NetworkOperators.HotspotAuthentication.dll\"")
