#pragma comment(linker, "/export:CreateControlInput=\"C:\\Windows\\System32\\Windows.UI.CreateControlInput\"")
#pragma comment(linker, "/export:CreateControlInputEx=\"C:\\Windows\\System32\\Windows.UI.CreateControlInputEx\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.UI.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.UI.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.UI.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\Windows.UI.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\Windows.UI.DllUnregisterServer\"")
