#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\winethc.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\winethc.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\winethc.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\winethc.dll\"")
#pragma comment(linker, "/export:ForceProxyDetectionOnNextRun=\"C:\\Windows\\System32\\winethc.dll\"")
#pragma comment(linker, "/export:SetAutoDetectProxyFlagForUser=\"C:\\Windows\\System32\\winethc.dll\"")
