#pragma comment(linker, "/export:GetLoggedOnUserCount=\"C:\\Windows\\System32\\wininitext.dll\"")
#pragma comment(linker, "/export:PrimaryTerminalAndHookWorker=\"C:\\Windows\\System32\\wininitext.dll\"")
#pragma comment(linker, "/export:StartLoadingFontsWorker=\"C:\\Windows\\System32\\wininitext.dll\"")
#pragma comment(linker, "/export:UIStartupWorker=\"C:\\Windows\\System32\\wininitext.dll\"")
#pragma comment(linker, "/export:WaitForWinstationShutdown=\"C:\\Windows\\System32\\wininitext.dll\"")
#pragma comment(linker, "/export:WinStationSystemShutdownStartedWorker=\"C:\\Windows\\System32\\wininitext.dll\"")
