#pragma comment(linker, "/export:ConfigureUserArso=\"C:\\Windows\\System32\\winlogonext.ConfigureUserArso\"")
#pragma comment(linker, "/export:EnableDisableElevationForSessionWorker=\"C:\\Windows\\System32\\winlogonext.EnableDisableElevationForSessionWorker\"")
#pragma comment(linker, "/export:NotifyInteractiveSessionLogoff=\"C:\\Windows\\System32\\winlogonext.NotifyInteractiveSessionLogoff\"")
#pragma comment(linker, "/export:UpdateUserTokenSessionId=\"C:\\Windows\\System32\\winlogonext.UpdateUserTokenSessionId\"")
#pragma comment(linker, "/export:WinLogonExt=\"C:\\Windows\\System32\\winlogonext.WinLogonExt\"")
