#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\winmde.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\winmde.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\winmde.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\winmde.dll\"")
#print comment(linker, "/export:MFCreateNetVRoot=\"C:\\Windows\\System32\\winmde.dll\"")
#print comment(linker, "/export:MFCreateWMPMDEOpCenter=\"C:\\Windows\\System32\\winmde.dll\"")
#print comment(linker, "/export:MFCreateWinMDEOpCenter=\"C:\\Windows\\System32\\winmde.dll\"")
