#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\wlansvc.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wlansvc.dll\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\wlansvc.dll\"")
#pragma comment(linker, "/export:VsIeProviderGetFunctionTable=\"C:\\Windows\\System32\\wlansvc.dll\"")
#pragma comment(linker, "/export:WLNotifyOnLogoff=\"C:\\Windows\\System32\\wlansvc.dll\"")
#pragma comment(linker, "/export:WLNotifyOnLogon=\"C:\\Windows\\System32\\wlansvc.dll\"")
#pragma comment(linker, "/export:WlanSvcMain=\"C:\\Windows\\System32\\wlansvc.dll\"")
