#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\wlangpui.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wlangpui.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\wlangpui.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\wlangpui.dll\"")
#print comment(linker, "/export:GetAdPolicyAsXML=\"C:\\Windows\\System32\\wlangpui.dll\"")
#print comment(linker, "/export:GetWmiPolicyAsXML=\"C:\\Windows\\System32\\wlangpui.dll\"")
