#pragma comment(linker, "/export:WlanIsActiveConsoleUser=\"C:\\Windows\\System32\\wlanutil.WlanIsActiveConsoleUser\"")
#pragma comment(linker, "/export:WlanSignalValueToBar=\"C:\\Windows\\System32\\wlanutil.WlanSignalValueToBar\"")
#pragma comment(linker, "/export:WlanSignalValueToBarEx=\"C:\\Windows\\System32\\wlanutil.WlanSignalValueToBarEx\"")
#pragma comment(linker, "/export:WlanSsidToDisplayName=\"C:\\Windows\\System32\\wlanutil.WlanSsidToDisplayName\"")
#pragma comment(linker, "/export:WlanStringToSsid=\"C:\\Windows\\System32\\wlanutil.WlanStringToSsid\"")
#pragma comment(linker, "/export:WlanStringToUtf8Ssid=\"C:\\Windows\\System32\\wlanutil.WlanStringToUtf8Ssid\"")
#pragma comment(linker, "/export:WlanUtf8SsidToDisplayName=\"C:\\Windows\\System32\\wlanutil.WlanUtf8SsidToDisplayName\"")
