#pragma comment(linker, "/export:WlanIsActiveConsoleUser=\"C:\\Windows\\System32\\wlanutil.dll\"")
#pragma comment(linker, "/export:WlanSignalValueToBar=\"C:\\Windows\\System32\\wlanutil.dll\"")
#pragma comment(linker, "/export:WlanSignalValueToBarEx=\"C:\\Windows\\System32\\wlanutil.dll\"")
#pragma comment(linker, "/export:WlanSsidToDisplayName=\"C:\\Windows\\System32\\wlanutil.dll\"")
#pragma comment(linker, "/export:WlanStringToSsid=\"C:\\Windows\\System32\\wlanutil.dll\"")
#pragma comment(linker, "/export:WlanStringToUtf8Ssid=\"C:\\Windows\\System32\\wlanutil.dll\"")
#pragma comment(linker, "/export:WlanUtf8SsidToDisplayName=\"C:\\Windows\\System32\\wlanutil.dll\"")
