#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wlanui.dll\"")
#pragma comment(linker, "/export:WLFreeProfile=\"C:\\Windows\\System32\\wlanui.dll\"")
#pragma comment(linker, "/export:WLFreeProfileXml=\"C:\\Windows\\System32\\wlanui.dll\"")
#pragma comment(linker, "/export:WLInvokeProfileUI=\"C:\\Windows\\System32\\wlanui.dll\"")
#pragma comment(linker, "/export:WLInvokeProfileUIFromXMLFile=\"C:\\Windows\\System32\\wlanui.dll\"")
#pragma comment(linker, "/export:WlanUIEditProfile=\"C:\\Windows\\System32\\wlanui.dll\"")
