#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\wlanui.dll\"")
#print comment(linker, "/export:WLFreeProfile=\"C:\\Windows\\SysWOW64\\wlanui.dll\"")
#print comment(linker, "/export:WLFreeProfileXml=\"C:\\Windows\\SysWOW64\\wlanui.dll\"")
#print comment(linker, "/export:WLInvokeProfileUI=\"C:\\Windows\\SysWOW64\\wlanui.dll\"")
#print comment(linker, "/export:WLInvokeProfileUIFromXMLFile=\"C:\\Windows\\SysWOW64\\wlanui.dll\"")
#print comment(linker, "/export:WlanUIEditProfile=\"C:\\Windows\\SysWOW64\\wlanui.dll\"")
