#print comment(linker, "/export:??0CCritSec@@QAE@XZ=\"C:\\Windows\\SysWOW64\\wmidcom.dll\"")
#print comment(linker, "/export:??1CCritSec@@QAE@XZ=\"C:\\Windows\\SysWOW64\\wmidcom.dll\"")
#print comment(linker, "/export:??4CAutoSetActivityId@@QAEAAV0@ABV0@@Z=\"C:\\Windows\\SysWOW64\\wmidcom.dll\"")
#print comment(linker, "/export:??4CCritSec@@QAEAAV0@ABV0@@Z=\"C:\\Windows\\SysWOW64\\wmidcom.dll\"")
#print comment(linker, "/export:MI_Application_InitializeV1=\"C:\\Windows\\SysWOW64\\wmidcom.dll\"")
