#print comment(linker, "/export:??0CCritSec@@QEAA@XZ=\"C:\\Windows\\System32\\wmidcom.dll\"")
#print comment(linker, "/export:??1CCritSec@@QEAA@XZ=\"C:\\Windows\\System32\\wmidcom.dll\"")
#print comment(linker, "/export:??4CAutoSetActivityId@@QEAAAEAV0@AEBV0@@Z=\"C:\\Windows\\System32\\wmidcom.dll\"")
#print comment(linker, "/export:??4CCritSec@@QEAAAEAV0@AEBV0@@Z=\"C:\\Windows\\System32\\wmidcom.dll\"")
#print comment(linker, "/export:MI_Application_InitializeV1=\"C:\\Windows\\System32\\wmidcom.dll\"")
