#print comment(linker, "/export:WmsgBroadcastMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.dll\"")
#print comment(linker, "/export:WmsgBroadcastNotifyMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.dll\"")
#print comment(linker, "/export:WmsgPostMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.dll\"")
#print comment(linker, "/export:WmsgPostNotifyMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.dll\"")
#print comment(linker, "/export:WmsgSendMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.dll\"")
#print comment(linker, "/export:WmsgSendPSPMessage=\"C:\\Windows\\SysWOW64\\wmsgapi.dll\"")
