#pragma comment(linker, "/export:CreateInstance=\"C:\\Windows\\System32\\WMVDECOD.DLL\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\WMVDECOD.DLL\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\WMVDECOD.DLL\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\WMVDECOD.DLL\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\WMVDECOD.DLL\"")
#pragma comment(linker, "/export:GetVC1DecoderFunctionTable=\"C:\\Windows\\System32\\WMVDECOD.DLL\"")
