#pragma comment(linker, "/export:WpbcCleanup=\"C:\\Windows\\System32\\wpbcreds.dll\"")
#pragma comment(linker, "/export:WpbcCreateRemoveTestCredentials=\"C:\\Windows\\System32\\wpbcreds.dll\"")
#pragma comment(linker, "/export:WpbcCreateTestPin=\"C:\\Windows\\System32\\wpbcreds.dll\"")
#pragma comment(linker, "/export:WpbcExportCredentials=\"C:\\Windows\\System32\\wpbcreds.dll\"")
#pragma comment(linker, "/export:WpbcGetPinInfo=\"C:\\Windows\\System32\\wpbcreds.dll\"")
#pragma comment(linker, "/export:WpbcInitialize=\"C:\\Windows\\System32\\wpbcreds.dll\"")
#pragma comment(linker, "/export:WpbcVerifyUser=\"C:\\Windows\\System32\\wpbcreds.dll\"")
