#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Wpc.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Wpc.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Wpc.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\Wpc.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\Wpc.DllUnregisterServer\"")
#pragma comment(linker, "/export:WpcTimeRestrictionsCreateLocalOverride=\"C:\\Windows\\System32\\Wpc.WpcTimeRestrictionsCreateLocalOverride\"")
