#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\WpcWebFilter.dll\"")
#print comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\WpcWebFilter.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\WpcWebFilter.dll\"")
#print comment(linker, "/export:WpcWebFilterCreate=\"C:\\Windows\\System32\\WpcWebFilter.dll\"")
#print comment(linker, "/export:WpcWebFilterDestroy=\"C:\\Windows\\System32\\WpcWebFilter.dll\"")
#print comment(linker, "/export:WpcWebFilterGet=\"C:\\Windows\\System32\\WpcWebFilter.dll\"")
