#print comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\wpdshext.dll\"")
#print comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\wpdshext.dll\"")
#print comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\wpdshext.dll\"")
#print comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\wpdshext.dll\"")
#print comment(linker, "/export:_CDefFolderMenu_MergeMenu@16=\"C:\\Windows\\SysWOW64\\wpdshext.dll\"")
