#pragma comment(linker, "/export:CDefFolderMenu_MergeMenu=\"C:\\Windows\\System32\\wpdshext.dll\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\wpdshext.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wpdshext.dll\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\wpdshext.dll\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\wpdshext.dll\"")
