#print comment(linker, "/export:WpxCreateConfig=\"C:\\Windows\\System32\\wpx.dll\"")
#print comment(linker, "/export:WpxCreateWriteOpt=\"C:\\Windows\\System32\\wpx.dll\"")
#print comment(linker, "/export:WpxGetAnswerFileType=\"C:\\Windows\\System32\\wpx.dll\"")
#print comment(linker, "/export:WpxGetDeplSettings=\"C:\\Windows\\System32\\wpx.dll\"")
#print comment(linker, "/export:WpxResetDeplSettings=\"C:\\Windows\\System32\\wpx.dll\"")
#print comment(linker, "/export:WpxSetDeplSettings=\"C:\\Windows\\System32\\wpx.dll\"")
#print comment(linker, "/export:WpxSetLogger=\"C:\\Windows\\System32\\wpx.dll\"")
#print comment(linker, "/export:WpxSetScratchDirectory=\"C:\\Windows\\System32\\wpx.dll\"")
