#pragma comment(linker, "/export:WSDCHNGRChallengeDeviceClass=\"C:\\Windows\\System32\\wsdchngr.dll\"")
#pragma comment(linker, "/export:WSDCHNGRInitialize=\"C:\\Windows\\System32\\wsdchngr.dll\"")
#pragma comment(linker, "/export:WSDCHNGRRegisterDeviceToChallenge=\"C:\\Windows\\System32\\wsdchngr.dll\"")
#pragma comment(linker, "/export:WSDCHNGRRegisterDeviceToChallengeByGlobalId=\"C:\\Windows\\System32\\wsdchngr.dll\"")
#pragma comment(linker, "/export:WSDCHNGRRemoveDevice=\"C:\\Windows\\System32\\wsdchngr.dll\"")
#pragma comment(linker, "/export:WSDCHNGRShutdown=\"C:\\Windows\\System32\\wsdchngr.dll\"")
