#pragma comment(linker, "/export:DLLGetDocumentation=\"C:\\Windows\\System32\\wshcon.DLLGetDocumentation\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\wshcon.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wshcon.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\wshcon.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\wshcon.DllUnregisterServer\"")
