#print comment(linker, "/export:WslConfigureDistribution=\"C:\\Windows\\System32\\wslapi.dll\"")
#print comment(linker, "/export:WslGetDistributionConfiguration=\"C:\\Windows\\System32\\wslapi.dll\"")
#print comment(linker, "/export:WslIsDistributionRegistered=\"C:\\Windows\\System32\\wslapi.dll\"")
#print comment(linker, "/export:WslLaunch=\"C:\\Windows\\System32\\wslapi.dll\"")
#print comment(linker, "/export:WslLaunchInteractive=\"C:\\Windows\\System32\\wslapi.dll\"")
#print comment(linker, "/export:WslRegisterDistribution=\"C:\\Windows\\System32\\wslapi.dll\"")
#print comment(linker, "/export:WslUnregisterDistribution=\"C:\\Windows\\System32\\wslapi.dll\"")
