#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\wuaueng.dll\"")
#pragma comment(linker, "/export:GeneralizeForImaging=\"C:\\Windows\\System32\\wuaueng.dll\"")
#pragma comment(linker, "/export:WUCreateExpressionEvaluator=\"C:\\Windows\\System32\\wuaueng.dll\"")
#pragma comment(linker, "/export:WUCreateUpdateHandler=\"C:\\Windows\\System32\\wuaueng.dll\"")
#pragma comment(linker, "/export:WUServiceMain=\"C:\\Windows\\System32\\wuaueng.dll\"")
