#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\wuuhosdeployment.dll\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wuuhosdeployment.dll\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\wuuhosdeployment.dll\"")
#pragma comment(linker, "/export:WUCreateExpressionEvaluator=\"C:\\Windows\\System32\\wuuhosdeployment.dll\"")
#pragma comment(linker, "/export:WUCreateUpdateHandler=\"C:\\Windows\\System32\\wuuhosdeployment.dll\"")
