#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\wvc.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wvc.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\wvc.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\wvc.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\wvc.DllUnregisterServer\"")
