#pragma comment(linker, "/export:CreateAudioReverb=\"C:\\Windows\\System32\\XAudio2_8.dll\"")
#pragma comment(linker, "/export:CreateAudioVolumeMeter=\"C:\\Windows\\System32\\XAudio2_8.dll\"")
#pragma comment(linker, "/export:CreateFX=\"C:\\Windows\\System32\\XAudio2_8.dll\"")
#pragma comment(linker, "/export:X3DAudioCalculate=\"C:\\Windows\\System32\\XAudio2_8.dll\"")
#pragma comment(linker, "/export:X3DAudioInitialize=\"C:\\Windows\\System32\\XAudio2_8.dll\"")
#pragma comment(linker, "/export:XAudio2Create=\"C:\\Windows\\System32\\XAudio2_8.dll\"")
#pragma comment(linker, "/export:XAudio2CreateWithVersionInfo=\"C:\\Windows\\System32\\XAudio2_8.dll\"")
