#print comment(linker, "/export:CreateAudioReverb=\"C:\\Windows\\SysWOW64\\XAudio2_8.dll\"")
#print comment(linker, "/export:CreateAudioVolumeMeter=\"C:\\Windows\\SysWOW64\\XAudio2_8.dll\"")
#print comment(linker, "/export:CreateFX=\"C:\\Windows\\SysWOW64\\XAudio2_8.dll\"")
#print comment(linker, "/export:X3DAudioCalculate=\"C:\\Windows\\SysWOW64\\XAudio2_8.dll\"")
#print comment(linker, "/export:X3DAudioInitialize=\"C:\\Windows\\SysWOW64\\XAudio2_8.dll\"")
#print comment(linker, "/export:XAudio2Create=\"C:\\Windows\\SysWOW64\\XAudio2_8.dll\"")
#print comment(linker, "/export:XAudio2CreateWithVersionInfo=\"C:\\Windows\\SysWOW64\\XAudio2_8.dll\"")
