#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\XInput9_1_0.dll\"")
#pragma comment(linker, "/export:XInputGetCapabilities=\"C:\\Windows\\System32\\XInput9_1_0.dll\"")
#pragma comment(linker, "/export:XInputGetDSoundAudioDeviceGuids=\"C:\\Windows\\System32\\XInput9_1_0.dll\"")
#pragma comment(linker, "/export:XInputGetState=\"C:\\Windows\\System32\\XInput9_1_0.dll\"")
#pragma comment(linker, "/export:XInputSetState=\"C:\\Windows\\System32\\XInput9_1_0.dll\"")
