#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\XInputUap.dll\"")
#pragma comment(linker, "/export:XInputEnable=\"C:\\Windows\\System32\\XInputUap.dll\"")
#pragma comment(linker, "/export:XInputGetAudioDeviceIds=\"C:\\Windows\\System32\\XInputUap.dll\"")
#pragma comment(linker, "/export:XInputGetBatteryInformation=\"C:\\Windows\\System32\\XInputUap.dll\"")
#pragma comment(linker, "/export:XInputGetCapabilities=\"C:\\Windows\\System32\\XInputUap.dll\"")
#pragma comment(linker, "/export:XInputGetKeystroke=\"C:\\Windows\\System32\\XInputUap.dll\"")
#pragma comment(linker, "/export:XInputGetState=\"C:\\Windows\\System32\\XInputUap.dll\"")
#pragma comment(linker, "/export:XInputSetState=\"C:\\Windows\\System32\\XInputUap.dll\"")
