#print comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\XInputUap.dll\"")
#print comment(linker, "/export:XInputEnable=\"C:\\Windows\\SysWOW64\\XInputUap.dll\"")
#print comment(linker, "/export:XInputGetAudioDeviceIds=\"C:\\Windows\\SysWOW64\\XInputUap.dll\"")
#print comment(linker, "/export:XInputGetBatteryInformation=\"C:\\Windows\\SysWOW64\\XInputUap.dll\"")
#print comment(linker, "/export:XInputGetCapabilities=\"C:\\Windows\\SysWOW64\\XInputUap.dll\"")
#print comment(linker, "/export:XInputGetKeystroke=\"C:\\Windows\\SysWOW64\\XInputUap.dll\"")
#print comment(linker, "/export:XInputGetState=\"C:\\Windows\\SysWOW64\\XInputUap.dll\"")
#print comment(linker, "/export:XInputSetState=\"C:\\Windows\\SysWOW64\\XInputUap.dll\"")
