#pragma comment(linker, "/export:DtcGetTransactionManager=\"C:\\Windows\\System32\\xolehlp.dll\"")
#pragma comment(linker, "/export:DtcGetTransactionManagerC=\"C:\\Windows\\System32\\xolehlp.dll\"")
#pragma comment(linker, "/export:DtcGetTransactionManagerEx=\"C:\\Windows\\System32\\xolehlp.dll\"")
#pragma comment(linker, "/export:DtcGetTransactionManagerExA=\"C:\\Windows\\System32\\xolehlp.dll\"")
#pragma comment(linker, "/export:DtcGetTransactionManagerExW=\"C:\\Windows\\System32\\xolehlp.dll\"")
#pragma comment(linker, "/export:FreezeLocalTransactionManagers=\"C:\\Windows\\System32\\xolehlp.dll\"")
#pragma comment(linker, "/export:GetDtcLocaleResourceHandle=\"C:\\Windows\\System32\\xolehlp.dll\"")
#pragma comment(linker, "/export:ThawLocalTransactionManagers=\"C:\\Windows\\System32\\xolehlp.dll\"")
