#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\audiodev.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\audiodev.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\audiodev.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\audiodev.DllUnregisterServer\"")
#pragma comment(linker, "/export:_CDefFolderMenu_MergeMenu@16=\"C:\\Windows\\SysWOW64\\audiodev._CDefFolderMenu_MergeMenu@16\"")
#pragma comment(linker, "/export:_CIDLData_CreateFromIDArray@16=\"C:\\Windows\\SysWOW64\\audiodev._CIDLData_CreateFromIDArray@16\"")
