#pragma comment(linker, "/export:DllAddRef=\"C:\\Windows\\SysWOW64\\cmstplua.DllAddRef\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\cmstplua.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\cmstplua.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\cmstplua.DllMain\"")
#pragma comment(linker, "/export:DllRelease=\"C:\\Windows\\SysWOW64\\cmstplua.DllRelease\"")
