#pragma comment(linker, "/export:DispBrokerTraceLogCallback=\"C:\\Windows\\SysWOW64\\DispBroker.DispBrokerTraceLogCallback\"")
#pragma comment(linker, "/export:DispBrokerTraceLogHelper=\"C:\\Windows\\SysWOW64\\DispBroker.DispBrokerTraceLogHelper\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\DispBroker.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\DispBroker.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\DispBroker.DllGetClassObject\"")
