#pragma comment(linker, "/export:DSCreateISecurityInfoObject=\"C:\\Windows\\SysWOW64\\dssec.DSCreateISecurityInfoObject\"")
#pragma comment(linker, "/export:DSCreateISecurityInfoObjectEx=\"C:\\Windows\\SysWOW64\\dssec.DSCreateISecurityInfoObjectEx\"")
#pragma comment(linker, "/export:DSCreateSecurityPage=\"C:\\Windows\\SysWOW64\\dssec.DSCreateSecurityPage\"")
#pragma comment(linker, "/export:DSEditSecurity=\"C:\\Windows\\SysWOW64\\dssec.DSEditSecurity\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\dssec.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\dssec.DllGetClassObject\"")
