#pragma comment(linker, "/export:CreateHrtfApo=\"C:\\Windows\\SysWOW64\\HrtfApo.CreateHrtfApo\"")
#pragma comment(linker, "/export:CreateHrtfApoWithDatasetType=\"C:\\Windows\\SysWOW64\\HrtfApo.CreateHrtfApoWithDatasetType\"")
#pragma comment(linker, "/export:CreateHrtfEngineFactory=\"C:\\Windows\\SysWOW64\\HrtfApo.CreateHrtfEngineFactory\"")
#pragma comment(linker, "/export:GetHrtfEngineMinFrameCount=\"C:\\Windows\\SysWOW64\\HrtfApo.GetHrtfEngineMinFrameCount\"")
#pragma comment(linker, "/export:IsHrtfApoAvailable=\"C:\\Windows\\SysWOW64\\HrtfApo.IsHrtfApoAvailable\"")
