#pragma comment(linker, "/export:HelperTraceEvent=\"C:\\Windows\\SysWOW64\\netdiagfx.HelperTraceEvent\"")
#pragma comment(linker, "/export:HelperTraceInitialize=\"C:\\Windows\\SysWOW64\\netdiagfx.HelperTraceInitialize\"")
#pragma comment(linker, "/export:HelperTraceUninitialize=\"C:\\Windows\\SysWOW64\\netdiagfx.HelperTraceUninitialize\"")
#pragma comment(linker, "/export:WdiDiagnosticModuleMain=\"C:\\Windows\\SysWOW64\\netdiagfx.WdiDiagnosticModuleMain\"")
#pragma comment(linker, "/export:WdiGetDiagnosticModuleInterfaceVersion=\"C:\\Windows\\SysWOW64\\netdiagfx.WdiGetDiagnosticModuleInterfaceVersion\"")
#pragma comment(linker, "/export:WdiHandleInstance=\"C:\\Windows\\SysWOW64\\netdiagfx.WdiHandleInstance\"")
