#pragma comment(linker, "/export:DeleteTaskNotification=\"C:\\Windows\\SysWOW64\\taskcomp.DeleteTaskNotification\"")
#pragma comment(linker, "/export:InitializeAdapter=\"C:\\Windows\\SysWOW64\\taskcomp.InitializeAdapter\"")
#pragma comment(linker, "/export:IsRegistering=\"C:\\Windows\\SysWOW64\\taskcomp.IsRegistering\"")
#pragma comment(linker, "/export:RegisterTaskNotification=\"C:\\Windows\\SysWOW64\\taskcomp.RegisterTaskNotification\"")
#pragma comment(linker, "/export:SetSdNotification=\"C:\\Windows\\SysWOW64\\taskcomp.SetSdNotification\"")
#pragma comment(linker, "/export:ShutdownAdapter=\"C:\\Windows\\SysWOW64\\taskcomp.ShutdownAdapter\"")
#pragma comment(linker, "/export:UpdateJobStatus=\"C:\\Windows\\SysWOW64\\taskcomp.UpdateJobStatus\"")
