#pragma comment(linker, "/export:InjectThread=\"C:\\Windows\\SysWOW64\\ttdloader.InjectThread\"")
#pragma comment(linker, "/export:ParametersBlock=\"C:\\Windows\\SysWOW64\\ttdloader.ParametersBlock\"")
#pragma comment(linker, "/export:StubDllEntry=\"C:\\Windows\\SysWOW64\\ttdloader.StubDllEntry\"")
#pragma comment(linker, "/export:StubDllEntryWow64=\"C:\\Windows\\SysWOW64\\ttdloader.StubDllEntryWow64\"")
#pragma comment(linker, "/export:TriggerOSNotification=\"C:\\Windows\\SysWOW64\\ttdloader.TriggerOSNotification\"")
