#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\usbceip.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\usbceip.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\usbceip.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\usbceip.DllUnregisterServer\"")
#pragma comment(linker, "/export:UsbCeip_Execute=\"C:\\Windows\\SysWOW64\\usbceip.UsbCeip_Execute\"")
