#pragma comment(linker, "/export:BthEvtBrCreateBroker=\"C:\\Windows\\SysWOW64\\Windows.Internal.Bluetooth.BthEvtBrCreateBroker\"")
#pragma comment(linker, "/export:BthEvtBrDeleteBroker=\"C:\\Windows\\SysWOW64\\Windows.Internal.Bluetooth.BthEvtBrDeleteBroker\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.Internal.Bluetooth.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.Internal.Bluetooth.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.Internal.Bluetooth.DllGetClassObject\"")
