#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\XInputUap.DllMain\"")
#pragma comment(linker, "/export:XInputEnable=\"C:\\Windows\\SysWOW64\\XInputUap.XInputEnable\"")
#pragma comment(linker, "/export:XInputGetAudioDeviceIds=\"C:\\Windows\\SysWOW64\\XInputUap.XInputGetAudioDeviceIds\"")
#pragma comment(linker, "/export:XInputGetBatteryInformation=\"C:\\Windows\\SysWOW64\\XInputUap.XInputGetBatteryInformation\"")
#pragma comment(linker, "/export:XInputGetCapabilities=\"C:\\Windows\\SysWOW64\\XInputUap.XInputGetCapabilities\"")
#pragma comment(linker, "/export:XInputGetKeystroke=\"C:\\Windows\\SysWOW64\\XInputUap.XInputGetKeystroke\"")
#pragma comment(linker, "/export:XInputGetState=\"C:\\Windows\\SysWOW64\\XInputUap.XInputGetState\"")
#pragma comment(linker, "/export:XInputSetState=\"C:\\Windows\\SysWOW64\\XInputUap.XInputSetState\"")
