#pragma comment(linker, "/export:Deinitialize=\"C:\\Windows\\System32\\AppVOrchestration.Deinitialize\"")
#pragma comment(linker, "/export:GetControllerComponent=\"C:\\Windows\\System32\\AppVOrchestration.GetControllerComponent\"")
#pragma comment(linker, "/export:GetControllerRequests=\"C:\\Windows\\System32\\AppVOrchestration.GetControllerRequests\"")
#pragma comment(linker, "/export:Initialize=\"C:\\Windows\\System32\\AppVOrchestration.Initialize\"")
#pragma comment(linker, "/export:InitializeISV=\"C:\\Windows\\System32\\AppVOrchestration.InitializeISV\"")
