#pragma comment(linker, "/export:JsThunk_AllocateData=\"C:\\Windows\\System32\\Chakrathunk.JsThunk_AllocateData\"")
#pragma comment(linker, "/export:JsThunk_Cleanup=\"C:\\Windows\\System32\\Chakrathunk.JsThunk_Cleanup\"")
#pragma comment(linker, "/export:JsThunk_CleanupDefer=\"C:\\Windows\\System32\\Chakrathunk.JsThunk_CleanupDefer\"")
#pragma comment(linker, "/export:JsThunk_CleanupFinish=\"C:\\Windows\\System32\\Chakrathunk.JsThunk_CleanupFinish\"")
#pragma comment(linker, "/export:JsThunk_DataToCode=\"C:\\Windows\\System32\\Chakrathunk.JsThunk_DataToCode\"")
#pragma comment(linker, "/export:JsThunk_GetSize=\"C:\\Windows\\System32\\Chakrathunk.JsThunk_GetSize\"")
#pragma comment(linker, "/export:JsThunk_InitData=\"C:\\Windows\\System32\\Chakrathunk.JsThunk_InitData\"")
#pragma comment(linker, "/export:JsThunk_Is=\"C:\\Windows\\System32\\Chakrathunk.JsThunk_Is\"")
