#pragma comment(linker, "/export:DabInitialize=\"C:\\Windows\\System32\\dab.DabInitialize\"")
#pragma comment(linker, "/export:DabNotifyPowerEvent=\"C:\\Windows\\System32\\dab.DabNotifyPowerEvent\"")
#pragma comment(linker, "/export:DabNotifySessionChange=\"C:\\Windows\\System32\\dab.DabNotifySessionChange\"")
#pragma comment(linker, "/export:DabNotifyTimeChange=\"C:\\Windows\\System32\\dab.DabNotifyTimeChange\"")
#pragma comment(linker, "/export:DabTerminate=\"C:\\Windows\\System32\\dab.DabTerminate\"")
