#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\defragsvc.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\defragsvc.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\defragsvc.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\defragsvc.DllUnregisterServer\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\defragsvc.ServiceMain\"")
