#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\dfsncimprov.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\dfsncimprov.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\dfsncimprov.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\dfsncimprov.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\dfsncimprov.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProviderClassID=\"C:\\Windows\\System32\\dfsncimprov.GetProviderClassID\"")
#pragma comment(linker, "/export:MI_Main=\"C:\\Windows\\System32\\dfsncimprov.MI_Main\"")
