#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\DfsrHelper.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\DfsrHelper.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\DfsrHelper.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\DfsrHelper.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetFileHash=\"C:\\Windows\\System32\\DfsrHelper.GetFileHash\"")
