#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\dnsmgr.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\dnsmgr.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\dnsmgr.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\dnsmgr.DllUnregisterServer\"")
#pragma comment(linker, "/export:DnsSetup=\"C:\\Windows\\System32\\dnsmgr.DnsSetup\"")
