#pragma comment(linker, "/export:MilCompositionEngine_CreateCursorController=\"C:\\Windows\\System32\\dwmcore.MilCompositionEngine_CreateCursorController\"")
#pragma comment(linker, "/export:MilCompositionEngine_GetComposedEventId=\"C:\\Windows\\System32\\dwmcore.MilCompositionEngine_GetComposedEventId\"")
#pragma comment(linker, "/export:MilCompositionEngine_Initialize=\"C:\\Windows\\System32\\dwmcore.MilCompositionEngine_Initialize\"")
#pragma comment(linker, "/export:MilCompositionEngine_Uninitialize=\"C:\\Windows\\System32\\dwmcore.MilCompositionEngine_Uninitialize\"")
#pragma comment(linker, "/export:MilConnection_CreateChannel=\"C:\\Windows\\System32\\dwmcore.MilConnection_CreateChannel\"")
#pragma comment(linker, "/export:MilTransport_AddRef=\"C:\\Windows\\System32\\dwmcore.MilTransport_AddRef\"")
#pragma comment(linker, "/export:MilTransport_Release=\"C:\\Windows\\System32\\dwmcore.MilTransport_Release\"")
