#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\eapahost.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\eapahost.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\eapahost.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\eapahost.DllUnregisterServer\"")
#pragma comment(linker, "/export:InitializeEapHost=\"C:\\Windows\\System32\\eapahost.InitializeEapHost\"")
#pragma comment(linker, "/export:UninitializeEapHost=\"C:\\Windows\\System32\\eapahost.UninitializeEapHost\"")
