#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\FrameServerClient.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\FrameServerClient.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\FrameServerClient.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\FrameServerClient.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\FrameServerClient.DllUnregisterServer\"")
