#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\gpprnext.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\gpprnext.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\gpprnext.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\gpprnext.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\gpprnext.DllUnregisterServer\"")
#pragma comment(linker, "/export:PrinterGenerateGroupPolicy=\"C:\\Windows\\System32\\gpprnext.PrinterGenerateGroupPolicy\"")
#pragma comment(linker, "/export:PrinterProcessGroupPolicy=\"C:\\Windows\\System32\\gpprnext.PrinterProcessGroupPolicy\"")
#pragma comment(linker, "/export:PrinterProcessGroupPolicyEx=\"C:\\Windows\\System32\\gpprnext.PrinterProcessGroupPolicyEx\"")
