#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\IEProxyDesktop.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\IEProxyDesktop.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\IEProxyDesktop.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\IEProxyDesktop.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\IEProxyDesktop.GetProxyDllInfo\"")
