#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\InstallServiceTasks.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\InstallServiceTasks.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\InstallServiceTasks.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\InstallServiceTasks.DllUnregisterServer\"")
#pragma comment(linker, "/export:ForceAppInUseRestart=\"C:\\Windows\\System32\\InstallServiceTasks.ForceAppInUseRestart\"")
#pragma comment(linker, "/export:GetSetting=\"C:\\Windows\\System32\\InstallServiceTasks.GetSetting\"")
