#pragma comment(linker, "/export:ClosePopupTipbar=\"C:\\Windows\\System32\\msutb.ClosePopupTipbar\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\msutb.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\msutb.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\msutb.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\msutb.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetChildTipbar=\"C:\\Windows\\System32\\msutb.GetChildTipbar\"")
#pragma comment(linker, "/export:GetPopupTipbar=\"C:\\Windows\\System32\\msutb.GetPopupTipbar\"")
#pragma comment(linker, "/export:SetRegisterLangBand=\"C:\\Windows\\System32\\msutb.SetRegisterLangBand\"")
