#pragma comment(linker, "/export:OrtGetApiBase=\"C:\\Windows\\System32\\onnxruntime.OrtGetApiBase\"")
#pragma comment(linker, "/export:OrtGetWinMLAdapter=\"C:\\Windows\\System32\\onnxruntime.OrtGetWinMLAdapter\"")
#pragma comment(linker, "/export:OrtSessionOptionsAppendExecutionProviderEx_DML=\"C:\\Windows\\System32\\onnxruntime.OrtSessionOptionsAppendExecutionProviderEx_DML\"")
#pragma comment(linker, "/export:OrtSessionOptionsAppendExecutionProvider_CPU=\"C:\\Windows\\System32\\onnxruntime.OrtSessionOptionsAppendExecutionProvider_CPU\"")
#pragma comment(linker, "/export:OrtSessionOptionsAppendExecutionProvider_DML=\"C:\\Windows\\System32\\onnxruntime.OrtSessionOptionsAppendExecutionProvider_DML\"")
