#pragma comment(linker, "/export:ExecuteUninstall=\"C:\\Windows\\System32\\osuninst.ExecuteUninstall\"")
#pragma comment(linker, "/export:GetUninstallImageSize=\"C:\\Windows\\System32\\osuninst.GetUninstallImageSize\"")
#pragma comment(linker, "/export:IsUninstallImageValid=\"C:\\Windows\\System32\\osuninst.IsUninstallImageValid\"")
#pragma comment(linker, "/export:ProvideUiAlerts=\"C:\\Windows\\System32\\osuninst.ProvideUiAlerts\"")
#pragma comment(linker, "/export:RemoveUninstallImage=\"C:\\Windows\\System32\\osuninst.RemoveUninstallImage\"")
