#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\pnpui.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\pnpui.DllGetClassObject\"")
#pragma comment(linker, "/export:InstallSecurityPrompt=\"C:\\Windows\\System32\\pnpui.InstallSecurityPrompt\"")
#pragma comment(linker, "/export:InstallSecurityPromptLUA=\"C:\\Windows\\System32\\pnpui.InstallSecurityPromptLUA\"")
#pragma comment(linker, "/export:InstallSecurityPromptRunDllW=\"C:\\Windows\\System32\\pnpui.InstallSecurityPromptRunDllW\"")
#pragma comment(linker, "/export:NotifyDevicesNeedRebootRunDllW=\"C:\\Windows\\System32\\pnpui.NotifyDevicesNeedRebootRunDllW\"")
#pragma comment(linker, "/export:SimplifiedDINotificationW=\"C:\\Windows\\System32\\pnpui.SimplifiedDINotificationW\"")
