#pragma comment(linker, "/export:??0MIFree@@QEAA@PEAX@Z=\"C:\\Windows\\System32\\prvdmofcomp.??0MIFree@@QEAA@PEAX@Z\"")
#pragma comment(linker, "/export:??1MIFree@@QEAA@XZ=\"C:\\Windows\\System32\\prvdmofcomp.??1MIFree@@QEAA@XZ\"")
#pragma comment(linker, "/export:??4MIServer@@QEAAAEAV0@$$QEAV0@@Z=\"C:\\Windows\\System32\\prvdmofcomp.??4MIServer@@QEAAAEAV0@$$QEAV0@@Z\"")
#pragma comment(linker, "/export:??4MIServer@@QEAAAEAV0@AEBV0@@Z=\"C:\\Windows\\System32\\prvdmofcomp.??4MIServer@@QEAAAEAV0@AEBV0@@Z\"")
#pragma comment(linker, "/export:CompileSchemaToWMI=\"C:\\Windows\\System32\\prvdmofcomp.CompileSchemaToWMI\"")
#pragma comment(linker, "/export:CreateRegisterParameter=\"C:\\Windows\\System32\\prvdmofcomp.CreateRegisterParameter\"")
#pragma comment(linker, "/export:GetProviderSchema=\"C:\\Windows\\System32\\prvdmofcomp.GetProviderSchema\"")
#pragma comment(linker, "/export:GetProviderSchemaFile=\"C:\\Windows\\System32\\prvdmofcomp.GetProviderSchemaFile\"")
