#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\replprov.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\replprov.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\replprov.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\replprov.DllUnregisterServer\"")
#pragma comment(linker, "/export:DoMofComp=\"C:\\Windows\\System32\\replprov.DoMofComp\"")
