#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\RoamingSecurity.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\RoamingSecurity.DllGetClassObject\"")
#pragma comment(linker, "/export:DllInstall=\"C:\\Windows\\System32\\RoamingSecurity.DllInstall\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\RoamingSecurity.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\RoamingSecurity.DllUnregisterServer\"")
