#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\SettingsHandlers_Storage.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\SettingsHandlers_Storage.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\SettingsHandlers_Storage.DllGetClassObject\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\SettingsHandlers_Storage.GetProxyDllInfo\"")
#pragma comment(linker, "/export:GetSetting=\"C:\\Windows\\System32\\SettingsHandlers_Storage.GetSetting\"")
