#pragma comment(linker, "/export:CreateModernAppToDelete=\"C:\\Windows\\System32\\ttdplm.CreateModernAppToDelete\"")
#pragma comment(linker, "/export:CreateModernAppToTrace=\"C:\\Windows\\System32\\ttdplm.CreateModernAppToTrace\"")
#pragma comment(linker, "/export:GetMaxPackageNameLength=\"C:\\Windows\\System32\\ttdplm.GetMaxPackageNameLength\"")
#pragma comment(linker, "/export:GetPackageFromPid=\"C:\\Windows\\System32\\ttdplm.GetPackageFromPid\"")
#pragma comment(linker, "/export:SetPermisionsForFolder=\"C:\\Windows\\System32\\ttdplm.SetPermisionsForFolder\"")
