#pragma comment(linker, "/export:GetServicingModeState=\"C:\\Windows\\System32\\uwfservicingapi.GetServicingModeState\"")
#pragma comment(linker, "/export:SetServicingModeState=\"C:\\Windows\\System32\\uwfservicingapi.SetServicingModeState\"")
#pragma comment(linker, "/export:UwfServicingCleanup=\"C:\\Windows\\System32\\uwfservicingapi.UwfServicingCleanup\"")
#pragma comment(linker, "/export:UwfServicingInitialize=\"C:\\Windows\\System32\\uwfservicingapi.UwfServicingInitialize\"")
#pragma comment(linker, "/export:UwfServicingWinUpdateApply=\"C:\\Windows\\System32\\uwfservicingapi.UwfServicingWinUpdateApply\"")
#pragma comment(linker, "/export:UwfServicingWinupdateCleanup=\"C:\\Windows\\System32\\uwfservicingapi.UwfServicingWinupdateCleanup\"")
#pragma comment(linker, "/export:UwfServicingWinupdateInitialize=\"C:\\Windows\\System32\\uwfservicingapi.UwfServicingWinupdateInitialize\"")
