#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\VaultRoaming.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\VaultRoaming.DllGetClassObject\"")
#pragma comment(linker, "/export:DllInstall=\"C:\\Windows\\System32\\VaultRoaming.DllInstall\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\VaultRoaming.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\VaultRoaming.DllUnregisterServer\"")
