#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\Windows.Networking.Sockets.PushEnabledApplication.DllUnregisterServer\"")
