#pragma comment(linker, "/export:BthEvtBrCreateBroker=\"C:\\Windows\\System32\\Windows.Internal.Devices.Bluetooth.BthEvtBrCreateBroker\"")
#pragma comment(linker, "/export:BthEvtBrDeleteBroker=\"C:\\Windows\\System32\\Windows.Internal.Devices.Bluetooth.BthEvtBrDeleteBroker\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Internal.Devices.Bluetooth.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Internal.Devices.Bluetooth.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Internal.Devices.Bluetooth.DllGetClassObject\"")
