#pragma comment(linker, "/export:WpbcCleanup=\"C:\\Windows\\System32\\wpbcreds.WpbcCleanup\"")
#pragma comment(linker, "/export:WpbcCreateRemoveTestCredentials=\"C:\\Windows\\System32\\wpbcreds.WpbcCreateRemoveTestCredentials\"")
#pragma comment(linker, "/export:WpbcCreateTestPin=\"C:\\Windows\\System32\\wpbcreds.WpbcCreateTestPin\"")
#pragma comment(linker, "/export:WpbcExportCredentials=\"C:\\Windows\\System32\\wpbcreds.WpbcExportCredentials\"")
#pragma comment(linker, "/export:WpbcGetPinInfo=\"C:\\Windows\\System32\\wpbcreds.WpbcGetPinInfo\"")
#pragma comment(linker, "/export:WpbcInitialize=\"C:\\Windows\\System32\\wpbcreds.WpbcInitialize\"")
#pragma comment(linker, "/export:WpbcVerifyUser=\"C:\\Windows\\System32\\wpbcreds.WpbcVerifyUser\"")
