#pragma comment(linker, "/export:AutoPilotGetOobeSettingsOverride=\"C:\\Windows\\System32\\autopilot.AutoPilotGetOobeSettingsOverride\"")
#pragma comment(linker, "/export:AutoPilotGetPolicyDwordByName=\"C:\\Windows\\System32\\autopilot.AutoPilotGetPolicyDwordByName\"")
#pragma comment(linker, "/export:AutoPilotGetPolicyStringByName=\"C:\\Windows\\System32\\autopilot.AutoPilotGetPolicyStringByName\"")
#pragma comment(linker, "/export:AutoPilotIsLocalProfileAvailable=\"C:\\Windows\\System32\\autopilot.AutoPilotIsLocalProfileAvailable\"")
#pragma comment(linker, "/export:AutoPilotIsNetworkRequired=\"C:\\Windows\\System32\\autopilot.AutoPilotIsNetworkRequired\"")
