#pragma comment(linker, "/export:BthCollectFingerprintInfo=\"C:\\Windows\\System32\\BthTelemetry.BthCollectFingerprintInfo\"")
#pragma comment(linker, "/export:BthProcessEventDataDword=\"C:\\Windows\\System32\\BthTelemetry.BthProcessEventDataDword\"")
#pragma comment(linker, "/export:BthProcessEventOccurrence=\"C:\\Windows\\System32\\BthTelemetry.BthProcessEventOccurrence\"")
#pragma comment(linker, "/export:BthProcessEventOccurrenceBthaddr=\"C:\\Windows\\System32\\BthTelemetry.BthProcessEventOccurrenceBthaddr\"")
#pragma comment(linker, "/export:BthProcessEventOccurrenceResult=\"C:\\Windows\\System32\\BthTelemetry.BthProcessEventOccurrenceResult\"")
#pragma comment(linker, "/export:BthProcessEventOccurrenceResultBthaddr=\"C:\\Windows\\System32\\BthTelemetry.BthProcessEventOccurrenceResultBthaddr\"")
