#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\CIWmi.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\CIWmi.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\CIWmi.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\CIWmi.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\CIWmi.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProviderClassID=\"C:\\Windows\\System32\\CIWmi.GetProviderClassID\"")
#pragma comment(linker, "/export:MI_Main=\"C:\\Windows\\System32\\CIWmi.MI_Main\"")
