#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\DesktopView.Internal.Broker.ProxyStub.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\DesktopView.Internal.Broker.ProxyStub.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\DesktopView.Internal.Broker.ProxyStub.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\DesktopView.Internal.Broker.ProxyStub.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\DesktopView.Internal.Broker.ProxyStub.GetProxyDllInfo\"")
