#pragma comment(linker, "/export:PushRouter_Close=\"C:\\Windows\\System32\\dmpushproxy.PushRouter_Close\"")
#pragma comment(linker, "/export:PushRouter_FreeGetMessageEventName=\"C:\\Windows\\System32\\dmpushproxy.PushRouter_FreeGetMessageEventName\"")
#pragma comment(linker, "/export:PushRouter_FreeMessage=\"C:\\Windows\\System32\\dmpushproxy.PushRouter_FreeMessage\"")
#pragma comment(linker, "/export:PushRouter_FreeMessageEx=\"C:\\Windows\\System32\\dmpushproxy.PushRouter_FreeMessageEx\"")
#pragma comment(linker, "/export:PushRouter_GetMessage=\"C:\\Windows\\System32\\dmpushproxy.PushRouter_GetMessage\"")
#pragma comment(linker, "/export:PushRouter_GetMessageEx=\"C:\\Windows\\System32\\dmpushproxy.PushRouter_GetMessageEx\"")
#pragma comment(linker, "/export:PushRouter_Open=\"C:\\Windows\\System32\\dmpushproxy.PushRouter_Open\"")
#pragma comment(linker, "/export:PushRouter_SubmitPush=\"C:\\Windows\\System32\\dmpushproxy.PushRouter_SubmitPush\"")
