#pragma comment(linker, "/export:EapProvPlugGetInfo=\"C:\\Windows\\System32\\eapprovp.EapProvPlugGetInfo\"")
#pragma comment(linker, "/export:EapProvPluginDeinitialize=\"C:\\Windows\\System32\\eapprovp.EapProvPluginDeinitialize\"")
#pragma comment(linker, "/export:EapProvPluginInitialize=\"C:\\Windows\\System32\\eapprovp.EapProvPluginInitialize\"")
#pragma comment(linker, "/export:EapProvPluginTestForAuthenticatingWlanInterfaces=\"C:\\Windows\\System32\\eapprovp.EapProvPluginTestForAuthenticatingWlanInterfaces\"")
#pragma comment(linker, "/export:EapProvPluginWlanCloseHandle=\"C:\\Windows\\System32\\eapprovp.EapProvPluginWlanCloseHandle\"")
#pragma comment(linker, "/export:EapProvPluginWlanOpenHandle=\"C:\\Windows\\System32\\eapprovp.EapProvPluginWlanOpenHandle\"")
#pragma comment(linker, "/export:EapProvPluginWlanRegisterNotification=\"C:\\Windows\\System32\\eapprovp.EapProvPluginWlanRegisterNotification\"")
