#pragma comment(linker, "/export:CreateInternetMailSyncServiceLayer=\"C:\\Windows\\System32\\internetmail.CreateInternetMailSyncServiceLayer\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\internetmail.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\internetmail.DllGetClassObject\"")
#pragma comment(linker, "/export:GetAutoConfigManager=\"C:\\Windows\\System32\\internetmail.GetAutoConfigManager\"")
#pragma comment(linker, "/export:OneStopFactory=\"C:\\Windows\\System32\\internetmail.OneStopFactory\"")
