#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\netprofm.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\netprofm.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\netprofm.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\netprofm.DllUnregisterServer\"")
#pragma comment(linker, "/export:InitHelperDll=\"C:\\Windows\\System32\\netprofm.InitHelperDll\"")
