#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\npmproxy.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\npmproxy.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\npmproxy.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\npmproxy.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\npmproxy.GetProxyDllInfo\"")
#pragma comment(linker, "/export:LANIdFreeCollection=\"C:\\Windows\\System32\\npmproxy.LANIdFreeCollection\"")
#pragma comment(linker, "/export:LANIdRetrieveCollection=\"C:\\Windows\\System32\\npmproxy.LANIdRetrieveCollection\"")
