#pragma comment(linker, "/export:??0SmartCardBiManager@@IEAA@XZ=\"C:\\Windows\\System32\\SCardBi.??0SmartCardBiManager@@IEAA@XZ\"")
#pragma comment(linker, "/export:??1SmartCardBiManager@@UEAA@XZ=\"C:\\Windows\\System32\\SCardBi.??1SmartCardBiManager@@UEAA@XZ\"")
#pragma comment(linker, "/export:??_7SmartCardBiManager@@6B@=\"C:\\Windows\\System32\\SCardBi.??_7SmartCardBiManager@@6B@\"")
#pragma comment(linker, "/export:?Initialize@SmartCardBiManager@@SAJXZ=\"C:\\Windows\\System32\\SCardBi.?Initialize@SmartCardBiManager@@SAJXZ\"")
#pragma comment(linker, "/export:?Instance@SmartCardBiManager@@SAPEAV1@XZ=\"C:\\Windows\\System32\\SCardBi.?Instance@SmartCardBiManager@@SAPEAV1@XZ\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\SCardBi.DllMain\"")
