#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\SEMgrSvc.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\SEMgrSvc.DllGetClassObject\"")
#pragma comment(linker, "/export:LaunchModernNfcEventSession=\"C:\\Windows\\System32\\SEMgrSvc.LaunchModernNfcEventSession\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\SEMgrSvc.ServiceMain\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\SEMgrSvc.SvchostPushServiceGlobals\"")
