#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\SettingsHandlers_Accessibility.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\SettingsHandlers_Accessibility.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\SettingsHandlers_Accessibility.DllGetClassObject\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\SettingsHandlers_Accessibility.GetProxyDllInfo\"")
#pragma comment(linker, "/export:GetSetting=\"C:\\Windows\\System32\\SettingsHandlers_Accessibility.GetSetting\"")
#pragma comment(linker, "/export:GetSettingForUser=\"C:\\Windows\\System32\\SettingsHandlers_Accessibility.GetSettingForUser\"")
