#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\StartTileData.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\StartTileData.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\StartTileData.DllGetClassObject\"")
#pragma comment(linker, "/export:GetSetting=\"C:\\Windows\\System32\\StartTileData.GetSetting\"")
#pragma comment(linker, "/export:HasMigratedTDLData=\"C:\\Windows\\System32\\StartTileData.HasMigratedTDLData\"")
#pragma comment(linker, "/export:ProcessStartLayoutPolicy=\"C:\\Windows\\System32\\StartTileData.ProcessStartLayoutPolicy\"")
#pragma comment(linker, "/export:TryMigrateTDLData=\"C:\\Windows\\System32\\StartTileData.TryMigrateTDLData\"")
