#pragma comment(linker, "/export:StreamingDeviceClassInstaller=\"C:\\Windows\\System32\\streamci.StreamingDeviceClassInstaller\"")
#pragma comment(linker, "/export:StreamingDeviceRemove=\"C:\\Windows\\System32\\streamci.StreamingDeviceRemove\"")
#pragma comment(linker, "/export:StreamingDeviceRemoveA=\"C:\\Windows\\System32\\streamci.StreamingDeviceRemoveA\"")
#pragma comment(linker, "/export:StreamingDeviceRemoveW=\"C:\\Windows\\System32\\streamci.StreamingDeviceRemoveW\"")
#pragma comment(linker, "/export:StreamingDeviceSetup=\"C:\\Windows\\System32\\streamci.StreamingDeviceSetup\"")
#pragma comment(linker, "/export:StreamingDeviceSetupA=\"C:\\Windows\\System32\\streamci.StreamingDeviceSetupA\"")
#pragma comment(linker, "/export:StreamingDeviceSetupW=\"C:\\Windows\\System32\\streamci.StreamingDeviceSetupW\"")
#pragma comment(linker, "/export:SwEnumCoInstaller=\"C:\\Windows\\System32\\streamci.SwEnumCoInstaller\"")
