#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\SyncSettings.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\SyncSettings.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\SyncSettings.DllGetClassObject\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\SyncSettings.GetProxyDllInfo\"")
#pragma comment(linker, "/export:GetSetting=\"C:\\Windows\\System32\\SyncSettings.GetSetting\"")
