#pragma comment(linker, "/export:DisableThreadLibraryCalls=\"C:\\Windows\\System32\\ttdloader.DisableThreadLibraryCalls\"")
#pragma comment(linker, "/export:InjectThread=\"C:\\Windows\\System32\\ttdloader.InjectThread\"")
#pragma comment(linker, "/export:ParametersBlock=\"C:\\Windows\\System32\\ttdloader.ParametersBlock\"")
#pragma comment(linker, "/export:StubDllEntry=\"C:\\Windows\\System32\\ttdloader.StubDllEntry\"")
#pragma comment(linker, "/export:ntdllLdrInitializeThunk=\"C:\\Windows\\System32\\ttdloader.ntdllLdrInitializeThunk\"")
