#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\TtlsAuth.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\TtlsAuth.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\TtlsAuth.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\TtlsAuth.DllUnregisterServer\"")
#pragma comment(linker, "/export:EapPeerFreeErrorMemory=\"C:\\Windows\\System32\\TtlsAuth.EapPeerFreeErrorMemory\"")
#pragma comment(linker, "/export:EapPeerFreeMemory=\"C:\\Windows\\System32\\TtlsAuth.EapPeerFreeMemory\"")
#pragma comment(linker, "/export:EapPeerGetInfo=\"C:\\Windows\\System32\\TtlsAuth.EapPeerGetInfo\"")
