#pragma comment(linker, "/export:CleanupUDSGlobals=\"C:\\Windows\\System32\\UserDataService.CleanupUDSGlobals\"")
#pragma comment(linker, "/export:CreateInprocConnectionHandle=\"C:\\Windows\\System32\\UserDataService.CreateInprocConnectionHandle\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\UserDataService.ServiceMain\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\UserDataService.SvchostPushServiceGlobals\"")
#pragma comment(linker, "/export:TeardownInprocConnectionHandle=\"C:\\Windows\\System32\\UserDataService.TeardownInprocConnectionHandle\"")
