#pragma comment(linker, "/export:CreateAndSetCoreAppModel=\"C:\\Windows\\System32\\WindowManagementAPI.CreateAndSetCoreAppModel\"")
#pragma comment(linker, "/export:CreateWindowInformation=\"C:\\Windows\\System32\\WindowManagementAPI.CreateWindowInformation\"")
#pragma comment(linker, "/export:CreateWindowLayout=\"C:\\Windows\\System32\\WindowManagementAPI.CreateWindowLayout\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\WindowManagementAPI.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\WindowManagementAPI.DllGetClassObject\"")
