#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\wlansvc.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\wlansvc.DllGetClassObject\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\wlansvc.SvchostPushServiceGlobals\"")
#pragma comment(linker, "/export:VsIeProviderGetFunctionTable=\"C:\\Windows\\System32\\wlansvc.VsIeProviderGetFunctionTable\"")
#pragma comment(linker, "/export:WLNotifyOnLogoff=\"C:\\Windows\\System32\\wlansvc.WLNotifyOnLogoff\"")
#pragma comment(linker, "/export:WLNotifyOnLogon=\"C:\\Windows\\System32\\wlansvc.WLNotifyOnLogon\"")
#pragma comment(linker, "/export:WlanSvcMain=\"C:\\Windows\\System32\\wlansvc.WlanSvcMain\"")
