#pragma comment(linker, "/export:??0CCritSec@@QEAA@XZ=\"C:\\Windows\\System32\\wmidcom.??0CCritSec@@QEAA@XZ\"")
#pragma comment(linker, "/export:??1CCritSec@@QEAA@XZ=\"C:\\Windows\\System32\\wmidcom.??1CCritSec@@QEAA@XZ\"")
#pragma comment(linker, "/export:??4CAutoSetActivityId@@QEAAAEAV0@AEBV0@@Z=\"C:\\Windows\\System32\\wmidcom.??4CAutoSetActivityId@@QEAAAEAV0@AEBV0@@Z\"")
#pragma comment(linker, "/export:??4CCritSec@@QEAAAEAV0@AEBV0@@Z=\"C:\\Windows\\System32\\wmidcom.??4CCritSec@@QEAAAEAV0@AEBV0@@Z\"")
#pragma comment(linker, "/export:MI_Application_InitializeV1=\"C:\\Windows\\System32\\wmidcom.MI_Application_InitializeV1\"")
