#pragma comment(linker, "/export:CompileEffectDescription=\"C:\\Windows\\System32\\wuceffects.CompileEffectDescription\"")
#pragma comment(linker, "/export:CreateCrossfadeEffectFactory=\"C:\\Windows\\System32\\wuceffects.CreateCrossfadeEffectFactory\"")
#pragma comment(linker, "/export:CreateEffectDescription=\"C:\\Windows\\System32\\wuceffects.CreateEffectDescription\"")
#pragma comment(linker, "/export:CreateInternalWallpaperBrush=\"C:\\Windows\\System32\\wuceffects.CreateInternalWallpaperBrush\"")
#pragma comment(linker, "/export:CrossFadeToNewBrush=\"C:\\Windows\\System32\\wuceffects.CrossFadeToNewBrush\"")
#pragma comment(linker, "/export:DeserializeEffectDescription=\"C:\\Windows\\System32\\wuceffects.DeserializeEffectDescription\"")
#pragma comment(linker, "/export:SerializeEffectDescription=\"C:\\Windows\\System32\\wuceffects.SerializeEffectDescription\"")
