#pragma comment(linker, "/export:CheckSSLCertificateTrust=\"C:\\Windows\\System32\\wutrust.CheckSSLCertificateTrust\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\wutrust.DllMain\"")
#pragma comment(linker, "/export:ExtractFileFromQuorumSignedInfraCAB=\"C:\\Windows\\System32\\wutrust.ExtractFileFromQuorumSignedInfraCAB\"")
#pragma comment(linker, "/export:VerifyCABIntegrity=\"C:\\Windows\\System32\\wutrust.VerifyCABIntegrity\"")
#pragma comment(linker, "/export:VerifyFileTrust=\"C:\\Windows\\System32\\wutrust.VerifyFileTrust\"")
#pragma comment(linker, "/export:VerifyMetadataIntegrityCertChains=\"C:\\Windows\\System32\\wutrust.VerifyMetadataIntegrityCertChains\"")
#pragma comment(linker, "/export:VerifyTimestampTokenCertChain=\"C:\\Windows\\System32\\wutrust.VerifyTimestampTokenCertChain\"")
