#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\XInput9_1_0.DllMain\"")
#pragma comment(linker, "/export:XInputGetCapabilities=\"C:\\Windows\\System32\\XInput9_1_0.XInputGetCapabilities\"")
#pragma comment(linker, "/export:XInputGetDSoundAudioDeviceGuids=\"C:\\Windows\\System32\\XInput9_1_0.XInputGetDSoundAudioDeviceGuids\"")
#pragma comment(linker, "/export:XInputGetState=\"C:\\Windows\\System32\\XInput9_1_0.XInputGetState\"")
#pragma comment(linker, "/export:XInputSetState=\"C:\\Windows\\System32\\XInput9_1_0.XInputSetState\"")
