#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\DavSyncProvider.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\DavSyncProvider.DllGetClassObject\"")
#pragma comment(linker, "/export:ForceCalDavCollectionsListRefreshDuringNextSync=\"C:\\Windows\\SysWOW64\\DavSyncProvider.ForceCalDavCollectionsListRefreshDuringNextSync\"")
#pragma comment(linker, "/export:HandleWebDavMeetingResponseForAppointment=\"C:\\Windows\\SysWOW64\\DavSyncProvider.HandleWebDavMeetingResponseForAppointment\"")
#pragma comment(linker, "/export:HandleWebDavMeetingResponseForMeetingNotification=\"C:\\Windows\\SysWOW64\\DavSyncProvider.HandleWebDavMeetingResponseForMeetingNotification\"")
#pragma comment(linker, "/export:UpdateCalDavTrackingSchema=\"C:\\Windows\\SysWOW64\\DavSyncProvider.UpdateCalDavTrackingSchema\"")
#pragma comment(linker, "/export:UpdateGMailContactSyncPartner=\"C:\\Windows\\SysWOW64\\DavSyncProvider.UpdateGMailContactSyncPartner\"")
