#pragma comment(linker, "/export:TelEvaluateActiveSettingAuthority=\"C:\\Windows\\SysWOW64\\DiagnosticDataSettings.TelEvaluateActiveSettingAuthority\"")
#pragma comment(linker, "/export:TelGetAllAllowedTelemetryTypes=\"C:\\Windows\\SysWOW64\\DiagnosticDataSettings.TelGetAllAllowedTelemetryTypes\"")
#pragma comment(linker, "/export:TelGetLocalAllowTelemetryRegPath=\"C:\\Windows\\SysWOW64\\DiagnosticDataSettings.TelGetLocalAllowTelemetryRegPath\"")
#pragma comment(linker, "/export:TelGetMaximumAllowedTelemetryLevel=\"C:\\Windows\\SysWOW64\\DiagnosticDataSettings.TelGetMaximumAllowedTelemetryLevel\"")
#pragma comment(linker, "/export:TelGetWerTelemetryMode=\"C:\\Windows\\SysWOW64\\DiagnosticDataSettings.TelGetWerTelemetryMode\"")
#pragma comment(linker, "/export:TelIsTelemetryTypeAllowed=\"C:\\Windows\\SysWOW64\\DiagnosticDataSettings.TelIsTelemetryTypeAllowed\"")
#pragma comment(linker, "/export:TelSetLocalTelemetrySetting=\"C:\\Windows\\SysWOW64\\DiagnosticDataSettings.TelSetLocalTelemetrySetting\"")
