#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\GameBarPresenceWriter.proxy.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\GameBarPresenceWriter.proxy.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\GameBarPresenceWriter.proxy.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\GameBarPresenceWriter.proxy.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\SysWOW64\\GameBarPresenceWriter.proxy.GetProxyDllInfo\"")
