#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\IasMigPlugin.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\IasMigPlugin.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\IasMigPlugin.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\IasMigPlugin.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\IasMigPlugin.DllUnregisterServer\"")
#pragma comment(linker, "/export:IasUpgradeComplianceCheck=\"C:\\Windows\\SysWOW64\\IasMigPlugin.IasUpgradeComplianceCheck\"")
