#pragma comment(linker, "/export:CleanUpIpPriority=\"C:\\Windows\\SysWOW64\\iprtprio.CleanUpIpPriority\"")
#pragma comment(linker, "/export:ComputeRouteMetric=\"C:\\Windows\\SysWOW64\\iprtprio.ComputeRouteMetric\"")
#pragma comment(linker, "/export:ComputeRouteMetricEx=\"C:\\Windows\\SysWOW64\\iprtprio.ComputeRouteMetricEx\"")
#pragma comment(linker, "/export:GetPriorityInfo=\"C:\\Windows\\SysWOW64\\iprtprio.GetPriorityInfo\"")
#pragma comment(linker, "/export:SetPriorityInfo=\"C:\\Windows\\SysWOW64\\iprtprio.SetPriorityInfo\"")
