#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Microsoft.Uev.Office2010CustomActions.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Microsoft.Uev.Office2010CustomActions.DllGetClassObject\"")
#pragma comment(linker, "/export:DllInstall=\"C:\\Windows\\SysWOW64\\Microsoft.Uev.Office2010CustomActions.DllInstall\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\Microsoft.Uev.Office2010CustomActions.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\Microsoft.Uev.Office2010CustomActions.DllUnregisterServer\"")
