#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\mstscax.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\mstscax.DllGetClassObject\"")
#pragma comment(linker, "/export:DllGetTscCtlVer=\"C:\\Windows\\SysWOW64\\mstscax.DllGetTscCtlVer\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\mstscax.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\mstscax.DllUnregisterServer\"")
