#pragma comment(linker, "/export:AddDemoAppLicense=\"C:\\Windows\\SysWOW64\\oemlicense.AddDemoAppLicense\"")
#pragma comment(linker, "/export:HrAddAppxLicense=\"C:\\Windows\\SysWOW64\\oemlicense.HrAddAppxLicense\"")
#pragma comment(linker, "/export:HrInstallClipLicense=\"C:\\Windows\\SysWOW64\\oemlicense.HrInstallClipLicense\"")
#pragma comment(linker, "/export:HrNotifyPhoneLicenseReady=\"C:\\Windows\\SysWOW64\\oemlicense.HrNotifyPhoneLicenseReady\"")
#pragma comment(linker, "/export:HrRemoveAppxLicense=\"C:\\Windows\\SysWOW64\\oemlicense.HrRemoveAppxLicense\"")
#pragma comment(linker, "/export:RemoveDemoAppLicense=\"C:\\Windows\\SysWOW64\\oemlicense.RemoveDemoAppLicense\"")
