#pragma comment(linker, "/export:CreateInstance=\"C:\\Windows\\SysWOW64\\RESAMPLEDMO.CreateInstance\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\RESAMPLEDMO.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\RESAMPLEDMO.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\RESAMPLEDMO.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\RESAMPLEDMO.DllUnregisterServer\"")
