#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\ShareHost.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\ShareHost.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\ShareHost.DllGetClassObject\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\SysWOW64\\ShareHost.GetProxyDllInfo\"")
#pragma comment(linker, "/export:ResolveConnectedSharePlatformToken=\"C:\\Windows\\SysWOW64\\ShareHost.ResolveConnectedSharePlatformToken\"")
