#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\SyncSettings.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\SyncSettings.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\SyncSettings.DllGetClassObject\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\SysWOW64\\SyncSettings.GetProxyDllInfo\"")
#pragma comment(linker, "/export:GetSetting=\"C:\\Windows\\SysWOW64\\SyncSettings.GetSetting\"")
