#pragma comment(linker, "/export:CloseFindContext=\"C:\\Windows\\SysWOW64\\wiadss.CloseFindContext\"")
#pragma comment(linker, "/export:FindFirstImportDS=\"C:\\Windows\\SysWOW64\\wiadss.FindFirstImportDS\"")
#pragma comment(linker, "/export:FindImportDSByDeviceName=\"C:\\Windows\\SysWOW64\\wiadss.FindImportDSByDeviceName\"")
#pragma comment(linker, "/export:FindNextImportDS=\"C:\\Windows\\SysWOW64\\wiadss.FindNextImportDS\"")
#pragma comment(linker, "/export:GetLoaderStatus=\"C:\\Windows\\SysWOW64\\wiadss.GetLoaderStatus\"")
#pragma comment(linker, "/export:LoadImportDS=\"C:\\Windows\\SysWOW64\\wiadss.LoadImportDS\"")
#pragma comment(linker, "/export:UnloadImportDS=\"C:\\Windows\\SysWOW64\\wiadss.UnloadImportDS\"")
