#pragma comment(linker, "/export:CleanupHotspotProfiles=\"C:\\Windows\\SysWOW64\\Windows.Networking.NetworkOperators.HotspotAuthentication.CleanupHotspotProfiles\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.Networking.NetworkOperators.HotspotAuthentication.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.Networking.NetworkOperators.HotspotAuthentication.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.Networking.NetworkOperators.HotspotAuthentication.DllGetClassObject\"")
#pragma comment(linker, "/export:RegisterHotspotProfile=\"C:\\Windows\\SysWOW64\\Windows.Networking.NetworkOperators.HotspotAuthentication.RegisterHotspotProfile\"")
