#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\wlanui.DllGetClassObject\"")
#pragma comment(linker, "/export:WLFreeProfile=\"C:\\Windows\\SysWOW64\\wlanui.WLFreeProfile\"")
#pragma comment(linker, "/export:WLFreeProfileXml=\"C:\\Windows\\SysWOW64\\wlanui.WLFreeProfileXml\"")
#pragma comment(linker, "/export:WLInvokeProfileUI=\"C:\\Windows\\SysWOW64\\wlanui.WLInvokeProfileUI\"")
#pragma comment(linker, "/export:WLInvokeProfileUIFromXMLFile=\"C:\\Windows\\SysWOW64\\wlanui.WLInvokeProfileUIFromXMLFile\"")
#pragma comment(linker, "/export:WlanUIEditProfile=\"C:\\Windows\\SysWOW64\\wlanui.WlanUIEditProfile\"")
