#pragma comment(linker, "/export:CheckSSLCertificateTrust=\"C:\\Windows\\SysWOW64\\wutrust.CheckSSLCertificateTrust\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\wutrust.DllMain\"")
#pragma comment(linker, "/export:ExtractFileFromQuorumSignedInfraCAB=\"C:\\Windows\\SysWOW64\\wutrust.ExtractFileFromQuorumSignedInfraCAB\"")
#pragma comment(linker, "/export:VerifyCABIntegrity=\"C:\\Windows\\SysWOW64\\wutrust.VerifyCABIntegrity\"")
#pragma comment(linker, "/export:VerifyFileTrust=\"C:\\Windows\\SysWOW64\\wutrust.VerifyFileTrust\"")
#pragma comment(linker, "/export:VerifyMetadataIntegrityCertChains=\"C:\\Windows\\SysWOW64\\wutrust.VerifyMetadataIntegrityCertChains\"")
#pragma comment(linker, "/export:VerifyTimestampTokenCertChain=\"C:\\Windows\\SysWOW64\\wutrust.VerifyTimestampTokenCertChain\"")
