#pragma comment(linker, "/export:AcmEngineApply=\"C:\\Windows\\System32\\acmigration.AcmEngineApply\"")
#pragma comment(linker, "/export:AcmEngineCollect=\"C:\\Windows\\System32\\acmigration.AcmEngineCollect\"")
#pragma comment(linker, "/export:AcmEngineCreate=\"C:\\Windows\\System32\\acmigration.AcmEngineCreate\"")
#pragma comment(linker, "/export:AcmEngineDelete=\"C:\\Windows\\System32\\acmigration.AcmEngineDelete\"")
#pragma comment(linker, "/export:AcmEngineGenerateMigXml=\"C:\\Windows\\System32\\acmigration.AcmEngineGenerateMigXml\"")
#pragma comment(linker, "/export:AcmEngineSetBaseWorkingDirectory=\"C:\\Windows\\System32\\acmigration.AcmEngineSetBaseWorkingDirectory\"")
#pragma comment(linker, "/export:AcmMatchPluginExecute=\"C:\\Windows\\System32\\acmigration.AcmMatchPluginExecute\"")
#pragma comment(linker, "/export:ApplyMigrationShimsW=\"C:\\Windows\\System32\\acmigration.ApplyMigrationShimsW\"")
