#pragma comment(linker, "/export:ActionMgrActivateService=\"C:\\Windows\\System32\\ActionMgr.ActionMgrActivateService\"")
#pragma comment(linker, "/export:ActionMgrBindToHandler=\"C:\\Windows\\System32\\ActionMgr.ActionMgrBindToHandler\"")
#pragma comment(linker, "/export:ActionMgrInitializeApi=\"C:\\Windows\\System32\\ActionMgr.ActionMgrInitializeApi\"")
#pragma comment(linker, "/export:ActionMgrRegisterJsonHandler=\"C:\\Windows\\System32\\ActionMgr.ActionMgrRegisterJsonHandler\"")
#pragma comment(linker, "/export:ActionMgrShutdownApi=\"C:\\Windows\\System32\\ActionMgr.ActionMgrShutdownApi\"")
#pragma comment(linker, "/export:ActionMgrSubmitActionJson=\"C:\\Windows\\System32\\ActionMgr.ActionMgrSubmitActionJson\"")
#pragma comment(linker, "/export:ActionMgrUnbindHandler=\"C:\\Windows\\System32\\ActionMgr.ActionMgrUnbindHandler\"")
