#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\AppManagementConfiguration.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\AppManagementConfiguration.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\AppManagementConfiguration.DllGetClassObject\"")
#pragma comment(linker, "/export:ProcessAppVPolicy=\"C:\\Windows\\System32\\AppManagementConfiguration.ProcessAppVPolicy\"")
#pragma comment(linker, "/export:ProcessUevPolicy=\"C:\\Windows\\System32\\AppManagementConfiguration.ProcessUevPolicy\"")
