#pragma comment(linker, "/export:GetApplicabilityFactory=\"C:\\Windows\\System32\\AppXApplicabilityBlob.GetApplicabilityFactory\"")
#pragma comment(linker, "/export:IsAppx=\"C:\\Windows\\System32\\AppXApplicabilityBlob.IsAppx\"")
#pragma comment(linker, "/export:IsModernApp=\"C:\\Windows\\System32\\AppXApplicabilityBlob.IsModernApp\"")
#pragma comment(linker, "/export:IsPreThresholdDesktop=\"C:\\Windows\\System32\\AppXApplicabilityBlob.IsPreThresholdDesktop\"")
#pragma comment(linker, "/export:IsPreThresholdPhone=\"C:\\Windows\\System32\\AppXApplicabilityBlob.IsPreThresholdPhone\"")
#pragma comment(linker, "/export:IsXAP=\"C:\\Windows\\System32\\AppXApplicabilityBlob.IsXAP\"")
