#pragma comment(linker, "/export:CreateDeviceInventory=\"C:\\Windows\\System32\\devinv.CreateDeviceInventory\"")
#pragma comment(linker, "/export:CreateDeviceInventoryTC=\"C:\\Windows\\System32\\devinv.CreateDeviceInventoryTC\"")
#pragma comment(linker, "/export:CreateDeviceInventoryTC2=\"C:\\Windows\\System32\\devinv.CreateDeviceInventoryTC2\"")
#pragma comment(linker, "/export:GetDevInventory=\"C:\\Windows\\System32\\devinv.GetDevInventory\"")
#pragma comment(linker, "/export:ReportDeviceAdd=\"C:\\Windows\\System32\\devinv.ReportDeviceAdd\"")
#pragma comment(linker, "/export:ReportDeviceRemove=\"C:\\Windows\\System32\\devinv.ReportDeviceRemove\"")
#pragma comment(linker, "/export:RunDeviceInventoryW=\"C:\\Windows\\System32\\devinv.RunDeviceInventoryW\"")
#pragma comment(linker, "/export:SetDevInvDebugCorrelationVector=\"C:\\Windows\\System32\\devinv.SetDevInvDebugCorrelationVector\"")
