#pragma comment(linker, "/export:CollectDiagnosticsAutoLog=\"C:\\Windows\\System32\\dmenterprisediagnostics.CollectDiagnosticsAutoLog\"")
#pragma comment(linker, "/export:GatherAutoLogEventsFromMobile=\"C:\\Windows\\System32\\dmenterprisediagnostics.GatherAutoLogEventsFromMobile\"")
#pragma comment(linker, "/export:RecordDiagnosticsError=\"C:\\Windows\\System32\\dmenterprisediagnostics.RecordDiagnosticsError\"")
#pragma comment(linker, "/export:SetupAutoLog=\"C:\\Windows\\System32\\dmenterprisediagnostics.SetupAutoLog\"")
#pragma comment(linker, "/export:StartAutoLog=\"C:\\Windows\\System32\\dmenterprisediagnostics.StartAutoLog\"")
#pragma comment(linker, "/export:StopAutoLog=\"C:\\Windows\\System32\\dmenterprisediagnostics.StopAutoLog\"")
#pragma comment(linker, "/export:TearDownAutoLog=\"C:\\Windows\\System32\\dmenterprisediagnostics.TearDownAutoLog\"")
