#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\EdgeContent.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\EdgeContent.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\EdgeContent.DllGetClassObject\"")
#pragma comment(linker, "/export:IEGetWriteableFolderPath=\"C:\\Windows\\System32\\EdgeContent.IEGetWriteableFolderPath\"")
#pragma comment(linker, "/export:IEIsInPrivateBrowsing=\"C:\\Windows\\System32\\EdgeContent.IEIsInPrivateBrowsing\"")
#pragma comment(linker, "/export:IEIsProtectedModeProcess=\"C:\\Windows\\System32\\EdgeContent.IEIsProtectedModeProcess\"")
#pragma comment(linker, "/export:IERefreshElevationPolicy=\"C:\\Windows\\System32\\EdgeContent.IERefreshElevationPolicy\"")
