#pragma comment(linker, "/export:MappingDoAction=\"C:\\Windows\\System32\\ELSCore.MappingDoAction\"")
#pragma comment(linker, "/export:MappingFreePropertyBag=\"C:\\Windows\\System32\\ELSCore.MappingFreePropertyBag\"")
#pragma comment(linker, "/export:MappingFreeServices=\"C:\\Windows\\System32\\ELSCore.MappingFreeServices\"")
#pragma comment(linker, "/export:MappingGetServices=\"C:\\Windows\\System32\\ELSCore.MappingGetServices\"")
#pragma comment(linker, "/export:MappingRecognizeText=\"C:\\Windows\\System32\\ELSCore.MappingRecognizeText\"")
