#pragma comment(linker, "/export:IEApplyCurrentHardening=\"C:\\Windows\\System32\\iesetup.IEApplyCurrentHardening\"")
#pragma comment(linker, "/export:IEHardenAdmin=\"C:\\Windows\\System32\\iesetup.IEHardenAdmin\"")
#pragma comment(linker, "/export:IEHardenAdminNow=\"C:\\Windows\\System32\\iesetup.IEHardenAdminNow\"")
#pragma comment(linker, "/export:IEHardenLMSettings=\"C:\\Windows\\System32\\iesetup.IEHardenLMSettings\"")
#pragma comment(linker, "/export:IEHardenMachineNow=\"C:\\Windows\\System32\\iesetup.IEHardenMachineNow\"")
#pragma comment(linker, "/export:IEHardenUser=\"C:\\Windows\\System32\\iesetup.IEHardenUser\"")
#pragma comment(linker, "/export:IEShowHardeningDialog=\"C:\\Windows\\System32\\iesetup.IEShowHardeningDialog\"")
