#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MaintenanceUI.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MaintenanceUI.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\MaintenanceUI.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\MaintenanceUI.DllUnregisterServer\"")
#pragma comment(linker, "/export:StartMaintenance=\"C:\\Windows\\System32\\MaintenanceUI.StartMaintenance\"")
#pragma comment(linker, "/export:StopMaintenance=\"C:\\Windows\\System32\\MaintenanceUI.StopMaintenance\"")
