#pragma comment(linker, "/export:CreateLogCabOnArea=\"C:\\Windows\\System32\\MdmDiagnostics.CreateLogCabOnArea\"")
#pragma comment(linker, "/export:CreateLogZipOnArea=\"C:\\Windows\\System32\\MdmDiagnostics.CreateLogZipOnArea\"")
#pragma comment(linker, "/export:CreateLogZipOnXml=\"C:\\Windows\\System32\\MdmDiagnostics.CreateLogZipOnXml\"")
#pragma comment(linker, "/export:CreateMdmEnterpriseDiagnosticHTMLReport=\"C:\\Windows\\System32\\MdmDiagnostics.CreateMdmEnterpriseDiagnosticHTMLReport\"")
#pragma comment(linker, "/export:CreateMdmEnterpriseDiagnosticReport=\"C:\\Windows\\System32\\MdmDiagnostics.CreateMdmEnterpriseDiagnosticReport\"")
