#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\msisip.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\msisip.DllUnregisterServer\"")
#pragma comment(linker, "/export:MsiSIPCreateIndirectData=\"C:\\Windows\\System32\\msisip.MsiSIPCreateIndirectData\"")
#pragma comment(linker, "/export:MsiSIPGetSignedDataMsg=\"C:\\Windows\\System32\\msisip.MsiSIPGetSignedDataMsg\"")
#pragma comment(linker, "/export:MsiSIPIsMyTypeOfFile=\"C:\\Windows\\System32\\msisip.MsiSIPIsMyTypeOfFile\"")
#pragma comment(linker, "/export:MsiSIPPutSignedDataMsg=\"C:\\Windows\\System32\\msisip.MsiSIPPutSignedDataMsg\"")
#pragma comment(linker, "/export:MsiSIPRemoveSignedDataMsg=\"C:\\Windows\\System32\\msisip.MsiSIPRemoveSignedDataMsg\"")
#pragma comment(linker, "/export:MsiSIPVerifyIndirectData=\"C:\\Windows\\System32\\msisip.MsiSIPVerifyIndirectData\"")
