#pragma comment(linker, "/export:IdnToAscii=\"C:\\Windows\\System32\\normaliz.IdnToAscii\"")
#pragma comment(linker, "/export:IdnToNameprepUnicode=\"C:\\Windows\\System32\\normaliz.IdnToNameprepUnicode\"")
#pragma comment(linker, "/export:IdnToUnicode=\"C:\\Windows\\System32\\normaliz.IdnToUnicode\"")
#pragma comment(linker, "/export:IsNormalizedString=\"C:\\Windows\\System32\\normaliz.IsNormalizedString\"")
#pragma comment(linker, "/export:NormalizeString=\"C:\\Windows\\System32\\normaliz.NormalizeString\"")
