#pragma comment(linker, "/export:InitializeProtocolEngine=\"C:\\Windows\\System32\\rascustom.InitializeProtocolEngine\"")
#pragma comment(linker, "/export:SendMessageToProtocolEngine=\"C:\\Windows\\System32\\rascustom.SendMessageToProtocolEngine\"")
#pragma comment(linker, "/export:UninitializeProtocolEngine=\"C:\\Windows\\System32\\rascustom.UninitializeProtocolEngine\"")
#pragma comment(linker, "/export:VpnBrokerPluginIsInstalled=\"C:\\Windows\\System32\\rascustom.VpnBrokerPluginIsInstalled\"")
#pragma comment(linker, "/export:VpnBrokerRegisterForPluginInstallations=\"C:\\Windows\\System32\\rascustom.VpnBrokerRegisterForPluginInstallations\"")
#pragma comment(linker, "/export:VpnSmCommsPluginsNotifyLogOff=\"C:\\Windows\\System32\\rascustom.VpnSmCommsPluginsNotifyLogOff\"")
#pragma comment(linker, "/export:VpnSmCommsPluginsRoamToBestCostInterface=\"C:\\Windows\\System32\\rascustom.VpnSmCommsPluginsRoamToBestCostInterface\"")
