#pragma comment(linker, "/export:NlmGetBestCostNetworkConnection=\"C:\\Windows\\System32\\rasmans.NlmGetBestCostNetworkConnection\"")
#pragma comment(linker, "/export:NlmGetCostedNetworkSettings=\"C:\\Windows\\System32\\rasmans.NlmGetCostedNetworkSettings\"")
#pragma comment(linker, "/export:NlmSetCostedNetworkSettings=\"C:\\Windows\\System32\\rasmans.NlmSetCostedNetworkSettings\"")
#pragma comment(linker, "/export:ServiceInitialized=\"C:\\Windows\\System32\\rasmans.ServiceInitialized\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\rasmans.ServiceMain\"")
#pragma comment(linker, "/export:ServiceRequestInProcess=\"C:\\Windows\\System32\\rasmans.ServiceRequestInProcess\"")
#pragma comment(linker, "/export:VpnProfileMatchingNrpt=\"C:\\Windows\\System32\\rasmans.VpnProfileMatchingNrpt\"")
#pragma comment(linker, "/export:VpnProfileNrptHasExemptions=\"C:\\Windows\\System32\\rasmans.VpnProfileNrptHasExemptions\"")
