#pragma comment(linker, "/export:CreateInstance=\"C:\\Windows\\System32\\RESAMPLEDMO.CreateInstance\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\RESAMPLEDMO.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\RESAMPLEDMO.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\RESAMPLEDMO.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\RESAMPLEDMO.DllUnregisterServer\"")
