#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\rshx32.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\rshx32.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\rshx32.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\rshx32.DllUnregisterServer\"")
#pragma comment(linker, "/export:EditFSSecurity=\"C:\\Windows\\System32\\rshx32.EditFSSecurity\"")
