#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\ShareHost.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\ShareHost.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\ShareHost.DllGetClassObject\"")
#pragma comment(linker, "/export:ResolveConnectedSharePlatformToken=\"C:\\Windows\\System32\\ShareHost.ResolveConnectedSharePlatformToken\"")
#pragma comment(linker, "/export:SerializePropertyBag=\"C:\\Windows\\System32\\ShareHost.SerializePropertyBag\"")
