#pragma comment(linker, "/export:SspiSrvClientCallback=\"C:\\Windows\\System32\\sspisrv.SspiSrvClientCallback\"")
#pragma comment(linker, "/export:SspiSrvInitialize=\"C:\\Windows\\System32\\sspisrv.SspiSrvInitialize\"")
#pragma comment(linker, "/export:SspirAcquireCredentialsHandle=\"C:\\Windows\\System32\\sspisrv.SspirAcquireCredentialsHandle\"")
#pragma comment(linker, "/export:SspirDeleteSecurityContext=\"C:\\Windows\\System32\\sspisrv.SspirDeleteSecurityContext\"")
#pragma comment(linker, "/export:SspirProcessSecurityContext=\"C:\\Windows\\System32\\sspisrv.SspirProcessSecurityContext\"")
