#pragma comment(linker, "/export:CreateInstance=\"C:\\Windows\\System32\\VIDRESZR.CreateInstance\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\VIDRESZR.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\VIDRESZR.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\VIDRESZR.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\VIDRESZR.DllUnregisterServer\"")
