#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\VSSUI.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\VSSUI.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\VSSUI.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\VSSUI.DllUnregisterServer\"")
#pragma comment(linker, "/export:ShowDialog=\"C:\\Windows\\System32\\VSSUI.ShowDialog\"")
