#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\werconcpl.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\werconcpl.DllGetClassObject\"")
#pragma comment(linker, "/export:LaunchErcAppW=\"C:\\Windows\\System32\\werconcpl.LaunchErcAppW\"")
#pragma comment(linker, "/export:ShowCEIPDialogW=\"C:\\Windows\\System32\\werconcpl.ShowCEIPDialogW\"")
#pragma comment(linker, "/export:WerpIsResponseApplicable=\"C:\\Windows\\System32\\werconcpl.WerpIsResponseApplicable\"")
