#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.StateRepositoryClient.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.StateRepositoryClient.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.StateRepositoryClient.DllGetClassObject\"")
#pragma comment(linker, "/export:SRCheckIntegrity=\"C:\\Windows\\System32\\Windows.StateRepositoryClient.SRCheckIntegrity\"")
#pragma comment(linker, "/export:SRGetPackageOriginForUser=\"C:\\Windows\\System32\\Windows.StateRepositoryClient.SRGetPackageOriginForUser\"")
#pragma comment(linker, "/export:SRGetStagedPackageOrigin=\"C:\\Windows\\System32\\Windows.StateRepositoryClient.SRGetStagedPackageOrigin\"")
#pragma comment(linker, "/export:SRRepair=\"C:\\Windows\\System32\\Windows.StateRepositoryClient.SRRepair\"")
