#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\winethc.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\winethc.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\winethc.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\winethc.DllUnregisterServer\"")
#pragma comment(linker, "/export:ForceProxyDetectionOnNextRun=\"C:\\Windows\\System32\\winethc.ForceProxyDetectionOnNextRun\"")
#pragma comment(linker, "/export:SetAutoDetectProxyFlagForUser=\"C:\\Windows\\System32\\winethc.SetAutoDetectProxyFlagForUser\"")
