#pragma comment(linker, "/export:WslConfigureDistribution=\"C:\\Windows\\System32\\wslapi.WslConfigureDistribution\"")
#pragma comment(linker, "/export:WslGetDistributionConfiguration=\"C:\\Windows\\System32\\wslapi.WslGetDistributionConfiguration\"")
#pragma comment(linker, "/export:WslIsDistributionRegistered=\"C:\\Windows\\System32\\wslapi.WslIsDistributionRegistered\"")
#pragma comment(linker, "/export:WslLaunch=\"C:\\Windows\\System32\\wslapi.WslLaunch\"")
#pragma comment(linker, "/export:WslLaunchInteractive=\"C:\\Windows\\System32\\wslapi.WslLaunchInteractive\"")
#pragma comment(linker, "/export:WslRegisterDistribution=\"C:\\Windows\\System32\\wslapi.WslRegisterDistribution\"")
#pragma comment(linker, "/export:WslUnregisterDistribution=\"C:\\Windows\\System32\\wslapi.WslUnregisterDistribution\"")
