#pragma comment(linker, "/export:CryptUIWizBuildCTL=\"C:\\Windows\\SysWOW64\\cryptuiwizard.CryptUIWizBuildCTL\"")
#pragma comment(linker, "/export:CryptUIWizDigitalSign=\"C:\\Windows\\SysWOW64\\cryptuiwizard.CryptUIWizDigitalSign\"")
#pragma comment(linker, "/export:CryptUIWizExport=\"C:\\Windows\\SysWOW64\\cryptuiwizard.CryptUIWizExport\"")
#pragma comment(linker, "/export:CryptUIWizFreeDigitalSignContext=\"C:\\Windows\\SysWOW64\\cryptuiwizard.CryptUIWizFreeDigitalSignContext\"")
#pragma comment(linker, "/export:CryptUIWizImport=\"C:\\Windows\\SysWOW64\\cryptuiwizard.CryptUIWizImport\"")
#pragma comment(linker, "/export:CryptUIWizImportInternal=\"C:\\Windows\\SysWOW64\\cryptuiwizard.CryptUIWizImportInternal\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\SysWOW64\\cryptuiwizard.DllMain\"")
#pragma comment(linker, "/export:GetFunctionTable=\"C:\\Windows\\SysWOW64\\cryptuiwizard.GetFunctionTable\"")
