#pragma comment(linker, "/export:CscNetApiGetInterface=\"C:\\Windows\\SysWOW64\\cscapi.CscNetApiGetInterface\"")
#pragma comment(linker, "/export:CscSearchApiGetInterface=\"C:\\Windows\\SysWOW64\\cscapi.CscSearchApiGetInterface\"")
#pragma comment(linker, "/export:OfflineFilesEnable=\"C:\\Windows\\SysWOW64\\cscapi.OfflineFilesEnable\"")
#pragma comment(linker, "/export:OfflineFilesGetShareCachingMode=\"C:\\Windows\\SysWOW64\\cscapi.OfflineFilesGetShareCachingMode\"")
#pragma comment(linker, "/export:OfflineFilesQueryStatus=\"C:\\Windows\\SysWOW64\\cscapi.OfflineFilesQueryStatus\"")
#pragma comment(linker, "/export:OfflineFilesQueryStatusEx=\"C:\\Windows\\SysWOW64\\cscapi.OfflineFilesQueryStatusEx\"")
#pragma comment(linker, "/export:OfflineFilesStart=\"C:\\Windows\\SysWOW64\\cscapi.OfflineFilesStart\"")
