#pragma comment(linker, "/export:PushRouter_Close=\"C:\\Windows\\SysWOW64\\dmpushproxy.PushRouter_Close\"")
#pragma comment(linker, "/export:PushRouter_FreeMessage=\"C:\\Windows\\SysWOW64\\dmpushproxy.PushRouter_FreeMessage\"")
#pragma comment(linker, "/export:PushRouter_GetMessage=\"C:\\Windows\\SysWOW64\\dmpushproxy.PushRouter_GetMessage\"")
#pragma comment(linker, "/export:PushRouter_Open=\"C:\\Windows\\SysWOW64\\dmpushproxy.PushRouter_Open\"")
#pragma comment(linker, "/export:PushRouter_SubmitPush=\"C:\\Windows\\SysWOW64\\dmpushproxy.PushRouter_SubmitPush\"")
