#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\eapsimextdesktop.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\eapsimextdesktop.DllGetClassObject\"")
#pragma comment(linker, "/export:EapSimExtCallRunWizard=\"C:\\Windows\\SysWOW64\\eapsimextdesktop.EapSimExtCallRunWizard\"")
#pragma comment(linker, "/export:EapSimExtGetIdentityPageGuid=\"C:\\Windows\\SysWOW64\\eapsimextdesktop.EapSimExtGetIdentityPageGuid\"")
#pragma comment(linker, "/export:EapSimExtInvokeUIAndGetConfig=\"C:\\Windows\\SysWOW64\\eapsimextdesktop.EapSimExtInvokeUIAndGetConfig\"")
