#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\iassam.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\iassam.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\iassam.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\iassam.DllUnregisterServer\"")
#pragma comment(linker, "/export:IASParmsQueryUserProperty=\"C:\\Windows\\SysWOW64\\iassam.IASParmsQueryUserProperty\"")
