#pragma comment(linker, "/export:IEApplyCurrentHardening=\"C:\\Windows\\SysWOW64\\iesetup.IEApplyCurrentHardening\"")
#pragma comment(linker, "/export:IEHardenAdmin=\"C:\\Windows\\SysWOW64\\iesetup.IEHardenAdmin\"")
#pragma comment(linker, "/export:IEHardenAdminNow=\"C:\\Windows\\SysWOW64\\iesetup.IEHardenAdminNow\"")
#pragma comment(linker, "/export:IEHardenLMSettings=\"C:\\Windows\\SysWOW64\\iesetup.IEHardenLMSettings\"")
#pragma comment(linker, "/export:IEHardenMachineNow=\"C:\\Windows\\SysWOW64\\iesetup.IEHardenMachineNow\"")
#pragma comment(linker, "/export:IEHardenUser=\"C:\\Windows\\SysWOW64\\iesetup.IEHardenUser\"")
#pragma comment(linker, "/export:IEShowHardeningDialog=\"C:\\Windows\\SysWOW64\\iesetup.IEShowHardeningDialog\"")
