#pragma comment(linker, "/export:Sysprep_Cleanup_IE=\"C:\\Windows\\SysWOW64\\iesysprep.Sysprep_Cleanup_IE\"")
#pragma comment(linker, "/export:Sysprep_Generalize_IE=\"C:\\Windows\\SysWOW64\\iesysprep.Sysprep_Generalize_IE\"")
#pragma comment(linker, "/export:Sysprep_Offline_Specialize_IE=\"C:\\Windows\\SysWOW64\\iesysprep.Sysprep_Offline_Specialize_IE\"")
#pragma comment(linker, "/export:Sysprep_Online_Specialize_IE=\"C:\\Windows\\SysWOW64\\iesysprep.Sysprep_Online_Specialize_IE\"")
#pragma comment(linker, "/export:Sysprep_Specialize_IE=\"C:\\Windows\\SysWOW64\\iesysprep.Sysprep_Specialize_IE\"")
