#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\mfreadwrite.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\mfreadwrite.DllGetClassObject\"")
#pragma comment(linker, "/export:MFCreateSinkWriterFromMediaSink=\"C:\\Windows\\SysWOW64\\mfreadwrite.MFCreateSinkWriterFromMediaSink\"")
#pragma comment(linker, "/export:MFCreateSinkWriterFromURL=\"C:\\Windows\\SysWOW64\\mfreadwrite.MFCreateSinkWriterFromURL\"")
#pragma comment(linker, "/export:MFCreateSourceReaderFromByteStream=\"C:\\Windows\\SysWOW64\\mfreadwrite.MFCreateSourceReaderFromByteStream\"")
#pragma comment(linker, "/export:MFCreateSourceReaderFromMediaSource=\"C:\\Windows\\SysWOW64\\mfreadwrite.MFCreateSourceReaderFromMediaSource\"")
#pragma comment(linker, "/export:MFCreateSourceReaderFromURL=\"C:\\Windows\\SysWOW64\\mfreadwrite.MFCreateSourceReaderFromURL\"")
