#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.DllUnregisterServer\"")
#pragma comment(linker, "/export:DoMsCtfMonitor=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.DoMsCtfMonitor\"")
#pragma comment(linker, "/export:InitLocalMsCtfMonitor=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.InitLocalMsCtfMonitor\"")
#pragma comment(linker, "/export:UninitLocalMsCtfMonitor=\"C:\\Windows\\SysWOW64\\MsCtfMonitor.UninitLocalMsCtfMonitor\"")
