#pragma comment(linker, "/export:??0MIFree@@QAE@PAX@Z=\"C:\\Windows\\SysWOW64\\prvdmofcomp.??0MIFree@@QAE@PAX@Z\"")
#pragma comment(linker, "/export:??1MIFree@@QAE@XZ=\"C:\\Windows\\SysWOW64\\prvdmofcomp.??1MIFree@@QAE@XZ\"")
#pragma comment(linker, "/export:??4MIServer@@QAEAAV0@$$QAV0@@Z=\"C:\\Windows\\SysWOW64\\prvdmofcomp.??4MIServer@@QAEAAV0@$$QAV0@@Z\"")
#pragma comment(linker, "/export:??4MIServer@@QAEAAV0@ABV0@@Z=\"C:\\Windows\\SysWOW64\\prvdmofcomp.??4MIServer@@QAEAAV0@ABV0@@Z\"")
#pragma comment(linker, "/export:CompileSchemaToWMI=\"C:\\Windows\\SysWOW64\\prvdmofcomp.CompileSchemaToWMI\"")
#pragma comment(linker, "/export:CreateRegisterParameter=\"C:\\Windows\\SysWOW64\\prvdmofcomp.CreateRegisterParameter\"")
#pragma comment(linker, "/export:GetProviderSchema=\"C:\\Windows\\SysWOW64\\prvdmofcomp.GetProviderSchema\"")
#pragma comment(linker, "/export:GetProviderSchemaFile=\"C:\\Windows\\SysWOW64\\prvdmofcomp.GetProviderSchemaFile\"")
