#pragma comment(linker, "/export:AqsFreeDevQueryFilter=\"C:\\Windows\\SysWOW64\\Windows.Devices.Enumeration.AqsFreeDevQueryFilter\"")
#pragma comment(linker, "/export:AqsToDevQueryFilter=\"C:\\Windows\\SysWOW64\\Windows.Devices.Enumeration.AqsToDevQueryFilter\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\Windows.Devices.Enumeration.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\SysWOW64\\Windows.Devices.Enumeration.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\Windows.Devices.Enumeration.DllGetClassObject\"")
