#pragma comment(linker, "/export:CreateInstance=\"C:\\Windows\\SysWOW64\\WMADMOD.CreateInstance\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\SysWOW64\\WMADMOD.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\SysWOW64\\WMADMOD.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\SysWOW64\\WMADMOD.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\SysWOW64\\WMADMOD.DllUnregisterServer\"")
