#pragma comment(linker, "/export:AdhEngineClose=\"C:\\Windows\\System32\\adhapi.AdhEngineClose\"")
#pragma comment(linker, "/export:AdhEngineOpen=\"C:\\Windows\\System32\\adhapi.AdhEngineOpen\"")
#pragma comment(linker, "/export:AdhGetConfig=\"C:\\Windows\\System32\\adhapi.AdhGetConfig\"")
#pragma comment(linker, "/export:AdhGetEvidenceCollectorResult=\"C:\\Windows\\System32\\adhapi.AdhGetEvidenceCollectorResult\"")
#pragma comment(linker, "/export:AdhStatusEventSubscribe=\"C:\\Windows\\System32\\adhapi.AdhStatusEventSubscribe\"")
#pragma comment(linker, "/export:AdhStatusEventUnsubscribe=\"C:\\Windows\\System32\\adhapi.AdhStatusEventUnsubscribe\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\adhapi.DllMain\"")
