#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\appsruprov.DllMain\"")
#pragma comment(linker, "/export:LogMemoryPerfCounters=\"C:\\Windows\\System32\\appsruprov.LogMemoryPerfCounters\"")
#pragma comment(linker, "/export:LogMemoryPerfCountersPeriodically=\"C:\\Windows\\System32\\appsruprov.LogMemoryPerfCountersPeriodically\"")
#pragma comment(linker, "/export:PsmQueryApplicationPerformanceInformation=\"C:\\Windows\\System32\\appsruprov.PsmQueryApplicationPerformanceInformation\"")
#pragma comment(linker, "/export:PsmQueryApplicationPerformanceInformation2=\"C:\\Windows\\System32\\appsruprov.PsmQueryApplicationPerformanceInformation2\"")
#pragma comment(linker, "/export:PsmQueryQuotaInformation=\"C:\\Windows\\System32\\appsruprov.PsmQueryQuotaInformation\"")
#pragma comment(linker, "/export:SruInitializeProvider=\"C:\\Windows\\System32\\appsruprov.SruInitializeProvider\"")
#pragma comment(linker, "/export:SruUninitializeProvider=\"C:\\Windows\\System32\\appsruprov.SruUninitializeProvider\"")
