#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Chakradiag.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Chakradiag.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\Chakradiag.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\Chakradiag.DllUnregisterServer\"")
#pragma comment(linker, "/export:FreeDumpStreams=\"C:\\Windows\\System32\\Chakradiag.FreeDumpStreams\"")
#pragma comment(linker, "/export:GetDumpStreams=\"C:\\Windows\\System32\\Chakradiag.GetDumpStreams\"")
