#pragma comment(linker, "/export:ModernColorGetGDILutFromHDC=\"C:\\Windows\\System32\\coloradapterclient.ModernColorGetGDILutFromHDC\"")
#pragma comment(linker, "/export:ModernColorSetGDILut=\"C:\\Windows\\System32\\coloradapterclient.ModernColorSetGDILut\"")
#pragma comment(linker, "/export:ModernColorSetGDILutFromHDC=\"C:\\Windows\\System32\\coloradapterclient.ModernColorSetGDILutFromHDC\"")
#pragma comment(linker, "/export:ModernColorSetLut=\"C:\\Windows\\System32\\coloradapterclient.ModernColorSetLut\"")
#pragma comment(linker, "/export:ModernColorSetMatrix=\"C:\\Windows\\System32\\coloradapterclient.ModernColorSetMatrix\"")
#pragma comment(linker, "/export:ModernColorSetMatrixFromHDC=\"C:\\Windows\\System32\\coloradapterclient.ModernColorSetMatrixFromHDC\"")
