#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\easinvoker.proxystub.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\easinvoker.proxystub.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\easinvoker.proxystub.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\easinvoker.proxystub.DllUnregisterServer\"")
#pragma comment(linker, "/export:GetProxyDllInfo=\"C:\\Windows\\System32\\easinvoker.proxystub.GetProxyDllInfo\"")
