#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\EsclWiaDriver.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\EsclWiaDriver.DllGetClassObject\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\EsclWiaDriver.DllMain\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\EsclWiaDriver.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\EsclWiaDriver.DllUnregisterServer\"")
