#pragma comment(linker, "/export:CloseFileRestoreContext=\"C:\\Windows\\System32\\fmapi.CloseFileRestoreContext\"")
#pragma comment(linker, "/export:CreateFileRestoreContext=\"C:\\Windows\\System32\\fmapi.CreateFileRestoreContext\"")
#pragma comment(linker, "/export:DetectBootSector=\"C:\\Windows\\System32\\fmapi.DetectBootSector\"")
#pragma comment(linker, "/export:DetectEncryptedVolume=\"C:\\Windows\\System32\\fmapi.DetectEncryptedVolume\"")
#pragma comment(linker, "/export:DetectEncryptedVolumeEx=\"C:\\Windows\\System32\\fmapi.DetectEncryptedVolumeEx\"")
#pragma comment(linker, "/export:RestoreFile=\"C:\\Windows\\System32\\fmapi.RestoreFile\"")
#pragma comment(linker, "/export:ScanRestorableFiles=\"C:\\Windows\\System32\\fmapi.ScanRestorableFiles\"")
#pragma comment(linker, "/export:SupplyDecryptionInfo=\"C:\\Windows\\System32\\fmapi.SupplyDecryptionInfo\"")
