#pragma comment(linker, "/export:HvlExchangeDispatchInterface=\"C:\\Windows\\System32\\hvloader.HvlExchangeDispatchInterface\"")
#pragma comment(linker, "/export:HvlLaunchHypervisor=\"C:\\Windows\\System32\\hvloader.HvlLaunchHypervisor\"")
#pragma comment(linker, "/export:HvlLoadHypervisor=\"C:\\Windows\\System32\\hvloader.HvlLoadHypervisor\"")
#pragma comment(linker, "/export:HvlPreloadHypervisor=\"C:\\Windows\\System32\\hvloader.HvlPreloadHypervisor\"")
#pragma comment(linker, "/export:HvlRegisterRuntimeRange=\"C:\\Windows\\System32\\hvloader.HvlRegisterRuntimeRange\"")
#pragma comment(linker, "/export:HvlRescindVsm=\"C:\\Windows\\System32\\hvloader.HvlRescindVsm\"")
#pragma comment(linker, "/export:HvlUpdateMcUpdateStatus=\"C:\\Windows\\System32\\hvloader.HvlUpdateMcUpdateStatus\"")
