#pragma comment(linker, "/export:DetectNAT=\"C:\\Windows\\System32\\igdDiag.DetectNAT\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\igdDiag.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\igdDiag.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\igdDiag.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\igdDiag.DllUnregisterServer\"")
