#pragma comment(linker, "/export:CreateInputMethodClient=\"C:\\Windows\\System32\\InputService.CreateInputMethodClient\"")
#pragma comment(linker, "/export:CreateKeyEventProcessor=\"C:\\Windows\\System32\\InputService.CreateKeyEventProcessor\"")
#pragma comment(linker, "/export:InitializeService=\"C:\\Windows\\System32\\InputService.InitializeService\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\InputService.ServiceMain\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\InputService.SvchostPushServiceGlobals\"")
#pragma comment(linker, "/export:UninitializeService=\"C:\\Windows\\System32\\InputService.UninitializeService\"")
