#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\lltdapi.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\lltdapi.DllGetClassObject\"")
#pragma comment(linker, "/export:LLTDCreateEnumerator=\"C:\\Windows\\System32\\lltdapi.LLTDCreateEnumerator\"")
#pragma comment(linker, "/export:LLTDCreateMapFromXML=\"C:\\Windows\\System32\\lltdapi.LLTDCreateMapFromXML\"")
#pragma comment(linker, "/export:LLTDCreateMapper=\"C:\\Windows\\System32\\lltdapi.LLTDCreateMapper\"")
#pragma comment(linker, "/export:LLTDCreateNode=\"C:\\Windows\\System32\\lltdapi.LLTDCreateNode\"")
