#pragma comment(linker, "/export:?AfxFreeLibrary@@YAHPEAUHINSTANCE__@@@Z=\"C:\\Windows\\System32\\mfc42.?AfxFreeLibrary@@YAHPEAUHINSTANCE__@@@Z\"")
#pragma comment(linker, "/export:?AfxLoadLibrary@@YAPEAUHINSTANCE__@@PEBD@Z=\"C:\\Windows\\System32\\mfc42.?AfxLoadLibrary@@YAPEAUHINSTANCE__@@PEBD@Z\"")
#pragma comment(linker, "/export:?AfxLockGlobals@@YAXH@Z=\"C:\\Windows\\System32\\mfc42.?AfxLockGlobals@@YAXH@Z\"")
#pragma comment(linker, "/export:?AfxUnlockGlobals@@YAXH@Z=\"C:\\Windows\\System32\\mfc42.?AfxUnlockGlobals@@YAXH@Z\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\mfc42.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\mfc42.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\mfc42.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\mfc42.DllUnregisterServer\"")
