#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\MFPlay.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\MFPlay.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\MFPlay.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\MFPlay.DllUnregisterServer\"")
#pragma comment(linker, "/export:MFPCreateMediaPlayer=\"C:\\Windows\\System32\\MFPlay.MFPCreateMediaPlayer\"")
#pragma comment(linker, "/export:MFPCreateMediaPlayerEx=\"C:\\Windows\\System32\\MFPlay.MFPCreateMediaPlayerEx\"")
