#pragma comment(linker, "/export:NetDriverInstallClose=\"C:\\Windows\\System32\\NetDriverInstall.NetDriverInstallClose\"")
#pragma comment(linker, "/export:NetDriverInstallCommit=\"C:\\Windows\\System32\\NetDriverInstall.NetDriverInstallCommit\"")
#pragma comment(linker, "/export:NetDriverInstallInitialize=\"C:\\Windows\\System32\\NetDriverInstall.NetDriverInstallInitialize\"")
#pragma comment(linker, "/export:NetDriverInstallProcessAdditions=\"C:\\Windows\\System32\\NetDriverInstall.NetDriverInstallProcessAdditions\"")
#pragma comment(linker, "/export:NetDriverInstallProcessRemovals=\"C:\\Windows\\System32\\NetDriverInstall.NetDriverInstallProcessRemovals\"")
#pragma comment(linker, "/export:NetDriverInstallSync=\"C:\\Windows\\System32\\NetDriverInstall.NetDriverInstallSync\"")
