#pragma comment(linker, "/export:ClearAutoLogon=\"C:\\Windows\\System32\\netplwiz.ClearAutoLogon\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\netplwiz.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\netplwiz.DllGetClassObject\"")
#pragma comment(linker, "/export:NetAccessWizard=\"C:\\Windows\\System32\\netplwiz.NetAccessWizard\"")
#pragma comment(linker, "/export:NetPlacesWizardDoModal=\"C:\\Windows\\System32\\netplwiz.NetPlacesWizardDoModal\"")
#pragma comment(linker, "/export:SHDisconnectNetDrives=\"C:\\Windows\\System32\\netplwiz.SHDisconnectNetDrives\"")
#pragma comment(linker, "/export:UsersRunDllW=\"C:\\Windows\\System32\\netplwiz.UsersRunDllW\"")
