#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\NetSetupShim.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\NetSetupShim.DllGetClassObject\"")
#pragma comment(linker, "/export:NetSetupCreateBindingMap=\"C:\\Windows\\System32\\NetSetupShim.NetSetupCreateBindingMap\"")
#pragma comment(linker, "/export:NetSetupExportDatabase=\"C:\\Windows\\System32\\NetSetupShim.NetSetupExportDatabase\"")
#pragma comment(linker, "/export:NetSetupResetBindings=\"C:\\Windows\\System32\\NetSetupShim.NetSetupResetBindings\"")
#pragma comment(linker, "/export:NetSetupShimExecuteInfSection=\"C:\\Windows\\System32\\NetSetupShim.NetSetupShimExecuteInfSection\"")
