#pragma comment(linker, "/export:IdpConfigAddPolicy=\"C:\\Windows\\System32\\nshwfp.IdpConfigAddPolicy\"")
#pragma comment(linker, "/export:IdpConfigAllocateAndGetPolicy=\"C:\\Windows\\System32\\nshwfp.IdpConfigAllocateAndGetPolicy\"")
#pragma comment(linker, "/export:IdpConfigFreePolicy=\"C:\\Windows\\System32\\nshwfp.IdpConfigFreePolicy\"")
#pragma comment(linker, "/export:IdpConfigInitDefaultPolicy=\"C:\\Windows\\System32\\nshwfp.IdpConfigInitDefaultPolicy\"")
#pragma comment(linker, "/export:IdpConfigRemovePolicy=\"C:\\Windows\\System32\\nshwfp.IdpConfigRemovePolicy\"")
#pragma comment(linker, "/export:InitHelperDll=\"C:\\Windows\\System32\\nshwfp.InitHelperDll\"")
#pragma comment(linker, "/export:WfpCaptureExportedW=\"C:\\Windows\\System32\\nshwfp.WfpCaptureExportedW\"")
#pragma comment(linker, "/export:WfpCaptureStop=\"C:\\Windows\\System32\\nshwfp.WfpCaptureStop\"")
