#pragma comment(linker, "/export:PcaGetFileInfoFromPath=\"C:\\Windows\\System32\\pcacli.PcaGetFileInfoFromPath\"")
#pragma comment(linker, "/export:PcaIsPcaDisabled=\"C:\\Windows\\System32\\pcacli.PcaIsPcaDisabled\"")
#pragma comment(linker, "/export:PcaLinkChildProcessToParent=\"C:\\Windows\\System32\\pcacli.PcaLinkChildProcessToParent\"")
#pragma comment(linker, "/export:PcaMonitorProcess=\"C:\\Windows\\System32\\pcacli.PcaMonitorProcess\"")
#pragma comment(linker, "/export:PcaMonitorProcess2=\"C:\\Windows\\System32\\pcacli.PcaMonitorProcess2\"")
#pragma comment(linker, "/export:PcaNotifyMsiInstall=\"C:\\Windows\\System32\\pcacli.PcaNotifyMsiInstall\"")
#pragma comment(linker, "/export:PcaNotifyStatusIcon=\"C:\\Windows\\System32\\pcacli.PcaNotifyStatusIcon\"")
#pragma comment(linker, "/export:PcaSendToService=\"C:\\Windows\\System32\\pcacli.PcaSendToService\"")
