#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\PortableDeviceClassExtension.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\PortableDeviceClassExtension.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\PortableDeviceClassExtension.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\PortableDeviceClassExtension.DllUnregisterServer\"")
#pragma comment(linker, "/export:Microsoft_WDF_UMDF_Version=\"C:\\Windows\\System32\\PortableDeviceClassExtension.Microsoft_WDF_UMDF_Version\"")
