#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\PrinterCleanupTask.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\PrinterCleanupTask.DllGetClassObject\"")
#pragma comment(linker, "/export:DllRegisterServer=\"C:\\Windows\\System32\\PrinterCleanupTask.DllRegisterServer\"")
#pragma comment(linker, "/export:DllUnregisterServer=\"C:\\Windows\\System32\\PrinterCleanupTask.DllUnregisterServer\"")
#pragma comment(linker, "/export:EnablePrinterCleanUpTask=\"C:\\Windows\\System32\\PrinterCleanupTask.EnablePrinterCleanUpTask\"")
#pragma comment(linker, "/export:SetLastUserInteractionDate=\"C:\\Windows\\System32\\PrinterCleanupTask.SetLastUserInteractionDate\"")
