#pragma comment(linker, "/export:RdrSysprepSpecialize=\"C:\\Windows\\System32\\radardt.RdrSysprepSpecialize\"")
#pragma comment(linker, "/export:RdrSysprepSpecializeOffline=\"C:\\Windows\\System32\\radardt.RdrSysprepSpecializeOffline\"")
#pragma comment(linker, "/export:WdiDiagnosticModuleMain=\"C:\\Windows\\System32\\radardt.WdiDiagnosticModuleMain\"")
#pragma comment(linker, "/export:WdiGetDiagnosticModuleInterfaceVersion=\"C:\\Windows\\System32\\radardt.WdiGetDiagnosticModuleInterfaceVersion\"")
#pragma comment(linker, "/export:WdiHandleInstance=\"C:\\Windows\\System32\\radardt.WdiHandleInstance\"")
