#pragma comment(linker, "/export:CreateRdpUdpStreamWrapper=\"C:\\Windows\\System32\\rdpnano.CreateRdpUdpStreamWrapper\"")
#pragma comment(linker, "/export:CreateRdpWebSocketStreamWrapper=\"C:\\Windows\\System32\\rdpnano.CreateRdpWebSocketStreamWrapper\"")
#pragma comment(linker, "/export:DllMain=\"C:\\Windows\\System32\\rdpnano.DllMain\"")
#pragma comment(linker, "/export:FreeRdpUdpStreamWrapper=\"C:\\Windows\\System32\\rdpnano.FreeRdpUdpStreamWrapper\"")
#pragma comment(linker, "/export:FreeRdpWebSocketStreamWrapper=\"C:\\Windows\\System32\\rdpnano.FreeRdpWebSocketStreamWrapper\"")
