#pragma comment(linker, "/export:ShutdownExAnnotate=\"C:\\Windows\\System32\\shutdownext.ShutdownExAnnotate\"")
#pragma comment(linker, "/export:ShutdownExDirtyDialog=\"C:\\Windows\\System32\\shutdownext.ShutdownExDirtyDialog\"")
#pragma comment(linker, "/export:ShutdownExPrintReasons=\"C:\\Windows\\System32\\shutdownext.ShutdownExPrintReasons\"")
#pragma comment(linker, "/export:ShutdownExReasonCommentRequired=\"C:\\Windows\\System32\\shutdownext.ShutdownExReasonCommentRequired\"")
#pragma comment(linker, "/export:ShutdownExRemoteDialog=\"C:\\Windows\\System32\\shutdownext.ShutdownExRemoteDialog\"")
