#pragma comment(linker, "/export:SssBindServicingStack=\"C:\\Windows\\System32\\SSShim.SssBindServicingStack\"")
#pragma comment(linker, "/export:SssGetServicingStackFilePath=\"C:\\Windows\\System32\\SSShim.SssGetServicingStackFilePath\"")
#pragma comment(linker, "/export:SssGetServicingStackFilePathLength=\"C:\\Windows\\System32\\SSShim.SssGetServicingStackFilePathLength\"")
#pragma comment(linker, "/export:SssPreloadDownlevelDependencies=\"C:\\Windows\\System32\\SSShim.SssPreloadDownlevelDependencies\"")
#pragma comment(linker, "/export:SssReleaseServicingStack=\"C:\\Windows\\System32\\SSShim.SssReleaseServicingStack\"")
