#pragma comment(linker, "/export:AttemptToUpdateTimeZone=\"C:\\Windows\\System32\\tzautoupdate.AttemptToUpdateTimeZone\"")
#pragma comment(linker, "/export:AttemptToUpdateTimeZoneAndEnableChangeDetection=\"C:\\Windows\\System32\\tzautoupdate.AttemptToUpdateTimeZoneAndEnableChangeDetection\"")
#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\tzautoupdate.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\tzautoupdate.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\tzautoupdate.DllGetClassObject\"")
#pragma comment(linker, "/export:ServiceMain=\"C:\\Windows\\System32\\tzautoupdate.ServiceMain\"")
#pragma comment(linker, "/export:SvchostPushServiceGlobals=\"C:\\Windows\\System32\\tzautoupdate.SvchostPushServiceGlobals\"")
