#pragma comment(linker, "/export:WIATRACE_DecrementIndentLevel=\"C:\\Windows\\System32\\wiatrace.WIATRACE_DecrementIndentLevel\"")
#pragma comment(linker, "/export:WIATRACE_GetIndentLevel=\"C:\\Windows\\System32\\wiatrace.WIATRACE_GetIndentLevel\"")
#pragma comment(linker, "/export:WIATRACE_GetTraceSettings=\"C:\\Windows\\System32\\wiatrace.WIATRACE_GetTraceSettings\"")
#pragma comment(linker, "/export:WIATRACE_IncrementIndentLevel=\"C:\\Windows\\System32\\wiatrace.WIATRACE_IncrementIndentLevel\"")
#pragma comment(linker, "/export:WIATRACE_Init=\"C:\\Windows\\System32\\wiatrace.WIATRACE_Init\"")
#pragma comment(linker, "/export:WIATRACE_OutputString=\"C:\\Windows\\System32\\wiatrace.WIATRACE_OutputString\"")
#pragma comment(linker, "/export:WIATRACE_SetTraceSettings=\"C:\\Windows\\System32\\wiatrace.WIATRACE_SetTraceSettings\"")
#pragma comment(linker, "/export:WIATRACE_Term=\"C:\\Windows\\System32\\wiatrace.WIATRACE_Term\"")
