#pragma comment(linker, "/export:DllCanUnloadNow=\"C:\\Windows\\System32\\Windows.Mirage.Internal.DllCanUnloadNow\"")
#pragma comment(linker, "/export:DllGetActivationFactory=\"C:\\Windows\\System32\\Windows.Mirage.Internal.DllGetActivationFactory\"")
#pragma comment(linker, "/export:DllGetActivationFactoryMirageInternal=\"C:\\Windows\\System32\\Windows.Mirage.Internal.DllGetActivationFactoryMirageInternal\"")
#pragma comment(linker, "/export:DllGetClassObject=\"C:\\Windows\\System32\\Windows.Mirage.Internal.DllGetClassObject\"")
#pragma comment(linker, "/export:InjectDependencyInternal=\"C:\\Windows\\System32\\Windows.Mirage.Internal.InjectDependencyInternal\"")
