#pragma comment(linker, "/export:CreateXmlReader=\"C:\\Windows\\System32\\xmllite.CreateXmlReader\"")
#pragma comment(linker, "/export:CreateXmlReaderInputWithEncodingCodePage=\"C:\\Windows\\System32\\xmllite.CreateXmlReaderInputWithEncodingCodePage\"")
#pragma comment(linker, "/export:CreateXmlReaderInputWithEncodingName=\"C:\\Windows\\System32\\xmllite.CreateXmlReaderInputWithEncodingName\"")
#pragma comment(linker, "/export:CreateXmlWriter=\"C:\\Windows\\System32\\xmllite.CreateXmlWriter\"")
#pragma comment(linker, "/export:CreateXmlWriterOutputWithEncodingCodePage=\"C:\\Windows\\System32\\xmllite.CreateXmlWriterOutputWithEncodingCodePage\"")
#pragma comment(linker, "/export:CreateXmlWriterOutputWithEncodingName=\"C:\\Windows\\System32\\xmllite.CreateXmlWriterOutputWithEncodingName\"")
